/**
 * fal.ai Account — billing, focus reports, model access controls, and account metadata
 *
 * Auto-generated by scripts/falai-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: Apache-2.0

import { z } from "npm:zod@4.4.3";
import { falApi } from "./_lib/api.ts";

const EXTENSION_NAME = "@webframp/falai/account";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiToken: z.string().meta({ sensitive: true }).describe(
    "fal.ai API key; overrides the FAL_KEY environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
});

const GetAccountBillingSchema = z.object({
  username: z.string().describe("Account username"),
  credits: z.object({
    current_balance: z.number().min(0),
    currency: z.string(),
  }).optional().describe(
    "Credit balance details. Only present when 'credits' is included in expand parameter.",
  ),
}).passthrough();

const GetMetaItemSchema = z.string();

const GetMetaSchema = z.object({
  items: z.array(GetMetaItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

// =============================================================================
// Model Definition
// =============================================================================

/** fal.ai Account — billing, focus reports, model access controls, and account metadata */
export const model = {
  type: "@webframp/falai/account",
  version: "2026.09.09.1",
  globalArguments: GlobalArgsSchema,

  upgrades: [],

  resources: {
    "account_billing": {
      description: "Account Billing",
      schema: GetAccountBillingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "get_meta": {
      description: "Get platform metadata",
      schema: GetMetaSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
  },

  methods: {
    get_account_billing: {
      description: "Account Billing",
      arguments: z.object({
        expand: z.union([z.string(), z.array(z.string())]).optional().describe(
          "Data to include in the response. Use 'credits' to include current credit balance.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken } = context.globalArgs;

        const queryParts: string[] = [];
        const queryKeys = new Set(["expand"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && queryKeys.has(k)) {
            queryParts.push(`${k}=${encodeURIComponent(String(v))}`);
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const result = await falApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/account/billing${qs}`,
        );

        const handle = await context.writeResource(
          "account_billing",
          "latest",
          result,
        );
        context.logger.info("Fetched account_billing", {});
        return { dataHandles: [handle] };
      },
    },
    get_meta: {
      description: "Get platform metadata",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken } = context.globalArgs;
        const startMs = Date.now();
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }
        const qs = new URLSearchParams(params).toString();
        const url = qs ? `/meta?${qs}` : `/meta`;

        const result = await falApi<Record<string, unknown>>(
          apiToken,
          "GET",
          url,
        );
        const items =
          (result as Record<string, unknown>)["webhook_ip_ranges"] ?? [];

        const handle = await context.writeResource("get_meta", "main", {
          items,
          truncated: false,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} get_meta", {
          count: (items as unknown[]).length,
        });
        return { dataHandles: [handle] };
      },
    },
  },
};
