/**
 * Snyk Assets — asset discovery and classification across the group
 *
 * Auto-generated by scripts/snyk-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: AGPL-3.0-or-later WITH Swamp-Extension-Exception

import { z } from "npm:zod@4.4.3";
import { snykApi, snykApiPaginated } from "./_lib/api.ts";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiToken: z.string().meta({ sensitive: true }).describe("Snyk API token"),
  groupId: z.string().describe("Snyk group ID"),
  version: z.string().default("2024-10-15").describe("Snyk API version date"),
});

const ListAssetsSchema = z.object({
  id: z.string(),
  type: z.enum(["repository", "image", "package"]).optional(),
  app_context: z.object({}).nullable().optional().describe(
    "asset metadata from App Context integrations",
  ),
  archived: z.boolean().optional().describe(
    "Indicates if the asset is archived",
  ),
  base_image: z.string().nullable().optional().describe(
    "Base image of the container image",
  ),
  browse_url: z.string().nullable().optional().describe(
    "URL to browse the asset",
  ),
  class: z.object({
    locked: z.boolean().optional(),
    name: z.string().optional(),
    rank: z.number().int().optional(),
  }).optional(),
  coverage_controls: z.array(z.unknown()).optional(),
  created_at: z.string().optional().describe("Creation timestamp"),
  default_branch_name: z.string().nullable().optional().describe(
    "Default branch name of the repository",
  ),
  developers: z.array(z.unknown()).optional().describe(
    "List of developers associated with the asset",
  ),
  file_path: z.string().nullable().optional().describe(
    "File path of the asset",
  ),
  image_digests: z.array(z.string()).nullable().optional().describe(
    "List of digests for the container image",
  ),
  image_id: z.string().nullable().optional().describe(
    "ID of the container image",
  ),
  image_registries: z.array(z.string()).nullable().optional().describe(
    "List of registries containing the container image",
  ),
  image_repositories: z.array(z.string()).nullable().optional().describe(
    "List of repositories containing the container image",
  ),
  image_tags: z.array(z.string()).nullable().optional().describe(
    "List of tags for the container image",
  ),
  languages: z.record(z.string(), z.number().int()).nullable().optional()
    .describe("Languages used in the asset with usage counts"),
  name: z.string().nullable().optional().describe(
    "Name of the asset of the file path",
  ),
  repository_freshness: z.string().nullable().optional().describe(
    "Indicating the activity level of the repository",
  ),
  repository_url: z.string().nullable().optional().describe(
    "URL to the asset's repository",
  ),
  risk_factors: z.array(z.string()).optional().describe(
    "Runtime context that indicates increased asset risk",
  ),
  sources: z.array(z.string()).optional().describe(
    "List of source identifiers for the asset",
  ),
  tags: z.array(z.string()).optional().describe(
    "Tags associated with the asset",
  ),
  updated_at: z.string().optional().describe("Last update timestamp"),
  assets_id: z.string().optional().describe("Related assets ID"),
  organizations_id: z.string().optional().describe("Related organizations ID"),
  projects_id: z.string().optional().describe("Related projects ID"),
});

const GetAssetSchema = z.object({
  id: z.string(),
  type: z.enum(["repository", "image", "package"]).optional(),
  app_context: z.object({}).nullable().optional().describe(
    "asset metadata from App Context integrations",
  ),
  archived: z.boolean().optional().describe(
    "Indicates if the asset is archived",
  ),
  base_image: z.string().nullable().optional().describe(
    "Base image of the container image",
  ),
  browse_url: z.string().nullable().optional().describe(
    "URL to browse the asset",
  ),
  class: z.object({
    locked: z.boolean().optional(),
    name: z.string().optional(),
    rank: z.number().int().optional(),
  }).optional(),
  coverage_controls: z.array(z.unknown()).optional(),
  created_at: z.string().optional().describe("Creation timestamp"),
  default_branch_name: z.string().nullable().optional().describe(
    "Default branch name of the repository",
  ),
  developers: z.array(z.unknown()).optional().describe(
    "List of developers associated with the asset",
  ),
  file_path: z.string().nullable().optional().describe(
    "File path of the asset",
  ),
  image_digests: z.array(z.string()).nullable().optional().describe(
    "List of digests for the container image",
  ),
  image_id: z.string().nullable().optional().describe(
    "ID of the container image",
  ),
  image_registries: z.array(z.string()).nullable().optional().describe(
    "List of registries containing the container image",
  ),
  image_repositories: z.array(z.string()).nullable().optional().describe(
    "List of repositories containing the container image",
  ),
  image_tags: z.array(z.string()).nullable().optional().describe(
    "List of tags for the container image",
  ),
  languages: z.record(z.string(), z.number().int()).nullable().optional()
    .describe("Languages used in the asset with usage counts"),
  name: z.string().nullable().optional().describe(
    "Name of the asset of the file path",
  ),
  repository_freshness: z.string().nullable().optional().describe(
    "Indicating the activity level of the repository",
  ),
  repository_url: z.string().nullable().optional().describe(
    "URL to the asset's repository",
  ),
  risk_factors: z.array(z.string()).optional().describe(
    "Runtime context that indicates increased asset risk",
  ),
  sources: z.array(z.string()).optional().describe(
    "List of source identifiers for the asset",
  ),
  tags: z.array(z.string()).optional().describe(
    "Tags associated with the asset",
  ),
  updated_at: z.string().optional().describe("Last update timestamp"),
  assets_id: z.string().optional().describe("Related assets ID"),
  organizations_id: z.string().optional().describe("Related organizations ID"),
  projects_id: z.string().optional().describe("Related projects ID"),
});

const RelatedAssetsItemSchema = z.object({
  id: z.string(),
  type: z.enum(["repository", "image", "package"]).optional(),
  app_context: z.object({}).nullable().optional().describe(
    "asset metadata from App Context integrations",
  ),
  archived: z.boolean().optional().describe(
    "Indicates if the asset is archived",
  ),
  base_image: z.string().nullable().optional().describe(
    "Base image of the container image",
  ),
  browse_url: z.string().nullable().optional().describe(
    "URL to browse the asset",
  ),
  class: z.object({
    locked: z.boolean().optional(),
    name: z.string().optional(),
    rank: z.number().int().optional(),
  }).optional(),
  coverage_controls: z.array(z.unknown()).optional(),
  created_at: z.string().optional().describe("Creation timestamp"),
  default_branch_name: z.string().nullable().optional().describe(
    "Default branch name of the repository",
  ),
  developers: z.array(z.unknown()).optional().describe(
    "List of developers associated with the asset",
  ),
  file_path: z.string().nullable().optional().describe(
    "File path of the asset",
  ),
  image_digests: z.array(z.string()).nullable().optional().describe(
    "List of digests for the container image",
  ),
  image_id: z.string().nullable().optional().describe(
    "ID of the container image",
  ),
  image_registries: z.array(z.string()).nullable().optional().describe(
    "List of registries containing the container image",
  ),
  image_repositories: z.array(z.string()).nullable().optional().describe(
    "List of repositories containing the container image",
  ),
  image_tags: z.array(z.string()).nullable().optional().describe(
    "List of tags for the container image",
  ),
  languages: z.record(z.string(), z.number().int()).nullable().optional()
    .describe("Languages used in the asset with usage counts"),
  name: z.string().nullable().optional().describe(
    "Name of the asset of the file path",
  ),
  repository_freshness: z.string().nullable().optional().describe(
    "Indicating the activity level of the repository",
  ),
  repository_url: z.string().nullable().optional().describe(
    "URL to the asset's repository",
  ),
  risk_factors: z.array(z.string()).optional().describe(
    "Runtime context that indicates increased asset risk",
  ),
  sources: z.array(z.string()).optional().describe(
    "List of source identifiers for the asset",
  ),
  tags: z.array(z.string()).optional().describe(
    "Tags associated with the asset",
  ),
  updated_at: z.string().optional().describe("Last update timestamp"),
  assets_id: z.string().optional().describe("Related assets ID"),
  organizations_id: z.string().optional().describe("Related organizations ID"),
  projects_id: z.string().optional().describe("Related projects ID"),
});

const ListRelatedAssetsSchema = z.object({
  items: z.array(RelatedAssetsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const AssetProjectsItemSchema = z.object({
  id: z.string(),
  type: z.enum(["project"]).optional(),
  issues_counts: z.object({
    critical: z.number().optional(),
    high: z.number().optional(),
    low: z.number().optional(),
    medium: z.number().optional(),
  }).optional(),
  last_scan: z.string().optional(),
  name: z.string().optional(),
  organization_id: z.string().optional(),
  organization_name: z.string().optional(),
  project_type: z.string().optional(),
  target_file: z.string().optional(),
  target_id: z.string().optional(),
  target_reference: z.string().optional(),
  test_surface: z.string().optional(),
  url: z.string().optional(),
});

const ListAssetProjectsSchema = z.object({
  items: z.array(AssetProjectsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Snyk Assets — asset discovery and classification across the group */
export const model = {
  type: "@webframp/snyk/assets",
  version: "2026.07.19.1",
  globalArguments: GlobalArgsSchema,

  upgrades: [],

  resources: {
    "list_assets": {
      description: "List Assets with filters (Early Access)",
      schema: ListAssetsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "asset": {
      description: "Get an Asset by its ID (Early Access)",
      schema: GetAssetSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "related_assets": {
      description: "List related assets with pagination (Early Access)",
      schema: ListRelatedAssetsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "asset_projects": {
      description: "List asset projects with pagination (Early Access)",
      schema: ListAssetProjectsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
  },

  methods: {
    list_assets: {
      description: "List Assets with filters (Early Access)",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "POST",
          `/groups/${groupId}/assets/search`,
          version,
          body,
        );

        const handle = await context.writeResource(
          "list_assets",
          "latest",
          result ?? {},
        );
        context.logger.info("Executed list_assets", {});
        return { dataHandles: [handle] };
      },
    },
    get_asset: {
      description: "Get an Asset by its ID (Early Access)",
      arguments: z.object({
        asset_id: z.string().describe("Unique identifier for the Asset"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        const result = await snykApi(
          apiToken,
          "GET",
          `/groups/${groupId}/assets/${args.asset_id}`,
          version,
        );

        const handle = await context.writeResource(
          "asset",
          String(args.asset_id),
          result,
        );
        context.logger.info("Fetched asset", {});
        return { dataHandles: [handle] };
      },
    },
    list_related_assets: {
      description: "List related assets with pagination (Early Access)",
      arguments: z.object({
        asset_id: z.string().describe("Unique identifier for the Asset"),
        type: z.enum(["repository", "package", "image"]).optional().describe(
          "Filter by asset type",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["asset_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/assets/${args.asset_id}/relationships/assets`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("related_assets", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} related_assets", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    list_asset_projects: {
      description: "List asset projects with pagination (Early Access)",
      arguments: z.object({
        asset_id: z.string().describe("Unique identifier for the Asset"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["asset_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/assets/${args.asset_id}/relationships/projects`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("asset_projects", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} asset_projects", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
  },
};
