/**
 * Datadog Teams — team management, memberships, and permissions
 *
 * Auto-generated by scripts/datadog-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: AGPL-3.0-or-later WITH Swamp-Extension-Exception

import { z } from "npm:zod@4.4.3";
import { ddApi, ddApiPaginated } from "./_lib/api.ts";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiKey: z.string().meta({ sensitive: true }).describe(
    "Datadog API key (DD-API-KEY)",
  ),
  appKey: z.string().meta({ sensitive: true }).describe(
    "Datadog application key (DD-APPLICATION-KEY)",
  ),
  site: z.enum(["us1", "us3", "us5", "eu1", "ap1", "us1-fed"]).default("us1")
    .describe("Datadog site"),
});

const TeamsItemSchema = z.object({
  id: z.string().describe("The team's identifier"),
  type: z.enum(["team"]).optional().describe("Team type"),
  avatar: z.string().nullable().optional().describe(
    "Unicode representation of the avatar for the team, limited to a single grapheme",
  ),
  banner: z.number().int().nullable().optional().describe(
    "Banner selection for the team",
  ),
  created_at: z.string().optional().describe("Creation date of the team"),
  description: z.string().nullable().optional().describe(
    "Free-form markdown description/content for the team's homepage",
  ),
  handle: z.string().max(195).describe("The team's identifier"),
  hidden_modules: z.array(z.string()).nullable().optional().describe(
    "Collection of hidden modules for the team",
  ),
  is_managed: z.boolean().optional().describe(
    "Whether the team is managed from an external source",
  ),
  link_count: z.number().int().max(2147483647).optional().describe(
    "The number of links belonging to the team",
  ),
  modified_at: z.string().optional().describe("Modification date of the team"),
  name: z.string().max(200).describe("The name of the team"),
  summary: z.string().max(120).nullable().optional().describe(
    "A brief summary of the team, derived from the `description`",
  ),
  user_count: z.number().int().max(2147483647).optional().describe(
    "The number of users belonging to the team",
  ),
  visible_modules: z.array(z.string()).nullable().optional().describe(
    "Collection of visible modules for the team",
  ),
  team_links_id: z.string().optional().describe("Related team_links ID"),
  user_team_permissions_id: z.string().optional().describe(
    "Related user_team_permissions ID",
  ),
});

const ListTeamsSchema = z.object({
  items: z.array(TeamsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateTeamSchema = z.object({
  id: z.string().describe("The team's identifier"),
  type: z.enum(["team"]).optional().describe("Team type"),
  avatar: z.string().nullable().optional().describe(
    "Unicode representation of the avatar for the team, limited to a single grapheme",
  ),
  banner: z.number().int().nullable().optional().describe(
    "Banner selection for the team",
  ),
  created_at: z.string().optional().describe("Creation date of the team"),
  description: z.string().nullable().optional().describe(
    "Free-form markdown description/content for the team's homepage",
  ),
  handle: z.string().max(195).describe("The team's identifier"),
  hidden_modules: z.array(z.string()).nullable().optional().describe(
    "Collection of hidden modules for the team",
  ),
  is_managed: z.boolean().optional().describe(
    "Whether the team is managed from an external source",
  ),
  link_count: z.number().int().max(2147483647).optional().describe(
    "The number of links belonging to the team",
  ),
  modified_at: z.string().optional().describe("Modification date of the team"),
  name: z.string().max(200).describe("The name of the team"),
  summary: z.string().max(120).nullable().optional().describe(
    "A brief summary of the team, derived from the `description`",
  ),
  user_count: z.number().int().max(2147483647).optional().describe(
    "The number of users belonging to the team",
  ),
  visible_modules: z.array(z.string()).nullable().optional().describe(
    "Collection of visible modules for the team",
  ),
  team_links_id: z.string().optional().describe("Related team_links ID"),
  user_team_permissions_id: z.string().optional().describe(
    "Related user_team_permissions ID",
  ),
});

const TeamHierarchyLinksItemSchema = z.object({
  id: z.string().describe("The team hierarchy link's identifier"),
  type: z.enum(["team_hierarchy_links"]).optional().describe(
    "Team hierarchy link type",
  ),
  created_at: z.string().describe(
    "Timestamp when the team hierarchy link was created",
  ),
  provisioned_by: z.string().describe(
    "The provisioner of the team hierarchy link",
  ),
  parent_team_id: z.string().optional().describe("Related parent_team ID"),
  sub_team_id: z.string().optional().describe("Related sub_team ID"),
});

const ListTeamHierarchyLinksSchema = z.object({
  items: z.array(TeamHierarchyLinksItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const AddTeamHierarchyLinkSchema = z.object({
  id: z.string().describe("The team hierarchy link's identifier"),
  type: z.enum(["team_hierarchy_links"]).optional().describe(
    "Team hierarchy link type",
  ),
  created_at: z.string().describe(
    "Timestamp when the team hierarchy link was created",
  ),
  provisioned_by: z.string().describe(
    "The provisioner of the team hierarchy link",
  ),
  parent_team_id: z.string().optional().describe("Related parent_team ID"),
  sub_team_id: z.string().optional().describe("Related sub_team ID"),
});

const GetTeamHierarchyLinkSchema = z.object({
  id: z.string().describe("The team hierarchy link's identifier"),
  type: z.enum(["team_hierarchy_links"]).optional().describe(
    "Team hierarchy link type",
  ),
  created_at: z.string().describe(
    "Timestamp when the team hierarchy link was created",
  ),
  provisioned_by: z.string().describe(
    "The provisioner of the team hierarchy link",
  ),
  parent_team_id: z.string().optional().describe("Related parent_team ID"),
  sub_team_id: z.string().optional().describe("Related sub_team ID"),
});

const TeamConnectionsItemSchema = z.object({
  id: z.string().describe("The unique identifier of the team connection."),
  type: z.enum(["team_connection"]).optional().describe(
    "Team connection resource type.",
  ),
  managed_by: z.string().optional().describe(
    "The entity that manages this team connection.",
  ),
  source: z.string().optional().describe("The name of the external source."),
  connected_team_id: z.string().optional().describe(
    "Related connected_team ID",
  ),
  team_id: z.string().optional().describe("Related team ID"),
});

const ListTeamConnectionsSchema = z.object({
  items: z.array(TeamConnectionsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const TeamSyncItemSchema = z.object({
  id: z.string().describe("The sync's identifier"),
  type: z.enum(["link", "provision"]).describe(
    'The type of synchronization operation. "link" connects teams by matching names. "provision" creat...',
  ),
  frequency: z.enum(["once", "continuously", "paused"]).optional().describe(
    "How often the sync process should be run. Defaults to `once` when not provided.",
  ),
  selection_state: z.array(z.unknown()).optional().describe(
    "Specifies which teams or organizations to sync. When provided, synchronization is limited to the ...",
  ),
  source: z.enum(["github"]).describe(
    'The external source platform for team synchronization. Only "github" is supported.',
  ),
  sync_membership: z.boolean().optional().describe(
    "Whether to sync members from the external team to the Datadog team. Defaults to `false` when not ...",
  ),
});

const GetTeamSyncSchema = z.object({
  items: z.array(TeamSyncItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const TeamLinksItemSchema = z.object({
  id: z.string().describe("The team link's identifier"),
  type: z.enum(["team_links"]).optional().describe("Team link type"),
  label: z.string().max(256).describe("The link's label"),
  position: z.number().int().max(2147483647).optional().describe(
    "The link's position, used to sort links for the team",
  ),
  team_id: z.string().optional().describe(
    "ID of the team the link is associated with",
  ),
  url: z.string().describe("The URL for the link"),
});

const GetTeamLinksSchema = z.object({
  items: z.array(TeamLinksItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateTeamLinkSchema = z.object({
  id: z.string().describe("The team link's identifier"),
  type: z.enum(["team_links"]).optional().describe("Team link type"),
  label: z.string().max(256).describe("The link's label"),
  position: z.number().int().max(2147483647).optional().describe(
    "The link's position, used to sort links for the team",
  ),
  team_id: z.string().optional().describe(
    "ID of the team the link is associated with",
  ),
  url: z.string().describe("The URL for the link"),
});

const TeamMembershipsItemSchema = z.object({
  id: z.string().describe("The ID of a user's relationship with a team"),
  type: z.enum(["team_memberships"]).optional().describe(
    "Team membership type",
  ),
  provisioned_by: z.string().nullable().optional().describe(
    "The mechanism responsible for provisioning the team relationship. Possible values: null for added...",
  ),
  provisioned_by_id: z.string().nullable().optional().describe(
    "UUID of the User or Service Account who provisioned this team membership, or null if provisioned ...",
  ),
  role: z.enum(["admin"]).nullable().optional().describe(
    "The user's role within the team",
  ),
  team_id: z.string().optional().describe("Related team ID"),
  user_id: z.string().optional().describe("Related user ID"),
});

const GetTeamMembershipsSchema = z.object({
  items: z.array(TeamMembershipsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateTeamMembershipSchema = z.object({
  id: z.string().describe("The ID of a user's relationship with a team"),
  type: z.enum(["team_memberships"]).optional().describe(
    "Team membership type",
  ),
  provisioned_by: z.string().nullable().optional().describe(
    "The mechanism responsible for provisioning the team relationship. Possible values: null for added...",
  ),
  provisioned_by_id: z.string().nullable().optional().describe(
    "UUID of the User or Service Account who provisioned this team membership, or null if provisioned ...",
  ),
  role: z.enum(["admin"]).nullable().optional().describe(
    "The user's role within the team",
  ),
  team_id: z.string().optional().describe("Related team ID"),
  user_id: z.string().optional().describe("Related user ID"),
});

const TeamNotificationRulesItemSchema = z.object({
  id: z.string().describe("The identifier of the team notification rule"),
  type: z.enum(["team_notification_rules"]).optional().describe(
    "Team notification rule type",
  ),
  email: z.object({
    enabled: z.boolean().optional(),
  }).optional().describe("Email notification settings for the team"),
  ms_teams: z.object({
    connector_name: z.string().optional(),
  }).optional().describe("MS Teams notification settings for the team"),
  pagerduty: z.object({
    service_name: z.string().optional(),
  }).optional().describe("PagerDuty notification settings for the team"),
  slack: z.object({
    channel: z.string().optional(),
    workspace: z.string().optional(),
  }).optional().describe("Slack notification settings for the team"),
});

const GetTeamNotificationRulesSchema = z.object({
  items: z.array(TeamNotificationRulesItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateTeamNotificationRuleSchema = z.object({
  id: z.string().describe("The identifier of the team notification rule"),
  type: z.enum(["team_notification_rules"]).optional().describe(
    "Team notification rule type",
  ),
  email: z.object({
    enabled: z.boolean().optional(),
  }).optional().describe("Email notification settings for the team"),
  ms_teams: z.object({
    connector_name: z.string().optional(),
  }).optional().describe("MS Teams notification settings for the team"),
  pagerduty: z.object({
    service_name: z.string().optional(),
  }).optional().describe("PagerDuty notification settings for the team"),
  slack: z.object({
    channel: z.string().optional(),
    workspace: z.string().optional(),
  }).optional().describe("Slack notification settings for the team"),
});

const TeamPermissionSettingsItemSchema = z.object({
  id: z.string().describe("The team permission setting's identifier"),
  type: z.enum(["team_permission_settings"]).optional().describe(
    "Team permission setting type",
  ),
  action: z.enum(["manage_membership", "edit"]).optional().describe(
    "The identifier for the action",
  ),
  editable: z.boolean().optional().describe(
    "Whether or not the permission setting is editable by the current user",
  ),
  options: z.array(z.unknown()).optional().describe(
    "Possible values for action",
  ),
  title: z.string().optional().describe("The team permission name"),
  value: z.enum([
    "admins",
    "members",
    "organization",
    "user_access_manage",
    "teams_manage",
  ]).optional().describe(
    "What type of user is allowed to perform the specified action",
  ),
});

const GetTeamPermissionSettingsSchema = z.object({
  items: z.array(TeamPermissionSettingsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const UpdateTeamPermissionSettingSchema = z.object({
  id: z.string().describe("The team permission setting's identifier"),
  type: z.enum(["team_permission_settings"]).optional().describe(
    "Team permission setting type",
  ),
  action: z.enum(["manage_membership", "edit"]).optional().describe(
    "The identifier for the action",
  ),
  editable: z.boolean().optional().describe(
    "Whether or not the permission setting is editable by the current user",
  ),
  options: z.array(z.unknown()).optional().describe(
    "Possible values for action",
  ),
  title: z.string().optional().describe("The team permission name"),
  value: z.enum([
    "admins",
    "members",
    "organization",
    "user_access_manage",
    "teams_manage",
  ]).optional().describe(
    "What type of user is allowed to perform the specified action",
  ),
});

const UserMembershipsItemSchema = z.object({
  id: z.string().describe("The ID of a user's relationship with a team"),
  type: z.enum(["team_memberships"]).optional().describe(
    "Team membership type",
  ),
  provisioned_by: z.string().nullable().optional().describe(
    "The mechanism responsible for provisioning the team relationship. Possible values: null for added...",
  ),
  provisioned_by_id: z.string().nullable().optional().describe(
    "UUID of the User or Service Account who provisioned this team membership, or null if provisioned ...",
  ),
  role: z.enum(["admin"]).nullable().optional().describe(
    "The user's role within the team",
  ),
  team_id: z.string().optional().describe("Related team ID"),
  user_id: z.string().optional().describe("Related user ID"),
});

const GetUserMembershipsSchema = z.object({
  items: z.array(UserMembershipsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Datadog Teams — team management, memberships, and permissions */
export const model = {
  type: "@webframp/datadog/teams",
  version: "2026.07.20.2",
  globalArguments: GlobalArgsSchema,

  upgrades: [],

  resources: {
    "teams": {
      description: "Get all teams",
      schema: ListTeamsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "team": {
      description: "Create a team",
      schema: CreateTeamSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_hierarchy_links": {
      description: "Get team hierarchy links",
      schema: ListTeamHierarchyLinksSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "add_team_hierarchy_link": {
      description: "Create a team hierarchy link",
      schema: AddTeamHierarchyLinkSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_hierarchy_link": {
      description: "Get a team hierarchy link",
      schema: GetTeamHierarchyLinkSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_connections": {
      description: "List team connections",
      schema: ListTeamConnectionsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "team_sync": {
      description: "Get team sync configurations",
      schema: GetTeamSyncSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "sync_teams": {
      description: "Link Teams with GitHub Teams",
      schema: z.object({}),
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_links": {
      description: "Get links for a team",
      schema: GetTeamLinksSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "team_link": {
      description: "Create a team link",
      schema: CreateTeamLinkSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_memberships": {
      description: "Get team memberships",
      schema: GetTeamMembershipsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "team_membership": {
      description: "Add a user to a team",
      schema: CreateTeamMembershipSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_notification_rules": {
      description: "Get team notification rules",
      schema: GetTeamNotificationRulesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "team_notification_rule": {
      description: "Create team notification rule",
      schema: CreateTeamNotificationRuleSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_permission_settings": {
      description: "Get permission settings for a team",
      schema: GetTeamPermissionSettingsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "team_permission_setting": {
      description: "Update permission setting for team",
      schema: UpdateTeamPermissionSettingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "user_memberships": {
      description: "Get user memberships",
      schema: GetUserMembershipsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
  },

  methods: {
    list_teams: {
      description: "Get all teams",
      arguments: z.object({
        sort: z.string().optional().describe(
          "Specifies the order of the returned teams",
        ),
        include: z.string().optional().describe(
          "Included related resources optionally requested. Allowed enum values: `team_l...",
        ),
        filter_keyword: z.string().optional().describe(
          "Search query. Can be team name, team handle, or email of team member",
        ),
        filter_me: z.boolean().optional().describe(
          "When true, only returns teams the current user belongs to",
        ),
        fields_team: z.string().optional().describe(
          "List of fields that need to be fetched.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team`,
          {
            "style": "page_number",
            "limitParam": "page[size]",
            "limitDefault": 50,
            "pageParam": "page[number]",
          },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("teams", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} teams", { count: results.length });
        return { dataHandles: [handle] };
      },
    },
    create_team: {
      description: "Create a team",
      arguments: z.object({
        avatar: z.string().nullable().optional().describe(
          "Unicode representation of the avatar for the team, limited to a single grapheme",
        ),
        banner: z.number().int().nullable().optional().describe(
          "Banner selection for the team",
        ),
        description: z.string().optional().describe(
          "Free-form markdown description/content for the team's homepage",
        ),
        handle: z.string().max(195).describe("The team's identifier"),
        hidden_modules: z.array(z.string()).optional().describe(
          "Collection of hidden modules for the team",
        ),
        name: z.string().max(200).describe("The name of the team"),
        visible_modules: z.array(z.string()).optional().describe(
          "Collection of visible modules for the team",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("team", id, result);
        context.logger.info("Created team {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    list_team_hierarchy_links: {
      description: "Get team hierarchy links",
      arguments: z.object({
        filter_parent_team: z.string().optional().describe(
          "Filter by parent team ID",
        ),
        filter_sub_team: z.string().optional().describe(
          "Filter by sub team ID",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team-hierarchy-links`,
          {
            "style": "page_number",
            "limitParam": "page[size]",
            "limitDefault": 50,
            "pageParam": "page[number]",
          },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "team_hierarchy_links",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} team_hierarchy_links", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    add_team_hierarchy_link: {
      description: "Create a team hierarchy link",
      arguments: z.object({
        relationships: z.unknown(),
        type: z.unknown(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "resource", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team-hierarchy-links`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "add_team_hierarchy_link",
          id,
          result,
        );
        context.logger.info("Created add_team_hierarchy_link {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_team_hierarchy_link: {
      description: "Get a team hierarchy link",
      arguments: z.object({
        link_id: z.string().describe("The team hierarchy link's identifier"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/team-hierarchy-links/${
            encodeURIComponent(String(args.link_id))
          }`,
        );

        const handle = await context.writeResource(
          "team_hierarchy_link",
          String(args.link_id),
          result,
        );
        context.logger.info("Fetched team_hierarchy_link", {});
        return { dataHandles: [handle] };
      },
    },
    remove_team_hierarchy_link: {
      description: "Remove a team hierarchy link",
      arguments: z.object({
        link_id: z.string().describe("The team hierarchy link's identifier"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/team-hierarchy-links/${
            encodeURIComponent(String(args.link_id))
          }`,
        );

        context.logger.info("Deleted resource {id}", { id: args.link_id });
        return { dataHandles: [] };
      },
    },
    list_team_connections: {
      description: "List team connections",
      arguments: z.object({
        filter_sources: z.string().optional().describe(
          "Filter team connections by external source systems.",
        ),
        filter_team_ids: z.string().optional().describe(
          "Filter team connections by Datadog team IDs.",
        ),
        filter_connected_team_ids: z.string().optional().describe(
          "Filter team connections by connected team IDs from external systems.",
        ),
        filter_connection_ids: z.string().optional().describe(
          "Filter team connections by connection IDs.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team/connections`,
          {
            "style": "page_number",
            "limitParam": "page[size]",
            "limitDefault": 50,
            "pageParam": "page[number]",
          },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("team_connections", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} team_connections", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_team_connections: {
      description: "Create team connections",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team/connections`,
          body,
        );

        const id = (result as { id?: string }).id ?? "latest";
        const handle = await context.writeResource(
          "team_connections",
          id,
          result ?? {},
        );
        context.logger.info("Executed create_team_connections", {});
        return { dataHandles: [handle] };
      },
    },
    delete_team_connections: {
      description: "Delete team connections",
      arguments: z.object({}),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/team/connections`,
        );

        context.logger.info("Deleted resource {id}", { id: "unknown" });
        return { dataHandles: [] };
      },
    },
    get_team_sync: {
      description: "Get team sync configurations",
      arguments: z.object({
        filter_source: z.string().optional().describe(
          "Filter by the external source platform for team synchronization",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team/sync`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("team_sync", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} team_sync", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    sync_teams: {
      description: "Link Teams with GitHub Teams",
      arguments: z.object({
        frequency: z.unknown().optional(),
        selection_state: z.unknown().optional(),
        source: z.unknown(),
        sync_membership: z.unknown().optional(),
        type: z.unknown(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team_sync_bulk", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team/sync`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("sync_teams", id, result);
        context.logger.info("Created sync_teams {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_team: {
      description: "Get a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}`,
        );

        const handle = await context.writeResource(
          "team",
          String(args.team_id),
          result,
        );
        context.logger.info("Fetched team", {});
        return { dataHandles: [handle] };
      },
    },
    update_team: {
      description: "Update a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
        avatar: z.string().nullable().optional().describe(
          "Unicode representation of the avatar for the team, limited to a single grapheme",
        ),
        banner: z.number().int().nullable().optional().describe(
          "Banner selection for the team",
        ),
        description: z.string().optional().describe(
          "Free-form markdown description/content for the team's homepage",
        ),
        handle: z.string().max(195).describe("The team's identifier"),
        hidden_modules: z.array(z.string()).optional().describe(
          "Collection of hidden modules for the team",
        ),
        name: z.string().max(200).describe("The name of the team"),
        visible_modules: z.array(z.string()).optional().describe(
          "Collection of visible modules for the team",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PATCH",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}`,
          body,
        );

        const handle = await context.writeResource(
          "team",
          String(args.team_id),
          result,
        );
        context.logger.info("Updated team", {});
        return { dataHandles: [handle] };
      },
    },
    delete_team: {
      description: "Remove a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}`,
        );

        context.logger.info("Deleted resource {id}", { id: args.team_id });
        return { dataHandles: [] };
      },
    },
    get_team_links: {
      description: "Get links for a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}/links`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("team_links", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} team_links", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_team_link: {
      description: "Create a team link",
      arguments: z.object({
        team_id: z.string().describe("None"),
        label: z.string().max(256).describe("The link's label"),
        position: z.number().int().max(2147483647).optional().describe(
          "The link's position, used to sort links for the team",
        ),
        url: z.string().describe("The URL for the link"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team_links", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}/links`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("team_link", id, result);
        context.logger.info("Created team_link {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_team_link: {
      description: "Get a team link",
      arguments: z.object({
        team_id: z.string().describe("None"),
        link_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}/links/${
            encodeURIComponent(String(args.link_id))
          }`,
        );

        const handle = await context.writeResource(
          "team_link",
          String(args.link_id),
          result,
        );
        context.logger.info("Fetched team_link", {});
        return { dataHandles: [handle] };
      },
    },
    update_team_link: {
      description: "Update a team link",
      arguments: z.object({
        team_id: z.string().describe("None"),
        link_id: z.string().describe("None"),
        label: z.string().max(256).describe("The link's label"),
        position: z.number().int().max(2147483647).optional().describe(
          "The link's position, used to sort links for the team",
        ),
        url: z.string().describe("The URL for the link"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id", "link_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team_links", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PATCH",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}/links/${
            encodeURIComponent(String(args.link_id))
          }`,
          body,
        );

        const handle = await context.writeResource(
          "team_link",
          String(args.link_id),
          result,
        );
        context.logger.info("Updated team_link", {});
        return { dataHandles: [handle] };
      },
    },
    delete_team_link: {
      description: "Remove a team link",
      arguments: z.object({
        team_id: z.string().describe("None"),
        link_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/team/${encodeURIComponent(String(args.team_id))}/links/${
            encodeURIComponent(String(args.link_id))
          }`,
        );

        context.logger.info("Deleted resource {id}", { id: args.link_id });
        return { dataHandles: [] };
      },
    },
    get_team_memberships: {
      description: "Get team memberships",
      arguments: z.object({
        team_id: z.string().describe("None"),
        sort: z.string().optional().describe(
          "Specifies the order of returned team memberships",
        ),
        filter_keyword: z.string().optional().describe(
          "Search query, can be user email or name",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/memberships`,
          {
            "style": "page_number",
            "limitParam": "page[size]",
            "limitDefault": 50,
            "pageParam": "page[number]",
          },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("team_memberships", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} team_memberships", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_team_membership: {
      description: "Add a user to a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
        provisioned_by: z.string().nullable().optional().describe(
          "The mechanism responsible for provisioning the team relationship. Possible va...",
        ),
        provisioned_by_id: z.string().nullable().optional().describe(
          "UUID of the User or Service Account who provisioned this team membership, or ...",
        ),
        role: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team_memberships", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/memberships`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "team_membership",
          id,
          result,
        );
        context.logger.info("Created team_membership {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    update_team_membership: {
      description: "Update a user's membership attributes on a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
        user_id: z.string().describe("None"),
        provisioned_by: z.string().nullable().optional().describe(
          "The mechanism responsible for provisioning the team relationship. Possible va...",
        ),
        provisioned_by_id: z.string().nullable().optional().describe(
          "UUID of the User or Service Account who provisioned this team membership, or ...",
        ),
        role: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id", "user_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "team_memberships", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PATCH",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/memberships/${encodeURIComponent(String(args.user_id))}`,
          body,
        );

        const handle = await context.writeResource(
          "team_membership",
          String(args.user_id),
          result,
        );
        context.logger.info("Updated team_membership", {});
        return { dataHandles: [handle] };
      },
    },
    delete_team_membership: {
      description: "Remove a user from a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
        user_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/memberships/${encodeURIComponent(String(args.user_id))}`,
        );

        context.logger.info("Deleted resource {id}", { id: args.user_id });
        return { dataHandles: [] };
      },
    },
    get_team_notification_rules: {
      description: "Get team notification rules",
      arguments: z.object({
        team_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/notification-rules`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "team_notification_rules",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} team_notification_rules", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_team_notification_rule: {
      description: "Create team notification rule",
      arguments: z.object({
        team_id: z.string().describe("None"),
        email: z.unknown().optional(),
        ms_teams: z.unknown().optional(),
        pagerduty: z.unknown().optional(),
        slack: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "team_notification_rules", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/notification-rules`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "team_notification_rule",
          id,
          result,
        );
        context.logger.info("Created team_notification_rule {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_team_notification_rule: {
      description: "Get team notification rule",
      arguments: z.object({
        team_id: z.string().describe("None"),
        rule_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/notification-rules/${encodeURIComponent(String(args.rule_id))}`,
        );

        const handle = await context.writeResource(
          "team_notification_rule",
          String(args.rule_id),
          result,
        );
        context.logger.info("Fetched team_notification_rule", {});
        return { dataHandles: [handle] };
      },
    },
    update_team_notification_rule: {
      description: "Update team notification rule",
      arguments: z.object({
        team_id: z.string().describe("None"),
        rule_id: z.string().describe("None"),
        email: z.unknown().optional(),
        ms_teams: z.unknown().optional(),
        pagerduty: z.unknown().optional(),
        slack: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id", "rule_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "team_notification_rules", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PUT",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/notification-rules/${encodeURIComponent(String(args.rule_id))}`,
          body,
        );

        const handle = await context.writeResource(
          "team_notification_rule",
          String(args.rule_id),
          result,
        );
        context.logger.info("Updated team_notification_rule", {});
        return { dataHandles: [handle] };
      },
    },
    delete_team_notification_rule: {
      description: "Delete team notification rule",
      arguments: z.object({
        team_id: z.string().describe("None"),
        rule_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/notification-rules/${encodeURIComponent(String(args.rule_id))}`,
        );

        context.logger.info("Deleted resource {id}", { id: args.rule_id });
        return { dataHandles: [] };
      },
    },
    get_team_permission_settings: {
      description: "Get permission settings for a team",
      arguments: z.object({
        team_id: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/permission-settings`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "team_permission_settings",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} team_permission_settings", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    update_team_permission_setting: {
      description: "Update permission setting for team",
      arguments: z.object({
        team_id: z.string().describe("None"),
        action: z.string().describe("None"),
        value: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id", "action"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "team_permission_settings", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PUT",
          `/api/v2/team/${
            encodeURIComponent(String(args.team_id))
          }/permission-settings/${encodeURIComponent(String(args.action))}`,
          body,
        );

        const handle = await context.writeResource(
          "team_permission_setting",
          String(args.action),
          result,
        );
        context.logger.info("Updated team_permission_setting", {});
        return { dataHandles: [handle] };
      },
    },
    get_user_memberships: {
      description: "Get user memberships",
      arguments: z.object({
        user_uuid: z.string().describe("None"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["user_uuid"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/users/${
            encodeURIComponent(String(args.user_uuid))
          }/memberships`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("user_memberships", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} user_memberships", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
  },
};
