/**
 * Griptape Cloud Rulesets — behavioral rulesets and their rules
 *
 * Auto-generated by scripts/griptape-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: Apache-2.0

import { z } from "npm:zod@4.4.3";
import {
  griptapeApi,
  griptapeApiPaginated,
  sanitizeInstanceName,
} from "./_lib/api.ts";

const EXTENSION_NAME = "@webframp/griptape/rulesets";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiKey: z.string().meta({ sensitive: true }).describe(
    "Griptape Cloud API key; overrides the GT_CLOUD_API_KEY environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  baseUrl: z.string().describe(
    "Griptape Cloud API base URL; overrides the GT_CLOUD_BASE_URL environment variable and the built-in default.",
  ).optional(),
});

const RulesItemSchema = z.looseObject({
  created_at: z.string(),
  created_by: z.string(),
  metadata: z.unknown(),
  name: z.string(),
  organization_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  rule: z.string(),
  rule_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  updated_at: z.string(),
});

const ListRulesSchema = z.object({
  items: z.array(RulesItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const CreateRuleSchema = z.looseObject({
  created_at: z.string(),
  created_by: z.string(),
  metadata: z.unknown(),
  name: z.string(),
  organization_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  rule: z.string(),
  rule_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  updated_at: z.string(),
});

const RulesetsItemSchema = z.looseObject({
  alias: z.string(),
  created_at: z.string(),
  created_by: z.string(),
  description: z.string(),
  metadata: z.unknown(),
  name: z.string(),
  organization_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  rule_ids: z.array(
    z.string().regex(
      new RegExp(
        "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      ),
    ),
  ),
  ruleset_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  updated_at: z.string(),
});

const ListRulesetsSchema = z.object({
  items: z.array(RulesetsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const CreateRulesetSchema = z.looseObject({
  alias: z.string(),
  created_at: z.string(),
  created_by: z.string(),
  description: z.string(),
  metadata: z.unknown(),
  name: z.string(),
  organization_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  rule_ids: z.array(
    z.string().regex(
      new RegExp(
        "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
      ),
    ),
  ),
  ruleset_id: z.string().regex(
    new RegExp(
      "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    ),
  ),
  updated_at: z.string(),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Griptape Cloud Rulesets — behavioral rulesets and their rules */
export const model = {
  type: "@webframp/griptape/rulesets",
  version: "2026.08.29.1",
  globalArguments: GlobalArgsSchema,

  upgrades: [],

  resources: {
    "rules": {
      description: "list operation",
      schema: ListRulesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "rule": {
      description: "create operation",
      schema: CreateRuleSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "rulesets": {
      description: "list operation",
      schema: ListRulesetsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "ruleset": {
      description: "create operation",
      schema: CreateRulesetSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
  },

  methods: {
    list_rules: {
      description: "list operation",
      arguments: z.object({
        page: z.number().optional(),
        page_size: z.number().optional(),
        ruleset_id: z.string().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const startMs = Date.now();
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "page_size"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await griptapeApiPaginated<
          Record<string, unknown>
        >(
          apiKey,
          `/api/rules`,
          "rules",
          params,
          baseUrl,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("rules", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} rules", { count: results.length });
        return { dataHandles: [handle] };
      },
    },
    create_rule: {
      description: "create operation",
      arguments: z.object({
        metadata: z.unknown().optional(),
        name: z.string().min(1).max(200),
        rule: z.string().min(1).max(2000),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const body = args;

        const result = await griptapeApi<Record<string, unknown>>(
          apiKey,
          "POST",
          `/api/rules`,
          body,
          baseUrl,
        );

        // A 204 No Content (or empty body) yields undefined; nothing to persist.
        if (result === undefined || result === null) {
          context.logger.info("Created rule (no content)", {});
          return { dataHandles: [] };
        }

        const record = result as Record<string, unknown>;
        const pathParamValues = new Set<string>([]);
        const idCandidates = ["rule_id", "id"];
        let rawId = idCandidates.map((k) => record[k]).find((v) =>
          v !== undefined && v !== null && v !== ""
        );
        if (rawId === undefined) {
          // No named id candidate matched. Scan for a single id-shaped key that is
          // not organization_id and whose value is not a path param (the parent
          // addressing context, e.g. bucket_id on an asset — would collide).
          for (const [k, v] of Object.entries(record)) {
            if (
              /(^|_)id$/.test(k) && k !== "organization_id" &&
              typeof v === "string" && v !== "" && !pathParamValues.has(v)
            ) {
              rawId = v;
              break;
            }
          }
        }
        if (
          rawId === undefined && typeof record.name === "string" &&
          record.name !== ""
        ) {
          rawId = record.name;
        }
        const fallbackId =
          [].filter((s: string) => s && s !== "undefined").join("_") ||
          "created";
        const id = sanitizeInstanceName(String(rawId ?? fallbackId));
        const handle = await context.writeResource("rule", id, result);
        context.logger.info("Created rule {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_rule: {
      description: "get operation",
      arguments: z.object({
        rule_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const result = await griptapeApi<Record<string, unknown>>(
          apiKey,
          "GET",
          `/api/rules/${encodeURIComponent(String(args.rule_id))}`,
          undefined,
          baseUrl,
        );

        if (result === undefined || result === null) {
          context.logger.info("rule not found (no content)", {});
          return { dataHandles: [] };
        }

        const handle = await context.writeResource(
          "rule",
          sanitizeInstanceName(String(args.rule_id)),
          result,
        );
        context.logger.info("Fetched rule", {});
        return { dataHandles: [handle] };
      },
    },
    update_rule: {
      description: "update operation",
      arguments: z.object({
        rule_id: z.string(),
        metadata: z.unknown().optional(),
        name: z.string().min(1).max(200).optional(),
        rule: z.string().min(1).max(2000).optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["rule_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await griptapeApi<Record<string, unknown>>(
          apiKey,
          "PATCH",
          `/api/rules/${encodeURIComponent(String(args.rule_id))}`,
          body,
          baseUrl,
        );

        // A 204 No Content (or empty body) yields undefined; nothing to persist.
        if (result === undefined || result === null) {
          context.logger.info("Updated rule (no content)", {});
          return { dataHandles: [] };
        }

        const handle = await context.writeResource(
          "rule",
          sanitizeInstanceName(String(args.rule_id)),
          result,
        );
        context.logger.info("Updated rule", {});
        return { dataHandles: [handle] };
      },
    },
    delete_rule: {
      description: "delete operation",
      arguments: z.object({
        rule_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        await griptapeApi<Record<string, unknown>>(
          apiKey,
          "DELETE",
          `/api/rules/${encodeURIComponent(String(args.rule_id))}`,
          undefined,
          baseUrl,
        );

        context.logger.info("Deleted resource {id}", { id: args.rule_id });
        return { dataHandles: [] };
      },
    },
    list_rulesets: {
      description: "list operation",
      arguments: z.object({
        page: z.number().optional(),
        page_size: z.number().optional(),
        alias: z.string().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const startMs = Date.now();
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "page_size"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await griptapeApiPaginated<
          Record<string, unknown>
        >(
          apiKey,
          `/api/rulesets`,
          "rulesets",
          params,
          baseUrl,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("rulesets", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} rulesets", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_ruleset: {
      description: "create operation",
      arguments: z.object({
        alias: z.string().min(1).max(200).optional(),
        description: z.string().min(1).max(200).optional(),
        metadata: z.unknown().optional(),
        name: z.string().min(1).max(200),
        rule_ids: z.array(
          z.string().regex(
            new RegExp(
              "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
            ),
          ),
        ).optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const body = args;

        const result = await griptapeApi<Record<string, unknown>>(
          apiKey,
          "POST",
          `/api/rulesets`,
          body,
          baseUrl,
        );

        // A 204 No Content (or empty body) yields undefined; nothing to persist.
        if (result === undefined || result === null) {
          context.logger.info("Created ruleset (no content)", {});
          return { dataHandles: [] };
        }

        const record = result as Record<string, unknown>;
        const pathParamValues = new Set<string>([]);
        const idCandidates = ["ruleset_id", "id"];
        let rawId = idCandidates.map((k) => record[k]).find((v) =>
          v !== undefined && v !== null && v !== ""
        );
        if (rawId === undefined) {
          // No named id candidate matched. Scan for a single id-shaped key that is
          // not organization_id and whose value is not a path param (the parent
          // addressing context, e.g. bucket_id on an asset — would collide).
          for (const [k, v] of Object.entries(record)) {
            if (
              /(^|_)id$/.test(k) && k !== "organization_id" &&
              typeof v === "string" && v !== "" && !pathParamValues.has(v)
            ) {
              rawId = v;
              break;
            }
          }
        }
        if (
          rawId === undefined && typeof record.name === "string" &&
          record.name !== ""
        ) {
          rawId = record.name;
        }
        const fallbackId =
          [].filter((s: string) => s && s !== "undefined").join("_") ||
          "created";
        const id = sanitizeInstanceName(String(rawId ?? fallbackId));
        const handle = await context.writeResource("ruleset", id, result);
        context.logger.info("Created ruleset {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_ruleset: {
      description: "get operation",
      arguments: z.object({
        ruleset_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const result = await griptapeApi<Record<string, unknown>>(
          apiKey,
          "GET",
          `/api/rulesets/${encodeURIComponent(String(args.ruleset_id))}`,
          undefined,
          baseUrl,
        );

        if (result === undefined || result === null) {
          context.logger.info("ruleset not found (no content)", {});
          return { dataHandles: [] };
        }

        const handle = await context.writeResource(
          "ruleset",
          sanitizeInstanceName(String(args.ruleset_id)),
          result,
        );
        context.logger.info("Fetched ruleset", {});
        return { dataHandles: [handle] };
      },
    },
    update_ruleset: {
      description: "update operation",
      arguments: z.object({
        ruleset_id: z.string(),
        alias: z.string().min(1).max(200).optional(),
        description: z.string().min(1).max(200).optional(),
        metadata: z.unknown().optional(),
        name: z.string().min(1).max(200).optional(),
        rule_ids: z.array(
          z.string().regex(
            new RegExp(
              "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
            ),
          ),
        ).optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["ruleset_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await griptapeApi<Record<string, unknown>>(
          apiKey,
          "PATCH",
          `/api/rulesets/${encodeURIComponent(String(args.ruleset_id))}`,
          body,
          baseUrl,
        );

        // A 204 No Content (or empty body) yields undefined; nothing to persist.
        if (result === undefined || result === null) {
          context.logger.info("Updated ruleset (no content)", {});
          return { dataHandles: [] };
        }

        const handle = await context.writeResource(
          "ruleset",
          sanitizeInstanceName(String(args.ruleset_id)),
          result,
        );
        context.logger.info("Updated ruleset", {});
        return { dataHandles: [handle] };
      },
    },
    delete_ruleset: {
      description: "delete operation",
      arguments: z.object({
        ruleset_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, baseUrl } = context.globalArgs;
        await griptapeApi<Record<string, unknown>>(
          apiKey,
          "DELETE",
          `/api/rulesets/${encodeURIComponent(String(args.ruleset_id))}`,
          undefined,
          baseUrl,
        );

        context.logger.info("Deleted resource {id}", { id: args.ruleset_id });
        return { dataHandles: [] };
      },
    },
  },
};
