/**
 * Cloudflare D1 serverless SQL databases — databases, queries
 *
 * Auto-generated by scripts/cloudflare-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: AGPL-3.0-or-later WITH Swamp-Extension-Exception

import { z } from "npm:zod@4.4.3";
import { cfApi, cfApiPaginated } from "./_lib/api.ts";

const EXTENSION_NAME = "@webframp/cloudflare/d1";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiToken: z.string().meta({ sensitive: true }).describe(
    "Cloudflare API token",
  ),
  accountId: z.string().describe("Cloudflare account ID"),
});

const DatabasesItemSchema = z.object({
  created_at: z.unknown().optional(),
  jurisdiction: z.unknown().optional(),
  name: z.unknown().optional(),
  uuid: z.unknown().optional(),
  version: z.unknown().optional(),
});

const ListDatabasesSchema = z.object({
  items: z.array(DatabasesItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const CreateDatabaseSchema = z.object({
  created_at: z.unknown().optional(),
  file_size: z.unknown().optional(),
  jurisdiction: z.unknown().optional(),
  name: z.unknown().optional(),
  num_tables: z.unknown().optional(),
  read_replication: z.unknown().optional(),
  uuid: z.unknown().optional(),
  version: z.unknown().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const UpdatePartialDatabaseSchema = z.object({
  created_at: z.unknown().optional(),
  file_size: z.unknown().optional(),
  jurisdiction: z.unknown().optional(),
  name: z.unknown().optional(),
  num_tables: z.unknown().optional(),
  read_replication: z.unknown().optional(),
  uuid: z.unknown().optional(),
  version: z.unknown().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const CreateD1ExportDatabaseSchema = z.object({
  at_bookmark: z.string().optional().describe(
    "The current time-travel bookmark for your D1, used to poll for updates. Will not change for the d...",
  ),
  error: z.string().optional().describe(
    "Only present when status = 'error'. Contains the error message.",
  ),
  messages: z.array(z.string()).optional().describe(
    "Logs since the last time you polled",
  ),
  result: z.object({
    filename: z.string().optional(),
    signed_url: z.string().optional(),
  }).optional().describe("Only present when status = 'complete'"),
  status: z.enum(["complete", "error"]).optional(),
  success: z.boolean().optional(),
  type: z.enum(["export"]).optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const D1ImportDatabaseSchema = z.object({
  at_bookmark: z.string().optional().describe(
    "The current time-travel bookmark for your D1, used to poll for updates. Will not change for the d...",
  ),
  error: z.string().optional().describe(
    "Only present when status = 'error'. Contains the error message that prevented the import from suc...",
  ),
  filename: z.string().optional().describe(
    "Derived from the database ID and etag, to use in avoiding repeated uploads. Only returned when fo...",
  ),
  messages: z.array(z.string()).optional().describe(
    "Logs since the last time you polled",
  ),
  result: z.object({
    final_bookmark: z.string().optional(),
    meta: z.unknown().optional(),
    num_queries: z.number().optional(),
  }).optional().describe("Only present when status = 'complete'"),
  status: z.enum(["complete", "error"]).optional(),
  success: z.boolean().optional(),
  type: z.enum(["import"]).optional(),
  upload_url: z.string().optional().describe(
    "The R2 presigned URL to use for uploading. Only returned when for the 'init' action.",
  ),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const D1QueryDatabaseSchema = z.object({
  meta: z.unknown().optional(),
  results: z.array(z.object({})).optional(),
  success: z.boolean().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const D1RawDatabaseQuerySchema = z.object({
  meta: z.unknown().optional(),
  results: z.object({
    columns: z.array(z.string()).optional(),
    rows: z.array(z.array(z.union([z.number(), z.string(), z.object({})])))
      .optional(),
  }).optional(),
  success: z.boolean().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const GetBookmarkSchema = z.object({
  bookmark: z.unknown().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const D1TimeTravelRestoreSchema = z.object({
  bookmark: z.unknown().optional(),
  message: z.string().optional().describe(
    "A message describing the result of the restore operation.",
  ),
  previous_bookmark: z.unknown().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Cloudflare D1 serverless SQL databases — databases, queries */
export const model = {
  type: "@webframp/cloudflare/d1",
  version: "2026.08.26.2",
  globalArguments: GlobalArgsSchema,

  upgrades: [
    {
      toVersion: "2026.08.24.1",
      description:
        "Added optional durationMs, collectedBy, and fetchedAt output metadata fields",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.08.26.1",
      description:
        "No schema changes — restored inline npm:zod specifier for registry scoring; retained strict mode",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.08.26.2",
      description:
        "No schema changes — restored inline npm:zod specifier for registry scoring; retained strict mode",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],

  resources: {
    "databases": {
      description: "List D1 Databases",
      schema: ListDatabasesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "database": {
      description: "Create D1 Database",
      schema: CreateDatabaseSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "partial_database": {
      description: "Update D1 Database partially",
      schema: UpdatePartialDatabaseSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "d1_export_database": {
      description: "Export D1 Database as SQL",
      schema: CreateD1ExportDatabaseSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "d1_import_database": {
      description: "Import SQL into your D1 Database",
      schema: D1ImportDatabaseSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "d1_query_database": {
      description: "Query D1 Database",
      schema: D1QueryDatabaseSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "d1_raw_database_query": {
      description: "Raw D1 Database query",
      schema: D1RawDatabaseQuerySchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "bookmark": {
      description: "Get D1 database bookmark",
      schema: GetBookmarkSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "d1_time_travel_restore": {
      description: "Restore D1 Database to a bookmark or point in time",
      schema: D1TimeTravelRestoreSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
  },

  methods: {
    list_databases: {
      description: "List D1 Databases",
      arguments: z.object({
        name: z.string().optional(),
        page: z.number().optional(),
        per_page: z.number().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "per_page"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        let results: Record<string, unknown>[];
        let truncated: boolean;
        try {
          ({ results, truncated } = await cfApiPaginated<
            Record<string, unknown>
          >(
            apiToken,
            `/accounts/${accountId}/d1/database`,
            params,
          ));
        } catch (error) {
          throw new Error(
            `Failed to list D1 databases for account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("databases", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} databases", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_database: {
      description: "Create D1 Database",
      arguments: z.object({
        jurisdiction: z.unknown().optional(),
        name: z.unknown(),
        primary_location_hint: z.unknown().optional(),
        read_replication: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        if (
          args.name === undefined || args.name === null || args.name === ""
        ) {
          throw new Error(
            "create_database requires a non-empty 'name' for the D1 database",
          );
        }

        const body = args;

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "POST",
            `/accounts/${accountId}/d1/database`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to create D1 database '${args.name}' in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("database", id, {
          ...result,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });
        context.logger.info("Created database {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_database: {
      description: "Get D1 Database",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
        fields: z.string().optional().describe(
          "Comma-separated list of fields to include in the response. When omitted, all fields are returned. ",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;
        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "GET",
            `/accounts/${accountId}/d1/database/${args.database_id}`,
          );
        } catch (error) {
          throw new Error(
            `Failed to get D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "database",
          String(args.database_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Fetched database", {});
        return { dataHandles: [handle] };
      },
    },
    update_database: {
      description: "Update D1 Database",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
        read_replication: z.unknown(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["database_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "PUT",
            `/accounts/${accountId}/d1/database/${args.database_id}`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to update D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "database",
          String(args.database_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Updated database", {});
        return { dataHandles: [handle] };
      },
    },
    update_partial_database: {
      description: "Update D1 Database partially",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
        read_replication: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["database_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "PATCH",
            `/accounts/${accountId}/d1/database/${args.database_id}`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to partially update D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "partial_database",
          String(args.database_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Updated partial_database", {});
        return { dataHandles: [handle] };
      },
    },
    delete_database: {
      description: "Delete D1 Database",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, accountId } = context.globalArgs;
        try {
          await cfApi(
            apiToken,
            "DELETE",
            `/accounts/${accountId}/d1/database/${args.database_id}`,
          );
        } catch (error) {
          throw new Error(
            `Failed to delete D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        context.logger.info("Deleted resource {id}", { id: args.database_id });
        return { dataHandles: [] };
      },
    },
    create_d1_export_database: {
      description: "Export D1 Database as SQL",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
        current_bookmark: z.string().optional().describe(
          "To poll an in-progress export, provide the current bookmark (returned by your...",
        ),
        dump_options: z.object({
          no_data: z.boolean().optional(),
          no_schema: z.boolean().optional(),
          tables: z.array(z.string()).optional(),
        }).optional(),
        output_format: z.enum(["polling"]).describe(
          "Specifies that you will poll this endpoint until the export completes",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["database_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "POST",
            `/accounts/${accountId}/d1/database/${args.database_id}/export`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to export D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "d1_export_database",
          id,
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Created d1_export_database {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    d1_import_database: {
      description: "Import SQL into your D1 Database",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["database_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "POST",
            `/accounts/${accountId}/d1/database/${args.database_id}/import`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to import into D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "d1_import_database",
          "latest",
          {
            ...result ?? {},
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Executed d1_import_database", {});
        return { dataHandles: [handle] };
      },
    },
    d1_query_database: {
      description: "Query D1 Database",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["database_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "POST",
            `/accounts/${accountId}/d1/database/${args.database_id}/query`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to query D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "d1_query_database",
          "latest",
          {
            ...result ?? {},
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Executed d1_query_database", {});
        return { dataHandles: [handle] };
      },
    },
    d1_raw_database_query: {
      description: "Raw D1 Database query",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const excludeKeys = new Set(["database_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "POST",
            `/accounts/${accountId}/d1/database/${args.database_id}/raw`,
            body,
          );
        } catch (error) {
          throw new Error(
            `Failed to run raw D1 query against database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "d1_raw_database_query",
          "latest",
          {
            ...result ?? {},
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Executed d1_raw_database_query", {});
        return { dataHandles: [handle] };
      },
    },
    get_bookmark: {
      description: "Get D1 database bookmark",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
        timestamp: z.string().optional().describe(
          "An optional ISO 8601 timestamp. If provided, returns the nearest available bookmark at or before this timestamp. If omitted, returns the current bookmark.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;
        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "GET",
            `/accounts/${accountId}/d1/database/${args.database_id}/time_travel/bookmark`,
          );
        } catch (error) {
          throw new Error(
            `Failed to get time-travel bookmark for D1 database ${args.database_id} in account ${accountId}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "bookmark",
          String(args.database_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Fetched bookmark", {});
        return { dataHandles: [handle] };
      },
    },
    d1_time_travel_restore: {
      description: "Restore D1 Database to a bookmark or point in time",
      arguments: z.object({
        database_id: z.string().min(1, "database_id must not be empty"),
        bookmark: z.string().optional().describe(
          "A bookmark to restore the database to. Required if `timestamp` is not provided.",
        ),
        timestamp: z.string().optional().describe(
          "An ISO 8601 timestamp to restore the database to. Required if `bookmark` is not provided.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, accountId } = context.globalArgs;

        if (args.bookmark === undefined && args.timestamp === undefined) {
          throw new Error(
            "d1_time_travel_restore requires either 'bookmark' or 'timestamp' to identify the restore point",
          );
        }

        const queryParts: string[] = [];
        const queryKeys = new Set(["bookmark", "timestamp"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && queryKeys.has(k)) {
            queryParts.push(`${k}=${encodeURIComponent(String(v))}`);
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        let result: Record<string, unknown>;
        try {
          result = await cfApi<Record<string, unknown>>(
            apiToken,
            "POST",
            `/accounts/${accountId}/d1/database/${args.database_id}/time_travel/restore${qs}`,
          );
        } catch (error) {
          throw new Error(
            `Failed to restore D1 database ${args.database_id} in account ${accountId} to bookmark=${
              args.bookmark ?? "n/a"
            } timestamp=${args.timestamp ?? "n/a"}: ${
              error instanceof Error ? error.message : String(error)
            }`,
            { cause: error },
          );
        }

        const handle = await context.writeResource(
          "d1_time_travel_restore",
          "latest",
          {
            ...result ?? {},
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Executed d1_time_travel_restore", {});
        return { dataHandles: [handle] };
      },
    },
  },
};
