// Snyk Groups — group management, orgs, members, and audit — Tests
// Auto-generated by scripts/snyk-codegen — do not edit manually.
// SPDX-License-Identifier: Apache-2.0

import { assertEquals, assertExists } from "jsr:@std/assert@1.0.19";
import { createModelTestContext } from "@systeminit/swamp-testing";
import { model } from "./groups.ts";

// ---------------------------------------------------------------------------
// Model Export Structure Tests
// ---------------------------------------------------------------------------

Deno.test("groups model: has correct type", () => {
  assertEquals(model.type, "@webframp/snyk/groups");
});

Deno.test("groups model: has valid version format", () => {
  const versionPattern = /^\d{4}\.\d{2}\.\d{2}\.\d+$/;
  assertEquals(versionPattern.test(model.version), true);
});

Deno.test("groups model: has globalArguments with apiToken", () => {
  assertExists(model.globalArguments);
  const shape = model.globalArguments.shape;
  assertExists(shape.apiToken);
  assertExists(shape.groupId);
  assertExists(shape.version);
});

Deno.test("groups model: has expected methods", () => {
  assertExists(model.methods);
  assertExists(model.methods.list_groups);
  assertExists(model.methods.get_group);
  assertExists(model.methods.list_group_audit_logs);
  assertExists(model.methods.create_group_export);
  assertExists(model.methods.get_group_export);
  assertExists(model.methods.get_group_export_job_status);
  assertExists(model.methods.list_group_user_org_memberships);
  assertExists(model.methods.list_orgs_in_group);
  assertExists(model.methods.list_group_policies);
  assertExists(model.methods.create_group_policy);
  assertExists(model.methods.update_group_policy);
  assertExists(model.methods.delete_group_policy);
  assertExists(model.methods.list_assignments);
  assertExists(model.methods.create_assignments);
  assertExists(model.methods.delete_assignments);
  assertExists(model.methods.list_secrets_rule_extensions);
  assertExists(model.methods.create_secrets_rule_extension);
  assertExists(model.methods.get_secrets_rule_extension);
  assertExists(model.methods.update_secrets_rule_extension);
  assertExists(model.methods.delete_secrets_rule_extension);
  assertExists(model.methods.update_user);
});

Deno.test("groups model: has expected resources", () => {
  assertExists(model.resources);
  assertExists(model.resources["groups"]);
  assertExists(model.resources["group"]);
  assertExists(model.resources["list_group_audit_logs"]);
  assertExists(model.resources["group_export"]);
  assertExists(model.resources["group_export_job_status"]);
  assertExists(model.resources["group_user_org_memberships"]);
  assertExists(model.resources["orgs_in_group"]);
  assertExists(model.resources["group_policies"]);
  assertExists(model.resources["group_policy"]);
  assertExists(model.resources["assignments"]);
  assertExists(model.resources["secrets_rule_extensions"]);
  assertExists(model.resources["secrets_rule_extension"]);
  assertExists(model.resources["user"]);
});

// ---------------------------------------------------------------------------
// Mock Snyk API Server
// ---------------------------------------------------------------------------

function startMockSnykServer(
  responses: Record<string, { data: unknown; isCollection?: boolean }>,
): { url: string; server: Deno.HttpServer } {
  const server = Deno.serve({ port: 0, onListen() {} }, (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    for (const [pattern, { data, isCollection }] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        const body = isCollection
          ? {
            data: Array.isArray(data) ? data : [data],
            jsonapi: { version: "1.0" },
            links: { self: path, next: null },
          }
          : {
            data,
            jsonapi: { version: "1.0" },
            links: { self: path },
          };
        return Response.json(body, {
          headers: { "content-type": "application/vnd.api+json" },
        });
      }
    }

    return new Response(
      JSON.stringify({
        jsonapi: { version: "1.0" },
        errors: [{ status: "404", detail: "Not found" }],
      }),
      { status: 404, headers: { "content-type": "application/vnd.api+json" } },
    );
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: `http://localhost:${addr.port}`, server };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    const newUrl = reqUrl.replace("https://api.snyk.io/rest", mockUrl);
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}

Deno.test({
  name: "groups model: list_groups fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockItem = {
      "id": "fixture-123",
      "type": "resource",
      "attributes": { "name": "My Group" },
    };
    const { url, server } = startMockSnykServer({
      "/groups": { data: [mockItem], isCollection: true },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "groupId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-groups",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).list_groups.execute({}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "groups model: get_group fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "id": "fixture-123",
      "type": "resource",
      "attributes": {
        "avatar_url": "https://example.com",
        "created_at": "2024-01-01T00:00:00Z",
        "logo_url": "https://example.com",
        "name": "test-value",
        "slug": "test-value",
        "updated_at": "2024-01-01T00:00:00Z",
        "tenant_id": "test-value",
      },
    };
    const { url, server } = startMockSnykServer({
      "": { data: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "groupId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-groups",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).get_group.execute({}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "groups model: create_group_export executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = { "id": "fixture-123", "type": "resource" };
    const { url, server } = startMockSnykServer({
      "/export": { data: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "groupId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-groups",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).create_group_export.execute({ "name": "test-resource" }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "groups model: create_group_policy creates and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "id": "new-123",
      "type": "resource",
      "attributes": {
        "action": null,
        "action_type": "ignore",
        "conditions_group": { "conditions": [], "logical_operator": null },
        "created_at": "2024-03-16T00:00:00Z",
        "created_by": {
          "email": "test-value",
          "id": "test-value",
          "name": "test-value",
        },
        "name": "test-value",
        "updated_at": "2024-03-16T00:00:00Z",
      },
    };
    const { url, server } = startMockSnykServer({
      "/policies": { data: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "groupId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-groups",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).create_group_policy.execute({ "name": "test-resource" }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "groups model: update_group_policy executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "id": "fixture-123",
      "type": "resource",
      "attributes": {
        "action": null,
        "action_type": "ignore",
        "conditions_group": { "conditions": [], "logical_operator": null },
        "created_at": "2024-03-16T00:00:00Z",
        "created_by": {
          "email": "test-value",
          "id": "test-value",
          "name": "test-value",
        },
        "name": "test-value",
        "updated_at": "2024-03-16T00:00:00Z",
      },
    };
    const { url, server } = startMockSnykServer({
      "/policies/test-id-123": { data: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "groupId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-groups",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).update_group_policy.execute({
        "policy_id": "test-id-123",
        "name": "test-resource",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "groups model: delete_group_policy executes successfully",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockSnykServer({
      "/policies/test-id-123": {
        data: { id: "test-id-123", type: "resource" },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "groupId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-groups",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).delete_group_policy.execute({ "policy_id": "test-id-123" }, context);
      assertEquals(result.dataHandles.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});
