/**
 * Snyk Groups — group management, orgs, members, and audit
 *
 * Auto-generated by scripts/snyk-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: AGPL-3.0-or-later WITH Swamp-Extension-Exception

import { z } from "zod";
import { snykApi, snykApiPaginated } from "./_lib/api.ts";

const EXTENSION_NAME = "@webframp/snyk/groups";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiToken: z.string().meta({ sensitive: true }).describe("Snyk API token"),
  groupId: z.string().describe("Snyk group ID"),
  version: z.string().default("2024-10-15").describe("Snyk API version date"),
});

const GroupsItemSchema = z.object({
  id: z.string(),
  type: z.string().optional().describe("Content type."),
  name: z.string().min(1).describe("The name of the group."),
});

const ListGroupsSchema = z.object({
  items: z.array(GroupsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const GetGroupSchema = z.object({
  id: z.string(),
  type: z.enum(["group"]).optional().describe(
    "The type of the resource for group operations",
  ),
  avatar_url: z.string().optional().describe(
    "The URL of an image to use as the group's avatar.",
  ),
  created_at: z.string().describe("The time the group was created."),
  logo_url: z.string().optional().describe(
    "The URL of an image to use as the group's logo.",
  ),
  name: z.string().min(1).describe("The name of the group."),
  slug: z.string().optional().describe("A slug uniquely identifying the group"),
  updated_at: z.string().describe("The time the group was created."),
  tenant_id: z.string().optional().describe("Related tenant ID"),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const ListGroupAuditLogsSchema = z.object({
  type: z.string().optional(),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const GroupUserOrgMembershipsItemSchema = z.object({
  id: z.string(),
  type: z.string().optional().describe("Content type."),
  created_at: z.unknown().optional().describe(
    "The date that the org membership was created on",
  ),
  org_id: z.string().optional().describe("Related org ID"),
  role_id: z.string().optional().describe("Related role ID"),
  user_id: z.string().optional().describe("Related user ID"),
});

const ListGroupUserOrgMembershipsSchema = z.object({
  items: z.array(GroupUserOrgMembershipsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const OrgsInGroupItemSchema = z.object({
  id: z.string().describe("The Snyk ID of the organization."),
  type: z.string().optional(),
  access_requests_enabled: z.boolean().optional().describe(
    "Whether the organization permits access requests from users who are not members of the organization.",
  ),
  created_at: z.string().optional().describe(
    "The time the organization was created.",
  ),
  group_id: z.string().optional().describe(
    "The Snyk ID of the group to which the organization belongs.",
  ),
  is_personal: z.boolean().describe(
    "Whether the organization is independent (that is, not part of a group).",
  ),
  name: z.string().min(1).describe("The display name of the organization."),
  slug: z.string().describe(
    "The canonical (unique and URL-friendly) name of the organization.",
  ),
  updated_at: z.string().optional().describe(
    "The time the organization was last modified.",
  ),
});

const ListOrgsInGroupSchema = z.object({
  items: z.array(OrgsInGroupItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const GroupPoliciesItemSchema = z.object({
  id: z.string().describe(
    "A unique identifier for this particular occurrence of the group level policy.",
  ),
  type: z.enum(["policy"]).optional(),
  action: z.union([z.unknown(), z.unknown(), z.unknown()]).describe(
    "The action to apply when this policy's conditions match",
  ),
  action_type: z.enum(["ignore", "annotation", "severity-override"]).describe(
    "The kind of action this policy performs",
  ),
  conditions_group: z.object({
    conditions: z.array(
      z.union([
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
      ]),
    ),
    logical_operator: z.unknown().describe(
      "How the listed conditions are combined (e.g. AND/OR)",
    ),
  }).describe("The set of conditions that must match for this policy to apply"),
  created_at: z.string().describe("When the policy was created"),
  created_by: z.object({
    email: z.string().nullable().optional(),
    id: z.string(),
    name: z.string(),
  }).describe("The user who created the policy"),
  name: z.string().describe("Name of the policy"),
  updated_at: z.string().describe("When the policy was last updated"),
});

const ListGroupPoliciesSchema = z.object({
  items: z.array(GroupPoliciesItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const CreateGroupPolicySchema = z.object({
  id: z.string().describe(
    "A unique identifier for this particular occurrence of the group level policy.",
  ),
  type: z.enum(["policy"]).optional(),
  action: z.union([z.unknown(), z.unknown(), z.unknown()]).describe(
    "The action to apply when this policy's conditions match",
  ),
  action_type: z.enum(["ignore", "annotation", "severity-override"]).describe(
    "The kind of action this policy performs",
  ),
  conditions_group: z.object({
    conditions: z.array(
      z.union([
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
        z.unknown(),
      ]),
    ),
    logical_operator: z.unknown().describe(
      "How the listed conditions are combined (e.g. AND/OR)",
    ),
  }).describe("The set of conditions that must match for this policy to apply"),
  created_at: z.string().describe("When the policy was created"),
  created_by: z.object({
    email: z.string().nullable().optional(),
    id: z.string(),
    name: z.string(),
  }).describe("The user who created the policy"),
  name: z.string().describe("Name of the policy"),
  updated_at: z.string().describe("When the policy was last updated"),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const AssignmentsItemSchema = z.object({
  id: z.string().describe("The unique identifier of the assignment."),
  type: z.enum(["assignments"]).optional().describe(
    'The type identifier for the "assignments" resource.',
  ),
  created_at: z.string().describe(
    "The timestamp when the assignment was created.",
  ),
  created_by: z.string().optional().describe(
    "The ID of the user who created the assignment.",
  ),
  rule_extension_id: z.string().optional().describe(
    "Related rule_extension ID",
  ),
  scope_id: z.string().optional().describe("Related scope ID"),
});

const ListAssignmentsSchema = z.object({
  items: z.array(AssignmentsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const SecretsRuleExtensionsItemSchema = z.object({
  id: z.string().describe("Unique identifier for a SAST rule extension"),
  type: z.enum(["rule_extensions"]).optional().describe(
    'The type identifier for the "rule_extensions" resource.',
  ),
  configuration: z.object({
    type: z.enum(["addition"]),
  }),
  created_at: z.string().describe(
    "Timestamp when the rule extension was created",
  ),
  created_by: z.string().describe(
    "User ID of the user who created the Secrets rule extension",
  ),
  description: z.string().max(4000).optional().describe(
    "The description for a rule extension to provide extra details on why it is safe to assume issues ...",
  ),
  kind: z.enum(["secrets_regex"]).describe(
    "Kind value for secrets regex rule extensions.",
  ),
  published_at: z.string().nullable().describe(
    "Timestamp when the rule extension was published",
  ),
  published_by: z.string().nullable().describe(
    "User ID of the user who published the rule extension",
  ),
  signature: z.object({
    regex_pattern: z.string().max(1000),
  }),
  status: z.enum(["published", "draft"]).describe(
    "The status for a rule extension. Rule extensions in draft do not apply to any analysis test until...",
  ),
  updated_at: z.string().describe(
    "Timestamp when the rule extension was last updated",
  ),
  updated_by: z.string().describe(
    "User ID of the user who updated the Secrets rule extension",
  ),
});

const ListSecretsRuleExtensionsSchema = z.object({
  items: z.array(SecretsRuleExtensionsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

const CreateSecretsRuleExtensionSchema = z.object({
  id: z.string().describe("Unique identifier for a SAST rule extension"),
  type: z.enum(["rule_extensions"]).optional().describe(
    'The type identifier for the "rule_extensions" resource.',
  ),
  configuration: z.object({
    type: z.enum(["addition"]),
  }),
  created_at: z.string().describe(
    "Timestamp when the rule extension was created",
  ),
  created_by: z.string().describe(
    "User ID of the user who created the Secrets rule extension",
  ),
  description: z.string().max(4000).optional().describe(
    "The description for a rule extension to provide extra details on why it is safe to assume issues ...",
  ),
  kind: z.enum(["secrets_regex"]).describe(
    "Kind value for secrets regex rule extensions.",
  ),
  published_at: z.string().nullable().describe(
    "Timestamp when the rule extension was published",
  ),
  published_by: z.string().nullable().describe(
    "User ID of the user who published the rule extension",
  ),
  signature: z.object({
    regex_pattern: z.string().max(1000),
  }),
  status: z.enum(["published", "draft"]).describe(
    "The status for a rule extension. Rule extensions in draft do not apply to any analysis test until...",
  ),
  updated_at: z.string().describe(
    "Timestamp when the rule extension was last updated",
  ),
  updated_by: z.string().describe(
    "User ID of the user who updated the Secrets rule extension",
  ),
  fetchedAt: z.string().optional().describe(
    "ISO 8601 timestamp when data was fetched",
  ),
  durationMs: z.number().optional().describe(
    "Method execution duration in milliseconds",
  ),
  collectedBy: z.string().optional().describe(
    "Extension that collected this data",
  ),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Snyk Groups — group management, orgs, members, and audit */
export const model = {
  type: "@webframp/snyk/groups",
  version: "2026.08.26.1",
  globalArguments: GlobalArgsSchema,

  upgrades: [
    {
      toVersion: "2026.08.21.2",
      description:
        "Snyk API errors now include the HTTP method and path attempted instead of just the raw status/body. No stored-resource schema changes.",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },

    {
      toVersion: "2026.08.24.1",

      description:
        "Added optional durationMs, collectedBy, and fetchedAt output metadata fields",

      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.08.25.1",
      description: "Label metadata update, no schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],

  resources: {
    "groups": {
      description: "Get all groups (Early Access)",
      schema: ListGroupsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "group": {
      description: "Get Group (Early Access)",
      schema: GetGroupSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "list_group_audit_logs": {
      description: "Search Group audit logs.",
      schema: ListGroupAuditLogsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "group_export": {
      description: "Start an export",
      schema: z.object({}),
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "group_export_job_status": {
      description: "Get export status",
      schema: z.object({}),
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "group_user_org_memberships": {
      description: "Get list of org memberships of a group user",
      schema: ListGroupUserOrgMembershipsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "orgs_in_group": {
      description: "List all organizations in group",
      schema: ListOrgsInGroupSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "group_policies": {
      description: "Get group level policies (Early Access)",
      schema: ListGroupPoliciesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "group_policy": {
      description: "Create a new group level policy (Early Access)",
      schema: CreateGroupPolicySchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "assignments": {
      description: "List all assignments for a group",
      schema: ListAssignmentsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "secrets_rule_extensions": {
      description:
        "Get a list of all secrets rule extensions for the requested Group",
      schema: ListSecretsRuleExtensionsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "secrets_rule_extension": {
      description: "Create a secrets rule extension",
      schema: CreateSecretsRuleExtensionSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "user": {
      description: "Update a user's role in a group (Early Access)",
      schema: z.object({}),
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
  },

  methods: {
    list_groups: {
      description: "Get all groups (Early Access)",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("groups", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} groups", { count: results.length });
        return { dataHandles: [handle] };
      },
    },
    get_group: {
      description: "Get Group (Early Access)",
      arguments: z.object({}),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const result = await snykApi(
          apiToken,
          "GET",
          `/groups/${groupId}`,
          version,
        );

        const handle = await context.writeResource("group", "latest", {
          ...result,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });
        context.logger.info("Fetched group", {});
        return { dataHandles: [handle] };
      },
    },
    list_group_audit_logs: {
      description: "Search Group audit logs.",
      arguments: z.object({
        cursor: z.string().optional().describe(
          "The ID for the next page of results.",
        ),
        from: z.string().optional().describe(
          "The start date (inclusive) of the audit logs search. If not specified, the st...",
        ),
        to: z.string().optional().describe(
          "The end date (exclusive) of the audit logs search. Dates should be formatted ...",
        ),
        size: z.number().optional().describe(
          "Number of results to return per page.",
        ),
        sort_order: z.enum(["ASC", "DESC"]).optional().describe(
          "Order in which results are returned.",
        ),
        user_id: z.string().optional().describe("Filter logs by user ID."),
        project_id: z.string().optional().describe(
          "Filter logs by project ID.",
        ),
        events: z.string().optional().describe(
          "Filter logs by event types, cannot be used in conjunction with exclude_events...",
        ),
        exclude_events: z.string().optional().describe(
          "Exclude event types from results, cannot be used in conjunctions with events ...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            queryParts.push(
              `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await snykApi(
          apiToken,
          "GET",
          `/groups/${groupId}/audit_logs/search${qs}`,
          version,
        );

        const handle = await context.writeResource(
          "list_group_audit_logs",
          "latest",
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Fetched list_group_audit_logs", {});
        return { dataHandles: [handle] };
      },
    },
    create_group_export: {
      description: "Start an export",
      arguments: z.object({
        include_deleted: z.string().optional().describe(
          "Optional parameter to include deleted issues in results",
        ),
        include_deactivated: z.string().optional().describe(
          "Optional parameter to include disabled issues in results",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const queryParts: string[] = [];
        const pathKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !pathKeys.has(k)) {
            queryParts.push(
              `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await snykApi(
          apiToken,
          "POST",
          `/groups/${groupId}/export${qs}`,
          version,
        );

        const handle = await context.writeResource(
          "group_export",
          "latest",
          {
            ...result ?? {},
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Executed create_group_export", {});
        return { dataHandles: [handle] };
      },
    },
    get_group_export: {
      description: "Get export results",
      arguments: z.object({
        export_id: z.string().describe("Unique export identifier"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const result = await snykApi(
          apiToken,
          "GET",
          `/groups/${groupId}/export/${args.export_id}`,
          version,
        );

        const handle = await context.writeResource(
          "group_export",
          String(args.export_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Fetched group_export", {});
        return { dataHandles: [handle] };
      },
    },
    get_group_export_job_status: {
      description: "Get export status",
      arguments: z.object({
        export_id: z.string().describe("Unique export identifier"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const result = await snykApi(
          apiToken,
          "GET",
          `/groups/${groupId}/jobs/export/${args.export_id}`,
          version,
        );

        const handle = await context.writeResource(
          "group_export_job_status",
          String(args.export_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Fetched group_export_job_status", {});
        return { dataHandles: [handle] };
      },
    },
    list_group_user_org_memberships: {
      description: "Get list of org memberships of a group user",
      arguments: z.object({
        user_id: z.string().optional().describe("The ID of the User"),
        org_name: z.string().optional().describe("The Name of the org"),
        role_name: z.string().optional().describe(
          "Filter the response for results only with the specified role.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/org_memberships`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "group_user_org_memberships",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );

        context.logger.info("Found {count} group_user_org_memberships", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    list_orgs_in_group: {
      description: "List all organizations in group",
      arguments: z.object({
        name: z.string().optional().describe(
          "Only return organizations whose name contains this value. Case insensitive.",
        ),
        slug: z.string().optional().describe(
          "Only return organizations whose slug exactly matches this value. Case sensitive.",
        ),
        expand: z.enum(["count"]).optional().describe(
          "Expand the response with additional fields. When set to `count`, the response...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/orgs`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("orgs_in_group", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} orgs_in_group", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    list_group_policies: {
      description: "Get group level policies (Early Access)",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/policies`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("group_policies", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} group_policies", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_group_policy: {
      description: "Create a new group level policy (Early Access)",
      arguments: z.object({
        data: z.object({
          attributes: z.unknown(),
          type: z.enum(["policy"]),
        }),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "POST",
          `/groups/${groupId}/policies`,
          version,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("group_policy", id, {
          ...result,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });
        context.logger.info("Created group_policy {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    update_group_policy: {
      description: "Update a group-level policy (Early Access)",
      arguments: z.object({
        policy_id: z.string().describe("Policy ID"),
        data: z.object({
          attributes: z.unknown(),
          id: z.string(),
          type: z.enum(["policy"]),
        }),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["policy_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "PATCH",
          `/groups/${groupId}/policies/${args.policy_id}`,
          version,
          body,
        );

        const handle = await context.writeResource(
          "group_policy",
          String(args.policy_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Updated group_policy", {});
        return { dataHandles: [handle] };
      },
    },
    delete_group_policy: {
      description: "Delete an group-level policy (Early Access)",
      arguments: z.object({
        policy_id: z.string().describe("Policy ID"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        await snykApi(
          apiToken,
          "DELETE",
          `/groups/${groupId}/policies/${args.policy_id}`,
          version,
        );

        context.logger.info("Deleted resource {id}", { id: args.policy_id });
        return { dataHandles: [] };
      },
    },
    list_assignments: {
      description: "List all assignments for a group",
      arguments: z.object({
        rule_extension_id: z.string().optional().describe(
          "Filter by rule extension IDs",
        ),
        org_id: z.string().optional().describe("Filter by organization ID"),
        group_id: z.string().optional().describe("Filter by group ID"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/rule_extensions/assignments`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("assignments", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });

        context.logger.info("Found {count} assignments", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_assignments: {
      description: "Create bulk assignments for rule extensions",
      arguments: z.object({
        data: z.unknown(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "POST",
          `/groups/${groupId}/rule_extensions/assignments`,
          version,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("assignments", id, {
          ...result,
          fetchedAt: new Date().toISOString(),
          durationMs: Date.now() - startMs,
          collectedBy: EXTENSION_NAME,
        });
        context.logger.info("Created assignments {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    delete_assignments: {
      description: "Delete assignments for rule extensions",
      arguments: z.object({
        id: z.string().optional().describe("Filter by IDs"),
        rule_extension_id: z.string().optional().describe(
          "Filter by rule extension ID",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        const queryParts: string[] = [];
        const pathKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !pathKeys.has(k)) {
            queryParts.push(
              `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        await snykApi(
          apiToken,
          "DELETE",
          `/groups/${groupId}/rule_extensions/assignments${qs}`,
          version,
        );

        context.logger.info("Deleted resource {id}", { id: "unknown" });
        return { dataHandles: [] };
      },
    },
    list_secrets_rule_extensions: {
      description:
        "Get a list of all secrets rule extensions for the requested Group",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await snykApiPaginated(
          apiToken,
          `/groups/${groupId}/secrets/rule_extensions`,
          version,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "secrets_rule_extensions",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );

        context.logger.info("Found {count} secrets_rule_extensions", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_secrets_rule_extension: {
      description: "Create a secrets rule extension",
      arguments: z.object({
        data: z.unknown(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>([]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "POST",
          `/groups/${groupId}/secrets/rule_extensions`,
          version,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "secrets_rule_extension",
          id,
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Created secrets_rule_extension {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_secrets_rule_extension: {
      description: "Get a secrets rule extension by rule extension ID",
      arguments: z.object({
        rule_extension_id: z.string().describe(
          "Unique identifier for a rule extension in request path",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const result = await snykApi(
          apiToken,
          "GET",
          `/groups/${groupId}/secrets/rule_extensions/${args.rule_extension_id}`,
          version,
        );

        const handle = await context.writeResource(
          "secrets_rule_extension",
          String(args.rule_extension_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Fetched secrets_rule_extension", {});
        return { dataHandles: [handle] };
      },
    },
    update_secrets_rule_extension: {
      description: "Update a secrets rule extension by rule extension ID",
      arguments: z.object({
        rule_extension_id: z.string().describe(
          "Unique identifier for a rule extension in request path",
        ),
        data: z.unknown(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["rule_extension_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "PATCH",
          `/groups/${groupId}/secrets/rule_extensions/${args.rule_extension_id}`,
          version,
          body,
        );

        const handle = await context.writeResource(
          "secrets_rule_extension",
          String(args.rule_extension_id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Updated secrets_rule_extension", {});
        return { dataHandles: [handle] };
      },
    },
    delete_secrets_rule_extension: {
      description: "Delete a secrets rule extension by rule extension ID",
      arguments: z.object({
        rule_extension_id: z.string().describe(
          "Unique identifier for a rule extension in request path",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, groupId, version } = context.globalArgs;
        await snykApi(
          apiToken,
          "DELETE",
          `/groups/${groupId}/secrets/rule_extensions/${args.rule_extension_id}`,
          version,
        );

        context.logger.info("Deleted resource {id}", {
          id: args.rule_extension_id,
        });
        return { dataHandles: [] };
      },
    },
    update_user: {
      description: "Update a user's role in a group (Early Access)",
      arguments: z.object({
        id: z.string().describe("The id of the user"),
        data: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const startMs = Date.now();
        const { apiToken, groupId, version } = context.globalArgs;
        const body: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) body[k] = v;
        }

        const result = await snykApi(
          apiToken,
          "PATCH",
          `/groups/${groupId}/users/${args.id}`,
          version,
          body,
        );

        const handle = await context.writeResource(
          "user",
          String(args.id),
          {
            ...result,
            fetchedAt: new Date().toISOString(),
            durationMs: Date.now() - startMs,
            collectedBy: EXTENSION_NAME,
          },
        );
        context.logger.info("Updated user", {});
        return { dataHandles: [handle] };
      },
    },
  },
};
