// Datadog Synthetics — synthetic monitoring tests, results, and locations — Tests
// Auto-generated by scripts/datadog-codegen — do not edit manually.
// SPDX-License-Identifier: Apache-2.0

import {
  assertEquals,
  assertExists,
  assertStringIncludes,
} from "jsr:@std/assert@1.0.19";
import { createModelTestContext } from "@systeminit/swamp-testing";
import { model } from "./synthetics.ts";

// ---------------------------------------------------------------------------
// Model Export Structure Tests
// ---------------------------------------------------------------------------

Deno.test("synthetics model: has correct type", () => {
  assertEquals(model.type, "@webframp/datadog/synthetics");
});

Deno.test("synthetics model: has valid version format", () => {
  const versionPattern = /^\d{4}\.\d{2}\.\d{2}\.\d+$/;
  assertEquals(versionPattern.test(model.version), true);
});

Deno.test("synthetics model: has globalArguments with apiKey and appKey", () => {
  assertExists(model.globalArguments);
  const shape = model.globalArguments.shape;
  assertExists(shape.apiKey);
  assertExists(shape.appKey);
  assertExists(shape.site);
});

Deno.test("synthetics model: has expected methods", () => {
  assertExists(model.methods);
  assertExists(model.methods.get_api_multistep_subtests);
  assertExists(model.methods.get_api_multistep_subtest_parents);
  assertExists(model.methods.list_synthetics_downtimes);
  assertExists(model.methods.create_synthetics_downtime);
  assertExists(model.methods.get_synthetics_downtime);
  assertExists(model.methods.update_synthetics_downtime);
  assertExists(model.methods.delete_synthetics_downtime);
  assertExists(model.methods.add_test_to_synthetics_downtime);
  assertExists(model.methods.remove_test_from_synthetics_downtime);
  assertExists(model.methods.get_on_demand_concurrency_cap);
  assertExists(model.methods.set_on_demand_concurrency_cap);
  assertExists(model.methods.create_synthetics_suite);
  assertExists(model.methods.delete_synthetics_suites);
  assertExists(model.methods.search_suites);
  assertExists(model.methods.get_synthetics_suite);
  assertExists(model.methods.edit_synthetics_suite);
  assertExists(model.methods.patch_test_suite);
  assertExists(model.methods.list_synthetics_browser_test_latest_results);
  assertExists(model.methods.get_synthetics_browser_test_result);
  assertExists(model.methods.delete_synthetics_tests);
  assertExists(model.methods.get_synthetics_fast_test_result);
  assertExists(model.methods.create_synthetics_network_test);
  assertExists(model.methods.get_synthetics_network_test);
  assertExists(model.methods.update_synthetics_network_test);
  assertExists(model.methods.poll_synthetics_test_results);
  assertExists(model.methods.get_test_file_download_url);
  assertExists(model.methods.get_test_file_multipart_presigned_urls);
  assertExists(model.methods.abort_test_file_multipart_upload);
  assertExists(model.methods.complete_test_file_multipart_upload);
  assertExists(model.methods.get_test_parent_suites);
  assertExists(model.methods.list_synthetics_test_latest_results);
  assertExists(model.methods.get_synthetics_test_result);
  assertExists(model.methods.list_synthetics_test_versions);
  assertExists(model.methods.get_synthetics_test_version);
  assertExists(model.methods.patch_global_variable);
});

Deno.test("synthetics model: has expected resources", () => {
  assertExists(model.resources);
  assertExists(model.resources["api_multistep_subtests"]);
  assertExists(model.resources["api_multistep_subtest_parents"]);
  assertExists(model.resources["synthetics_downtimes"]);
  assertExists(model.resources["synthetics_downtime"]);
  assertExists(model.resources["add_test_to_synthetics_downtime"]);
  assertExists(model.resources["on_demand_concurrency_cap"]);
  assertExists(model.resources["set_on_demand_concurrency_cap"]);
  assertExists(model.resources["synthetics_suite"]);
  assertExists(model.resources["synthetics_suites"]);
  assertExists(model.resources["search_suites"]);
  assertExists(model.resources["edit_synthetics_suite"]);
  assertExists(model.resources["patch_test_suite"]);
  assertExists(model.resources["synthetics_browser_test_latest_results"]);
  assertExists(model.resources["synthetics_browser_test_result"]);
  assertExists(model.resources["synthetics_tests"]);
  assertExists(model.resources["synthetics_fast_test_result"]);
  assertExists(model.resources["synthetics_network_test"]);
  assertExists(model.resources["poll_synthetics_test_results"]);
  assertExists(model.resources["test_file_download_url"]);
  assertExists(model.resources["test_file_multipart_presigned_urls"]);
  assertExists(model.resources["abort_test_file_multipart_upload"]);
  assertExists(model.resources["complete_test_file_multipart_upload"]);
  assertExists(model.resources["test_parent_suites"]);
  assertExists(model.resources["synthetics_test_latest_results"]);
  assertExists(model.resources["synthetics_test_result"]);
  assertExists(model.resources["synthetics_test_versions"]);
  assertExists(model.resources["synthetics_test_version"]);
  assertExists(model.resources["patch_global_variable"]);
});

// ---------------------------------------------------------------------------
// Mock Datadog API Server
// ---------------------------------------------------------------------------

interface CapturedRequest {
  method: string;
  path: string;
  search: string;
  headers: Record<string, string>;
  body: unknown;
}

function startMockDdServer(
  responses: Record<string, { body: unknown; status?: number }>,
): { url: string; server: Deno.HttpServer; requests: CapturedRequest[] } {
  const requests: CapturedRequest[] = [];
  const server = Deno.serve({ port: 0, onListen() {} }, async (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    // Capture the request (headers, method, path, parsed body) for assertions.
    let body: unknown = null;
    if (req.body) {
      const text = await req.text();
      if (text) {
        try {
          body = JSON.parse(text);
        } catch {
          body = text;
        }
      }
    }
    requests.push({
      method: req.method,
      path,
      search: url.search,
      headers: Object.fromEntries(req.headers),
      body,
    });

    for (
      const [pattern, { body: respBody, status }] of Object.entries(responses)
    ) {
      if (path.includes(pattern)) {
        const code = status ?? 200;
        if (code === 204 || code === 205) {
          return new Response(null, { status: code });
        }
        return Response.json(respBody, { status: code });
      }
    }

    return Response.json(
      { errors: [{ status: "404", title: "Not found" }] },
      { status: 404 },
    );
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: `http://localhost:${addr.port}`, server, requests };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    // Replace any DD site URL with the mock
    const newUrl = reqUrl
      .replace("https://api.datadoghq.com", mockUrl)
      .replace("https://us3.datadoghq.com", mockUrl)
      .replace("https://us5.datadoghq.com", mockUrl)
      .replace("https://api.datadoghq.eu", mockUrl)
      .replace("https://ap1.datadoghq.com", mockUrl)
      .replace("https://api.ddog-gov.com", mockUrl);
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}

Deno.test({
  name:
    "synthetics model: get_api_multistep_subtests fetches and writes resource",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server, requests } = startMockDdServer({
      "/subtests/test-id-123": {
        body: {
          "data": [{
            "id": "fixture-123",
            "type": "resource",
            "attributes": { "name": "My API Test", "public_id": "abc-def-123" },
          }],
          "meta": { "page": {} },
        },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).get_api_multistep_subtests.execute(
        { "public_id": "test-id-123" },
        context,
      );
      assertEquals(result.dataHandles.length, 1);

      assertEquals(requests.length >= 1, true);
      const req0 = requests[0];
      assertEquals(req0.method, "GET");
      assertStringIncludes(req0.path, "/subtests/test-id-123");
      assertEquals(req0.headers["dd-api-key"], "test-api-key");
      assertEquals(req0.headers["dd-application-key"], "test-app-key");

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
      assertEquals(resources[0].specName, "api_multistep_subtests");
      const data = resources[0].data as {
        items: unknown[];
        truncated: boolean;
      };
      assertEquals(Array.isArray(data.items), true);
      assertEquals(data.items.length, 1);
      assertEquals(typeof data.truncated, "boolean");
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "synthetics model: create_synthetics_downtime creates and writes resource",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server, requests } = startMockDdServer({
      "/synthetics/downtimes": {
        body: {
          "data": {
            "id": "new-123",
            "type": "resource",
            "attributes": {
              "createdAt": "2024-01-15T10:30:00Z",
              "createdBy": "00000000-0000-0000-0000-000000000003",
              "createdByName": "Jane Doe",
              "description": "Scheduled weekly maintenance window.",
              "isEnabled": true,
              "name": "Weekly maintenance",
              "tags": ["team:backend", "env:prod"],
              "testIds": ["abc-def-123", "xyz-uvw-456"],
              "timeSlots": [{
                "duration": 3600,
                "id": "00000000-0000-0000-0000-000000000002",
                "start": {
                  "day": 15,
                  "hour": 10,
                  "minute": 30,
                  "month": 1,
                  "year": 2024,
                },
                "timezone": "Europe/Paris",
              }],
              "updatedAt": "2024-01-15T10:30:00Z",
              "updatedBy": "00000000-0000-0000-0000-000000000003",
              "updatedByName": "Jane Doe",
            },
          },
        },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).create_synthetics_downtime.execute(
        { "name": "test-resource" },
        context,
      );
      assertEquals(result.dataHandles.length, 1);

      assertEquals(requests.length >= 1, true);
      const req0 = requests[0];
      assertEquals(req0.method, "POST");
      assertStringIncludes(req0.path, "/synthetics/downtimes");
      assertEquals(req0.headers["dd-api-key"], "test-api-key");
      assertEquals(req0.headers["dd-application-key"], "test-app-key");
      assertEquals(req0.headers["content-type"], "application/json");
      assertExists(req0.body);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
      assertEquals(resources[0].specName, "synthetics_downtime");
      assertEquals(resources[0].name, "new-123");
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "synthetics model: get_synthetics_downtime fetches and writes resource",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server, requests } = startMockDdServer({
      "/downtimes/test-id-123": {
        body: {
          "data": {
            "id": "fixture-123",
            "type": "resource",
            "attributes": {
              "createdAt": "2024-01-15T10:30:00Z",
              "createdBy": "00000000-0000-0000-0000-000000000003",
              "createdByName": "Jane Doe",
              "description": "Scheduled weekly maintenance window.",
              "isEnabled": true,
              "name": "Weekly maintenance",
              "tags": ["team:backend", "env:prod"],
              "testIds": ["abc-def-123", "xyz-uvw-456"],
              "timeSlots": [{
                "duration": 3600,
                "id": "00000000-0000-0000-0000-000000000002",
                "start": {
                  "day": 15,
                  "hour": 10,
                  "minute": 30,
                  "month": 1,
                  "year": 2024,
                },
                "timezone": "Europe/Paris",
              }],
              "updatedAt": "2024-01-15T10:30:00Z",
              "updatedBy": "00000000-0000-0000-0000-000000000003",
              "updatedByName": "Jane Doe",
            },
          },
        },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).get_synthetics_downtime.execute(
        { "downtime_id": "test-id-123" },
        context,
      );
      assertEquals(result.dataHandles.length, 1);

      assertEquals(requests.length >= 1, true);
      const req0 = requests[0];
      assertEquals(req0.method, "GET");
      assertStringIncludes(req0.path, "/downtimes/test-id-123");
      assertEquals(req0.headers["dd-api-key"], "test-api-key");
      assertEquals(req0.headers["dd-application-key"], "test-app-key");

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
      assertEquals(resources[0].specName, "synthetics_downtime");
      assertEquals(resources[0].name, "test-id-123");
      const data = resources[0].data as Record<string, unknown>;
      assertEquals(data.id, "fixture-123");
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "synthetics model: update_synthetics_downtime executes and writes resource",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server, requests } = startMockDdServer({
      "/downtimes/test-id-123": {
        body: {
          "data": {
            "id": "fixture-123",
            "type": "resource",
            "attributes": {
              "createdAt": "2024-01-15T10:30:00Z",
              "createdBy": "00000000-0000-0000-0000-000000000003",
              "createdByName": "Jane Doe",
              "description": "Scheduled weekly maintenance window.",
              "isEnabled": true,
              "name": "Weekly maintenance",
              "tags": ["team:backend", "env:prod"],
              "testIds": ["abc-def-123", "xyz-uvw-456"],
              "timeSlots": [{
                "duration": 3600,
                "id": "00000000-0000-0000-0000-000000000002",
                "start": {
                  "day": 15,
                  "hour": 10,
                  "minute": 30,
                  "month": 1,
                  "year": 2024,
                },
                "timezone": "Europe/Paris",
              }],
              "updatedAt": "2024-01-15T10:30:00Z",
              "updatedBy": "00000000-0000-0000-0000-000000000003",
              "updatedByName": "Jane Doe",
            },
          },
        },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).update_synthetics_downtime.execute({
        "downtime_id": "test-id-123",
        "name": "test-resource",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      assertEquals(requests.length >= 1, true);
      const req0 = requests[0];
      assertEquals(req0.method, "PUT");
      assertStringIncludes(req0.path, "/downtimes/test-id-123");
      assertEquals(req0.headers["dd-api-key"], "test-api-key");
      assertEquals(req0.headers["dd-application-key"], "test-app-key");
      assertEquals(req0.headers["content-type"], "application/json");
      assertExists(req0.body);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
      assertEquals(resources[0].specName, "synthetics_downtime");
      assertEquals(resources[0].name, "test-id-123");
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "synthetics model: delete_synthetics_downtime executes successfully",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server, requests } = startMockDdServer({
      "/downtimes/test-id-123": { body: {}, status: 204 },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).delete_synthetics_downtime.execute(
        { "downtime_id": "test-id-123" },
        context,
      );
      assertEquals(result.dataHandles.length, 0);

      assertEquals(requests.length >= 1, true);
      const req0 = requests[0];
      assertEquals(req0.method, "DELETE");
      assertStringIncludes(req0.path, "/downtimes/test-id-123");
      assertEquals(req0.headers["dd-api-key"], "test-api-key");
      assertEquals(req0.headers["dd-application-key"], "test-app-key");

      const resources = getWrittenResources();
      assertEquals(resources.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "synthetics model: delete_synthetics_suites executes and writes resource",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server, requests } = startMockDdServer({
      "/suites/bulk-delete": {
        body: {
          "data": {
            "id": "fixture-123",
            "type": "resource",
            "attributes": {
              "deleted_at": "test-value",
              "public_id": "test-value",
            },
          },
        },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).delete_synthetics_suites.execute(
        { "name": "test-resource" },
        context,
      );
      assertEquals(result.dataHandles.length, 1);

      assertEquals(requests.length >= 1, true);
      const req0 = requests[0];
      assertEquals(req0.method, "POST");
      assertStringIncludes(req0.path, "/suites/bulk-delete");
      assertEquals(req0.headers["dd-api-key"], "test-api-key");
      assertEquals(req0.headers["dd-application-key"], "test-app-key");
      assertEquals(req0.headers["content-type"], "application/json");
      assertExists(req0.body);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
      assertEquals(resources[0].specName, "synthetics_suites");
      assertExists(resources[0].data);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "synthetics model: get_api_multistep_subtests surfaces API errors",
  // sanitizeResources: false — Deno.serve() listener outlives test scope
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockDdServer({
      "/subtests/test-id-123": {
        body: { errors: [{ status: "500", title: "Internal Error" }] },
        status: 500,
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: {
          "apiKey": "test-api-key",
          "appKey": "test-app-key",
          "site": "us1",
        },
        definition: {
          id: "test-id",
          name: "test-synthetics",
          version: 1,
          tags: {},
        },
      });

      let threw = false;
      try {
        await (model.methods as Record<
          string,
          {
            execute: (
              args: Record<string, unknown>,
              ctx: unknown,
            ) => Promise<{ dataHandles: unknown[] }>;
          }
        >).get_api_multistep_subtests.execute(
          { "public_id": "test-id-123" },
          context,
        );
      } catch (_err) {
        threw = true;
      }
      assertEquals(threw, true);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});
