/**
 * Test generator — produces test files for generated Datadog models.
 *
 * Generates tests matching the swamp extension test pattern:
 * - Model structure tests (type, version, methods, resources)
 * - Mock HTTP server tests (one per method type)
 *
 * Uses mock responses matching DD's response patterns
 * (JSON:API where applicable, flat JSON otherwise).
 */

import type { ClassifiedMethod } from "./method_classifier.ts";
import type { SchemaObject } from "./schema_fetcher.ts";
import type { ServiceConfig } from "../config.ts";

/** Generate a complete test file for a service */
export function generateTestSource(
  config: ServiceConfig,
  methods: ClassifiedMethod[],
  modelFileName: string,
): string {
  const lines: string[] = [];

  lines.push(`// ${config.description} — Tests`);
  lines.push(
    `// Auto-generated by scripts/datadog-codegen — do not edit manually.`,
  );
  lines.push(`// SPDX-License-Identifier: Apache-2.0`);
  lines.push(``);
  lines.push(
    `import { assertEquals, assertExists } from "jsr:@std/assert@1";`,
  );
  lines.push(
    `import { createModelTestContext } from "@systeminit/swamp-testing";`,
  );
  lines.push(`import { model } from "./${modelFileName}.ts";`);
  lines.push(``);

  // Model structure tests
  lines.push(
    `// ---------------------------------------------------------------------------`,
  );
  lines.push(`// Model Export Structure Tests`);
  lines.push(
    `// ---------------------------------------------------------------------------`,
  );
  lines.push(``);

  lines.push(`Deno.test("${config.name} model: has correct type", () => {`);
  lines.push(
    `  assertEquals(model.type, "@webframp/datadog/${config.name}");`,
  );
  lines.push(`});`);
  lines.push(``);

  lines.push(
    `Deno.test("${config.name} model: has valid version format", () => {`,
  );
  lines.push(`  const versionPattern = /^\\d{4}\\.\\d{2}\\.\\d{2}\\.\\d+$/;`);
  lines.push(`  assertEquals(versionPattern.test(model.version), true);`);
  lines.push(`});`);
  lines.push(``);

  lines.push(
    `Deno.test("${config.name} model: has globalArguments with apiKey and appKey", () => {`,
  );
  lines.push(`  assertExists(model.globalArguments);`);
  lines.push(`  const shape = model.globalArguments.shape;`);
  lines.push(`  assertExists(shape.apiKey);`);
  lines.push(`  assertExists(shape.appKey);`);
  lines.push(`  assertExists(shape.site);`);
  lines.push(`});`);
  lines.push(``);

  // Methods existence tests
  lines.push(
    `Deno.test("${config.name} model: has expected methods", () => {`,
  );
  lines.push(`  assertExists(model.methods);`);
  for (const method of methods) {
    lines.push(`  assertExists(model.methods.${method.name});`);
  }
  lines.push(`});`);
  lines.push(``);

  // Resources existence tests — must match model's resource generation logic
  const seenResources = new Set<string>();
  const uniqueResources: string[] = [];
  for (const m of methods) {
    if (m.type === "delete") continue;
    let resourceName: string;
    if (m.type === "list") {
      resourceName = m.name.replace(/^(list|get)_/, "");
    } else {
      resourceName = m.name.replace(/^(get|create|update|action|delete)_/, "");
    }
    if (!seenResources.has(resourceName)) {
      seenResources.add(resourceName);
      uniqueResources.push(resourceName);
    }
  }

  lines.push(
    `Deno.test("${config.name} model: has expected resources", () => {`,
  );
  lines.push(`  assertExists(model.resources);`);
  for (const r of uniqueResources) {
    lines.push(`  assertExists(model.resources["${r}"]);`);
  }
  lines.push(`});`);
  lines.push(``);

  // Mock server + execution tests
  lines.push(
    `// ---------------------------------------------------------------------------`,
  );
  lines.push(`// Mock Datadog API Server`);
  lines.push(
    `// ---------------------------------------------------------------------------`,
  );
  lines.push(``);
  lines.push(generateMockServer());
  lines.push(``);

  // One execution test per method type
  const testedTypes = new Set<string>();
  for (const method of methods) {
    if (testedTypes.has(method.type)) continue;
    testedTypes.add(method.type);
    lines.push(generateExecutionTest(config, method));
    lines.push(``);
  }

  return lines.join("\n");
}

/** Generate the mock HTTP server for Datadog */
function generateMockServer(): string {
  return `function startMockDdServer(
  responses: Record<string, { body: unknown; status?: number }>,
): { url: string; server: Deno.HttpServer } {
  const server = Deno.serve({ port: 0, onListen() {} }, (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    for (const [pattern, { body, status }] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        return Response.json(body, { status: status ?? 200 });
      }
    }

    return Response.json(
      { errors: [{ status: "404", title: "Not found" }] },
      { status: 404 },
    );
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: \`http://localhost:\${addr.port}\`, server };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    // Replace any DD site URL with the mock
    const newUrl = reqUrl
      .replace("https://api.datadoghq.com", mockUrl)
      .replace("https://us3.datadoghq.com", mockUrl)
      .replace("https://us5.datadoghq.com", mockUrl)
      .replace("https://api.datadoghq.eu", mockUrl)
      .replace("https://ap1.datadoghq.com", mockUrl)
      .replace("https://api.ddog-gov.com", mockUrl);
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}`;
}

/** Generate an execution test for a method */
function generateExecutionTest(
  config: ServiceConfig,
  method: ClassifiedMethod,
): string {
  const globalArgs: Record<string, string> = {
    apiKey: "test-api-key",
    appKey: "test-app-key",
    site: "us1",
  };

  const fixture = generateFixture(method);
  const pathPattern = extractPathPattern(method.operation.path);
  const testArgs = buildTestArgs(method);

  if (method.type === "list") {
    const responseBody = method.operation.isJsonApi
      ? { data: [fixture], meta: { page: {} } }
      : { data: [fixture] };
    const argsStr = Object.keys(testArgs).length > 0
      ? JSON.stringify(testArgs)
      : "{}";
    return `Deno.test({
  name: "${config.name} model: ${method.name} fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockDdServer({
      "${pathPattern}": { body: ${JSON.stringify(responseBody)} },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: ${JSON.stringify(globalArgs)},
        definition: { id: "test-id", name: "test-${config.name}", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<string, { execute: (args: Record<string, unknown>, ctx: unknown) => Promise<{ dataHandles: unknown[] }> }>).${method.name}.execute(${argsStr}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});`;
  }

  if (method.type === "get") {
    const responseBody = method.operation.isJsonApi
      ? { data: fixture }
      : fixture;
    return `Deno.test({
  name: "${config.name} model: ${method.name} fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockDdServer({
      "${pathPattern}": { body: ${JSON.stringify(responseBody)} },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: ${JSON.stringify(globalArgs)},
        definition: { id: "test-id", name: "test-${config.name}", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<string, { execute: (args: Record<string, unknown>, ctx: unknown) => Promise<{ dataHandles: unknown[] }> }>).${method.name}.execute(${
      JSON.stringify(testArgs)
    }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});`;
  }

  if (method.type === "create") {
    const responseBody = method.operation.isJsonApi
      ? { data: { ...fixture, id: "new-123" } }
      : { ...fixture, id: "new-123" };
    const createArgs = { ...testArgs, name: "test-resource" };
    return `Deno.test({
  name: "${config.name} model: ${method.name} creates and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockDdServer({
      "${pathPattern}": { body: ${JSON.stringify(responseBody)} },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: ${JSON.stringify(globalArgs)},
        definition: { id: "test-id", name: "test-${config.name}", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<string, { execute: (args: Record<string, unknown>, ctx: unknown) => Promise<{ dataHandles: unknown[] }> }>).${method.name}.execute(${
      JSON.stringify(createArgs)
    }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});`;
  }

  if (method.type === "delete") {
    return `Deno.test({
  name: "${config.name} model: ${method.name} executes successfully",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockDdServer({
      "${pathPattern}": { body: {}, status: 204 },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: ${JSON.stringify(globalArgs)},
        definition: { id: "test-id", name: "test-${config.name}", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<string, { execute: (args: Record<string, unknown>, ctx: unknown) => Promise<{ dataHandles: unknown[] }> }>).${method.name}.execute(${
      JSON.stringify(testArgs)
    }, context);
      assertEquals(result.dataHandles.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});`;
  }

  // Default: action/update
  const responseBody = method.operation.isJsonApi ? { data: fixture } : fixture;
  const actionArgs = { ...testArgs, name: "test-resource" };
  return `Deno.test({
  name: "${config.name} model: ${method.name} executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockDdServer({
      "${pathPattern}": { body: ${JSON.stringify(responseBody)} },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: ${JSON.stringify(globalArgs)},
        definition: { id: "test-id", name: "test-${config.name}", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<string, { execute: (args: Record<string, unknown>, ctx: unknown) => Promise<{ dataHandles: unknown[] }> }>).${method.name}.execute(${
    JSON.stringify(actionArgs)
  }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});`;
}

/** Generate a fixture for test data */
function generateFixture(
  method: ClassifiedMethod,
): Record<string, unknown> {
  const schema = method.operation.responseSchema;

  if (method.operation.isJsonApi) {
    const base: Record<string, unknown> = {
      id: "fixture-123",
      type: "resource",
    };
    if (!schema?.properties) return base;

    const attributes: Record<string, unknown> = {};
    for (const [name, prop] of Object.entries(schema.properties)) {
      if (name === "id" || name === "type") continue;
      attributes[name] = synthesizeValue(prop);
    }
    return { ...base, attributes };
  }

  // Flat fixture
  const result: Record<string, unknown> = { id: "fixture-123" };
  if (!schema?.properties) return result;
  for (const [name, prop] of Object.entries(schema.properties)) {
    result[name] = synthesizeValue(prop);
  }
  return result;
}

/** Synthesize a value matching a schema (for test fixtures) */
function synthesizeValue(schema: SchemaObject, depth = 0): unknown {
  if (depth > 3) return null;

  if (schema.example !== undefined) return schema.example;
  if (schema.enum) return schema.enum[0];

  switch (schema.type) {
    case "string":
      if (schema.format === "date-time") return "2024-01-01T00:00:00Z";
      if (schema.format === "uri" || schema.format === "url") {
        return "https://example.com";
      }
      return "test-value";
    case "number":
    case "integer":
      return schema.minimum ?? 1;
    case "boolean":
      return true;
    case "array":
      return [];
    case "object":
      if (schema.properties) {
        const obj: Record<string, unknown> = {};
        for (const [name, prop] of Object.entries(schema.properties)) {
          obj[name] = synthesizeValue(prop, depth + 1);
        }
        return obj;
      }
      return {};
    default:
      return null;
  }
}

/** Extract path pattern for mock server matching */
function extractPathPattern(path: string): string {
  // Remove /api/v2 prefix and replace params with test values
  let result = path.replace(/^\/api\/v2/, "");
  result = result.replace(/\{[^}]+\}/g, "test-id-123");
  result = result.replace(/\/$/, "");
  // Take the last meaningful segment for matching
  const segments = result.split("/").filter(Boolean);
  if (segments.length >= 2) {
    return "/" + segments.slice(-2).join("/");
  }
  return result || "/";
}

/** Build test args that include path param values */
function buildTestArgs(method: ClassifiedMethod): Record<string, unknown> {
  const args: Record<string, unknown> = {};
  for (const p of method.operation.pathParams) {
    const name = p.name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/_+/g, "_")
      .replace(/^_|_$/g, "");
    args[name] = "test-id-123";
  }
  return args;
}
