/**
 * Cloudflare Email Routing — rules, addresses, catch-all, DNS setup
 *
 * Auto-generated by scripts/cloudflare-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: AGPL-3.0-or-later WITH Swamp-Extension-Exception

import { z } from "npm:zod@4.4.3";
import { cfApi, cfApiPaginated } from "./_lib/api.ts";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiToken: z.string().meta({ sensitive: true }).describe(
    "Cloudflare API token",
  ),
  zoneId: z.string().describe("Cloudflare zone ID"),
});

const GetDmarcReportsStatusSchema = z.object({
  approved_sources: z.array(z.unknown()).optional().describe(
    "List of approved sending sources (omitted when empty)",
  ),
  created: z.string().optional().describe("Deprecated, use created_at"),
  created_at: z.string().optional().describe("Creation timestamp"),
  enabled: z.boolean().optional().describe("Whether DMARC reports are enabled"),
  modified: z.string().optional().describe("Deprecated, use modified_at"),
  modified_at: z.string().optional().describe("Last modification timestamp"),
  records: z.unknown().optional(),
  rua_prefix: z.string().optional().describe(
    "Prefix for DMARC RUA addresses (32-char hex string)",
  ),
  skip_wizard: z.boolean().optional().describe(
    "Whether to skip the setup wizard",
  ),
  status: z.unknown().optional(),
  tag: z.string().optional().describe("Use `zone_id` instead"),
  zone_id: z.string().optional().describe("Zone identifier"),
});

const UpdateConfigureDmarcReportsSchema = z.object({
  approved_sources: z.array(z.unknown()).optional().describe(
    "List of approved sending sources (omitted when empty)",
  ),
  created: z.string().optional().describe("Deprecated, use created_at"),
  created_at: z.string().optional().describe("Creation timestamp"),
  enabled: z.boolean().optional().describe("Whether DMARC reports are enabled"),
  modified: z.string().optional().describe("Deprecated, use modified_at"),
  modified_at: z.string().optional().describe("Last modification timestamp"),
  records: z.unknown().optional(),
  rua_prefix: z.string().optional().describe(
    "Prefix for DMARC RUA addresses (32-char hex string)",
  ),
  skip_wizard: z.boolean().optional().describe(
    "Whether to skip the setup wizard",
  ),
  status: z.unknown().optional(),
  tag: z.string().optional().describe("Use `zone_id` instead"),
  zone_id: z.string().optional().describe("Zone identifier"),
});

const GetInspectSpfSchema = z.object({
  components: z.array(z.unknown()).describe(
    "Parsed SPF components (mechanisms)",
  ),
  domain: z.string().describe("Domain being inspected"),
  errors: z.array(z.unknown()).optional().describe(
    "All errors encountered during inspection, collected from the entire tree. This includes errors fr...",
  ),
  record: z.string().describe("Raw SPF record content"),
  total_lookups: z.number().int().describe(
    "Total number of DNS lookups performed across all includes",
  ),
});

const GetEmailRoutingSettingsSchema = z.object({
  created: z.unknown().optional(),
  enabled: z.unknown(),
  id: z.unknown(),
  modified: z.unknown().optional(),
  name: z.unknown(),
  skip_wizard: z.unknown().optional(),
  status: z.unknown().optional(),
  support_subaddress: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const UpdateEmailRoutingSettingsReplaceEmailRoutingSettingsSchema = z.object({
  created: z.unknown().optional(),
  enabled: z.unknown(),
  id: z.unknown(),
  modified: z.unknown().optional(),
  name: z.unknown(),
  skip_wizard: z.unknown().optional(),
  status: z.unknown().optional(),
  support_subaddress: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const GetEmailRoutingSettingsEmailRoutingDnsSettingsSchema = z.union([
  z.unknown(),
  z.unknown(),
]);

const CreateEmailRoutingSettingsEnableEmailRoutingDnsSchema = z.object({
  created: z.unknown().optional(),
  enabled: z.unknown(),
  id: z.unknown(),
  modified: z.unknown().optional(),
  name: z.unknown(),
  skip_wizard: z.unknown().optional(),
  status: z.unknown().optional(),
  support_subaddress: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const UpdateEmailRoutingSettingsUnlockEmailRoutingDnsSchema = z.object({
  created: z.unknown().optional(),
  enabled: z.unknown(),
  id: z.unknown(),
  modified: z.unknown().optional(),
  name: z.unknown(),
  skip_wizard: z.unknown().optional(),
  status: z.unknown().optional(),
  support_subaddress: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const RoutingRulesItemSchema = z.object({
  actions: z.unknown().optional(),
  enabled: z.unknown().optional(),
  id: z.unknown().optional(),
  matchers: z.unknown().optional(),
  name: z.unknown().optional(),
  priority: z.unknown().optional(),
  source: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const ListRoutingRulesSchema = z.object({
  items: z.array(RoutingRulesItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateRoutingRuleSchema = z.object({
  actions: z.unknown().optional(),
  enabled: z.unknown().optional(),
  id: z.unknown().optional(),
  matchers: z.unknown().optional(),
  name: z.unknown().optional(),
  priority: z.unknown().optional(),
  source: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const GetCatchAllRuleSchema = z.object({
  actions: z.unknown().optional(),
  enabled: z.unknown().optional(),
  id: z.unknown().optional(),
  matchers: z.unknown().optional(),
  name: z.unknown().optional(),
  source: z.unknown().optional(),
  tag: z.unknown().optional(),
});

const GetPubliclistsuppressionzoneroutingItemSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  expires_at: z.string().nullable(),
  id: z.string(),
  reason: z.string(),
  zones: z.array(z.string()).optional(),
});

const GetPubliclistsuppressionzoneroutingSchema = z.object({
  items: z.array(GetPubliclistsuppressionzoneroutingItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreatePostPublicnewsuppressionzoneroutingSchema = z.object({
  id: z.string(),
});

const GetPublicgetsuppressionzoneroutingSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  expires_at: z.string().nullable(),
  id: z.string(),
  reason: z.string(),
  zones: z.array(z.string()).optional(),
});

const SendingSubdomainsItemSchema = z.object({
  created: z.unknown().optional(),
  dkim_selector: z.string().optional().describe(
    "The DKIM selector used for email signing.",
  ),
  enabled: z.boolean().describe(
    "Whether Email Sending is enabled on this subdomain.",
  ),
  modified: z.unknown().optional(),
  name: z.string().describe("The subdomain domain name."),
  preview_enabled: z.boolean().optional().describe(
    "Whether sent messages from this subdomain can be previewed in the activity log.",
  ),
  return_path_domain: z.string().optional().describe(
    "The return-path domain used for bounce handling.",
  ),
  tag: z.unknown(),
});

const ListSendingSubdomainsSchema = z.object({
  items: z.array(SendingSubdomainsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateSendingSubdomainSchema = z.object({
  created: z.unknown().optional(),
  dkim_selector: z.string().optional().describe(
    "The DKIM selector used for email signing.",
  ),
  enabled: z.boolean().describe(
    "Whether Email Sending is enabled on this subdomain.",
  ),
  modified: z.unknown().optional(),
  name: z.string().describe("The subdomain domain name."),
  preview_enabled: z.boolean().optional().describe(
    "Whether sent messages from this subdomain can be previewed in the activity log.",
  ),
  return_path_domain: z.string().optional().describe(
    "The return-path domain used for bounce handling.",
  ),
  tag: z.unknown(),
});

const CreateEmailSendingSubdomainsPreviewSendingSubdomainSchema = z.object({
  errors: z.array(z.unknown()).optional().describe(
    "DNS issues detected — missing records that will be created and conflicts with existing records.",
  ),
  records: z.array(z.unknown()).optional().describe(
    "DNS records that would be created for the subdomain.",
  ),
});

const GetSendingSubdomainDnsItemSchema = z.object({
  content: z.string().optional().describe("DNS record content."),
  name: z.string().max(255).optional().describe(
    "DNS record name (or @ for the zone apex).",
  ),
  priority: z.number().min(0).max(65535).optional().describe(
    "Required for MX, SRV and URI records. Unused by other record types. Records with lower priorities...",
  ),
  ttl: z.union([z.number().min(1).max(86400), z.union([z.literal(1)])])
    .optional().describe(
      "Time to live, in seconds, of the DNS record. Must be between 60 and 86400, or 1 for 'automatic'.",
    ),
  type: z.enum([
    "A",
    "AAAA",
    "CNAME",
    "HTTPS",
    "TXT",
    "SRV",
    "LOC",
    "MX",
    "NS",
    "CERT",
    "DNSKEY",
    "DS",
    "NAPTR",
    "SMIMEA",
    "SSHFP",
    "SVCB",
    "TLSA",
    "URI",
  ]).optional().describe("DNS record type."),
});

const GetSendingSubdomainDnsSchema = z.object({
  items: z.array(GetSendingSubdomainDnsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const EmailSendingSubdomainsFixSendingSubdomainDnsSchema = z.object({
  errors: z.array(z.unknown()).optional().describe(
    "DNS issues detected against the current zone state.",
  ),
  records: z.array(z.unknown()).optional().describe(
    "Desired DNS records for the subdomain.",
  ),
  status: z.enum(["ready", "unconfigured", "unlocked", "misconfigured"])
    .optional().describe(
      "Aggregated DNS state for the subdomain. `unlocked` means desired records exist with correct conte...",
    ),
});

const GetSendingSubdomainDnsStatusSchema = z.object({
  errors: z.array(z.unknown()).optional().describe(
    "DNS issues detected against the current zone state.",
  ),
  records: z.array(z.unknown()).optional().describe(
    "Desired DNS records for the subdomain.",
  ),
  status: z.enum(["ready", "unconfigured", "unlocked", "misconfigured"])
    .optional().describe(
      "Aggregated DNS state for the subdomain. `unlocked` means desired records exist with correct conte...",
    ),
});

const GetPubliclistsuppressionzonesendingItemSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  expires_at: z.string().nullable(),
  id: z.string(),
  reason: z.string(),
  zones: z.array(z.string()).optional(),
});

const GetPubliclistsuppressionzonesendingSchema = z.object({
  items: z.array(GetPubliclistsuppressionzonesendingItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreatePostPublicnewsuppressionzonesendingSchema = z.object({
  id: z.string(),
});

const GetPublicgetsuppressionzonesendingSchema = z.object({
  created_at: z.string(),
  email: z.string(),
  expires_at: z.string().nullable(),
  id: z.string(),
  reason: z.string(),
  zones: z.array(z.string()).optional(),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Cloudflare Email Routing — rules, addresses, catch-all, DNS setup */
export const model = {
  type: "@webframp/cloudflare/email-routing",
  version: "2026.07.19.1",
  globalArguments: GlobalArgsSchema,

  upgrades: [],

  resources: {
    "dmarc_reports_status": {
      description: "Get DMARC Report Status",
      schema: GetDmarcReportsStatusSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "configure_dmarc_reports": {
      description: "Configure DMARC Reports",
      schema: UpdateConfigureDmarcReportsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "inspect_spf": {
      description: "Inspect SPF Record",
      schema: GetInspectSpfSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "email_routing_settings": {
      description: "Get Email Routing settings",
      schema: GetEmailRoutingSettingsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "email_routing_settings_replace_email_routing_settings": {
      description: "Update Email Routing settings",
      schema: UpdateEmailRoutingSettingsReplaceEmailRoutingSettingsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "email_routing_settings_email_routing_dns_settings": {
      description: "Email Routing - DNS settings",
      schema: GetEmailRoutingSettingsEmailRoutingDnsSettingsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "email_routing_settings_enable_email_routing_dns": {
      description: "Enable Email Routing",
      schema: CreateEmailRoutingSettingsEnableEmailRoutingDnsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "email_routing_settings_unlock_email_routing_dns": {
      description: "Unlock Email Routing",
      schema: UpdateEmailRoutingSettingsUnlockEmailRoutingDnsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "routing_rules": {
      description: "List routing rules",
      schema: ListRoutingRulesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "routing_rule": {
      description: "Create routing rule",
      schema: CreateRoutingRuleSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "catch_all_rule": {
      description: "Get catch-all rule",
      schema: GetCatchAllRuleSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "get_publiclistsuppressionzonerouting": {
      description: "List zone email suppressions",
      schema: GetPubliclistsuppressionzoneroutingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "post_publicnewsuppressionzonerouting": {
      description: "Create zone email suppression",
      schema: CreatePostPublicnewsuppressionzoneroutingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "publicgetsuppressionzonerouting": {
      description: "Get zone email suppression",
      schema: GetPublicgetsuppressionzoneroutingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "sending_subdomains": {
      description: "List sending subdomains",
      schema: ListSendingSubdomainsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "sending_subdomain": {
      description: "Create a sending subdomain",
      schema: CreateSendingSubdomainSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "email_sending_subdomains_preview_sending_subdomain": {
      description: "Preview sending subdomain DNS",
      schema: CreateEmailSendingSubdomainsPreviewSendingSubdomainSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "get_sending_subdomain_dns": {
      description: "Get sending subdomain DNS records",
      schema: GetSendingSubdomainDnsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "email_sending_subdomains_fix_sending_subdomain_dns": {
      description: "Fix sending subdomain DNS records",
      schema: EmailSendingSubdomainsFixSendingSubdomainDnsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "sending_subdomain_dns_status": {
      description: "Get sending subdomain DNS status",
      schema: GetSendingSubdomainDnsStatusSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "get_publiclistsuppressionzonesending": {
      description: "List zone email suppressions",
      schema: GetPubliclistsuppressionzonesendingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "post_publicnewsuppressionzonesending": {
      description: "Create zone email suppression",
      schema: CreatePostPublicnewsuppressionzonesendingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "publicgetsuppressionzonesending": {
      description: "Get zone email suppression",
      schema: GetPublicgetsuppressionzonesendingSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
  },

  methods: {
    get_dmarc_reports_status: {
      description: "Get DMARC Report Status",
      arguments: z.object({}),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/auth/dmarc-reports`,
        );

        const handle = await context.writeResource(
          "dmarc_reports_status",
          "latest",
          result,
        );
        context.logger.info("Fetched dmarc_reports_status", {});
        return { dataHandles: [handle] };
      },
    },
    update_configure_dmarc_reports: {
      description: "Configure DMARC Reports",
      arguments: z.object({
        enabled: z.boolean().nullable().optional().describe(
          "Enable or disable DMARC reports for this zone",
        ),
        skip_wizard: z.boolean().nullable().optional().describe(
          "Skip the DMARC setup wizard",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PATCH",
          `/zones/${zoneId}/email/auth/dmarc-reports`,
          body,
        );

        const handle = await context.writeResource(
          "configure_dmarc_reports",
          "updated",
          result,
        );
        context.logger.info("Updated configure_dmarc_reports", {});
        return { dataHandles: [handle] };
      },
    },
    get_inspect_spf: {
      description: "Inspect SPF Record",
      arguments: z.object({}),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/auth/spf/inspect`,
        );

        const handle = await context.writeResource(
          "inspect_spf",
          "latest",
          result,
        );
        context.logger.info("Fetched inspect_spf", {});
        return { dataHandles: [handle] };
      },
    },
    get_email_routing_settings: {
      description: "Get Email Routing settings",
      arguments: z.object({}),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/routing`,
        );

        const handle = await context.writeResource(
          "email_routing_settings",
          "latest",
          result,
        );
        context.logger.info("Fetched email_routing_settings", {});
        return { dataHandles: [handle] };
      },
    },
    update_email_routing_settings_replace_email_routing_settings: {
      description: "Update Email Routing settings",
      arguments: z.object({
        enabled: z.union([z.literal(true), z.literal(false)]).optional()
          .describe(
            "State of your zone Email Routing settings. No-op on this endpoint - use `POST...",
          ),
        skip_wizard: z.union([z.literal(true), z.literal(false)]).optional()
          .describe(
            "Flag to check if the user skipped the configuration wizard.",
          ),
        support_subaddress: z.union([z.literal(true), z.literal(false)])
          .optional().describe(
            "Whether subaddressing (plus-addressing) is honored when matching incoming mai...",
          ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PUT",
          `/zones/${zoneId}/email/routing`,
          body,
        );

        const handle = await context.writeResource(
          "email_routing_settings_replace_email_routing_settings",
          "updated",
          result,
        );
        context.logger.info(
          "Updated email_routing_settings_replace_email_routing_settings",
          {},
        );
        return { dataHandles: [handle] };
      },
    },
    update_email_routing_settings: {
      description: "Update Email Routing settings",
      arguments: z.object({
        enabled: z.union([z.literal(true), z.literal(false)]).optional()
          .describe(
            "State of your zone Email Routing settings. No-op on this endpoint - use `POST...",
          ),
        skip_wizard: z.union([z.literal(true), z.literal(false)]).optional()
          .describe(
            "Flag to check if the user skipped the configuration wizard.",
          ),
        support_subaddress: z.union([z.literal(true), z.literal(false)])
          .optional().describe(
            "Whether subaddressing (plus-addressing) is honored when matching incoming mai...",
          ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PATCH",
          `/zones/${zoneId}/email/routing`,
          body,
        );

        const handle = await context.writeResource(
          "email_routing_settings",
          "updated",
          result,
        );
        context.logger.info("Updated email_routing_settings", {});
        return { dataHandles: [handle] };
      },
    },
    get_email_routing_settings_email_routing_dns_settings: {
      description: "Email Routing - DNS settings",
      arguments: z.object({
        subdomain: z.string().optional(),
      }),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/routing/dns`,
        );

        const handle = await context.writeResource(
          "email_routing_settings_email_routing_dns_settings",
          "latest",
          result,
        );
        context.logger.info(
          "Fetched email_routing_settings_email_routing_dns_settings",
          {},
        );
        return { dataHandles: [handle] };
      },
    },
    create_email_routing_settings_enable_email_routing_dns: {
      description: "Enable Email Routing",
      arguments: z.object({
        name: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/routing/dns`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "email_routing_settings_enable_email_routing_dns",
          id,
          result,
        );
        context.logger.info(
          "Created email_routing_settings_enable_email_routing_dns {id}",
          { id },
        );
        return { dataHandles: [handle] };
      },
    },
    update_email_routing_settings_unlock_email_routing_dns: {
      description: "Unlock Email Routing",
      arguments: z.object({
        name: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PATCH",
          `/zones/${zoneId}/email/routing/dns`,
          body,
        );

        const handle = await context.writeResource(
          "email_routing_settings_unlock_email_routing_dns",
          "updated",
          result,
        );
        context.logger.info(
          "Updated email_routing_settings_unlock_email_routing_dns",
          {},
        );
        return { dataHandles: [handle] };
      },
    },
    delete_email_routing_settings_disable_email_routing_dns: {
      description: "Disable Email Routing",
      arguments: z.object({
        name: z.unknown().optional(),
      }),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        await cfApi(
          apiToken,
          "DELETE",
          `/zones/${zoneId}/email/routing/dns`,
        );

        context.logger.info("Deleted resource {id}", { id: "unknown" });
        return { dataHandles: [] };
      },
    },
    list_routing_rules: {
      description: "List routing rules",
      arguments: z.object({
        page: z.number().optional(),
        per_page: z.number().optional(),
        enabled: z.boolean().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "per_page"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await cfApiPaginated<
          Record<string, unknown>
        >(
          apiToken,
          `/zones/${zoneId}/email/routing/rules`,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource("routing_rules", "main", {
          items: results,
          truncated,
          fetchedAt: new Date().toISOString(),
        });

        context.logger.info("Found {count} routing_rules", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_routing_rule: {
      description: "Create routing rule",
      arguments: z.object({
        actions: z.unknown(),
        enabled: z.unknown().optional(),
        matchers: z.unknown(),
        name: z.unknown().optional(),
        owner_worker_tag: z.unknown().optional(),
        priority: z.unknown().optional(),
        source: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/routing/rules`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource("routing_rule", id, result);
        context.logger.info("Created routing_rule {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_catch_all_rule: {
      description: "Get catch-all rule",
      arguments: z.object({}),
      execute: async (
        _args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/routing/rules/catch_all`,
        );

        const handle = await context.writeResource(
          "catch_all_rule",
          "latest",
          result,
        );
        context.logger.info("Fetched catch_all_rule", {});
        return { dataHandles: [handle] };
      },
    },
    update_catch_all_rule: {
      description: "Update catch-all rule",
      arguments: z.object({
        actions: z.unknown(),
        enabled: z.unknown().optional(),
        matchers: z.unknown(),
        name: z.unknown().optional(),
        owner_worker_tag: z.unknown().optional(),
        source: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PUT",
          `/zones/${zoneId}/email/routing/rules/catch_all`,
          body,
        );

        const handle = await context.writeResource(
          "catch_all_rule",
          "updated",
          result,
        );
        context.logger.info("Updated catch_all_rule", {});
        return { dataHandles: [handle] };
      },
    },
    get_routing_rule: {
      description: "Get routing rule",
      arguments: z.object({
        rule_identifier: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/routing/rules/${args.rule_identifier}`,
        );

        const handle = await context.writeResource(
          "routing_rule",
          String(args.rule_identifier),
          result,
        );
        context.logger.info("Fetched routing_rule", {});
        return { dataHandles: [handle] };
      },
    },
    update_routing_rule: {
      description: "Update routing rule",
      arguments: z.object({
        rule_identifier: z.string(),
        actions: z.unknown(),
        enabled: z.unknown().optional(),
        matchers: z.unknown(),
        name: z.unknown().optional(),
        owner_worker_tag: z.unknown().optional(),
        priority: z.unknown().optional(),
        source: z.unknown().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const pathKeys = new Set(["rule_identifier"]);
        for (const [k, v] of Object.entries(args)) {
          if (!pathKeys.has(k)) body[k] = v;
        }

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PUT",
          `/zones/${zoneId}/email/routing/rules/${args.rule_identifier}`,
          body,
        );

        const handle = await context.writeResource(
          "routing_rule",
          String(args.rule_identifier),
          result,
        );
        context.logger.info("Updated routing_rule", {});
        return { dataHandles: [handle] };
      },
    },
    delete_routing_rule: {
      description: "Delete routing rule",
      arguments: z.object({
        rule_identifier: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        await cfApi(
          apiToken,
          "DELETE",
          `/zones/${zoneId}/email/routing/rules/${args.rule_identifier}`,
        );

        context.logger.info("Deleted resource {id}", {
          id: args.rule_identifier,
        });
        return { dataHandles: [] };
      },
    },
    get_publiclistsuppressionzonerouting: {
      description: "List zone email suppressions",
      arguments: z.object({
        page: z.number().optional(),
        per_page: z.number().optional(),
        order: z.enum(["email", "expires_at", "created_at"]).optional(),
        direction: z.enum(["asc", "desc"]).optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "per_page"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await cfApiPaginated<
          Record<string, unknown>
        >(
          apiToken,
          `/zones/${zoneId}/email/routing/suppression`,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "get_publiclistsuppressionzonerouting",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info(
          "Found {count} get_publiclistsuppressionzonerouting",
          { count: results.length },
        );
        return { dataHandles: [handle] };
      },
    },
    create_post_publicnewsuppressionzonerouting: {
      description: "Create zone email suppression",
      arguments: z.object({
        email: z.string(),
        expires_at: z.string().nullable().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/routing/suppression`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "post_publicnewsuppressionzonerouting",
          id,
          result,
        );
        context.logger.info(
          "Created post_publicnewsuppressionzonerouting {id}",
          { id },
        );
        return { dataHandles: [handle] };
      },
    },
    get_publicgetsuppressionzonerouting: {
      description: "Get zone email suppression",
      arguments: z.object({
        suppression_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/routing/suppression/${args.suppression_id}`,
        );

        const handle = await context.writeResource(
          "publicgetsuppressionzonerouting",
          String(args.suppression_id),
          result,
        );
        context.logger.info("Fetched publicgetsuppressionzonerouting", {});
        return { dataHandles: [handle] };
      },
    },
    delete_publicdeletesuppressionzonerouting: {
      description: "Delete zone email suppression",
      arguments: z.object({
        suppression_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        await cfApi(
          apiToken,
          "DELETE",
          `/zones/${zoneId}/email/routing/suppression/${args.suppression_id}`,
        );

        context.logger.info("Deleted resource {id}", {
          id: args.suppression_id,
        });
        return { dataHandles: [] };
      },
    },
    list_sending_subdomains: {
      description: "List sending subdomains",
      arguments: z.object({}),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "per_page"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await cfApiPaginated<
          Record<string, unknown>
        >(
          apiToken,
          `/zones/${zoneId}/email/sending/subdomains`,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "sending_subdomains",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} sending_subdomains", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_sending_subdomain: {
      description: "Create a sending subdomain",
      arguments: z.object({
        name: z.string().describe(
          "The subdomain name. Must be within the zone.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/sending/subdomains`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "sending_subdomain",
          id,
          result,
        );
        context.logger.info("Created sending_subdomain {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    create_email_sending_subdomains_preview_sending_subdomain: {
      description: "Preview sending subdomain DNS",
      arguments: z.object({
        name: z.string().describe(
          "The subdomain name. Must be within the zone.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/sending/subdomains/preview`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "email_sending_subdomains_preview_sending_subdomain",
          id,
          result,
        );
        context.logger.info(
          "Created email_sending_subdomains_preview_sending_subdomain {id}",
          { id },
        );
        return { dataHandles: [handle] };
      },
    },
    get_sending_subdomain: {
      description: "Get a sending subdomain",
      arguments: z.object({
        subdomain_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/sending/subdomains/${args.subdomain_id}`,
        );

        const handle = await context.writeResource(
          "sending_subdomain",
          String(args.subdomain_id),
          result,
        );
        context.logger.info("Fetched sending_subdomain", {});
        return { dataHandles: [handle] };
      },
    },
    update_sending_subdomain: {
      description: "Update a sending subdomain",
      arguments: z.object({
        subdomain_id: z.string(),
        preview_enabled: z.boolean().describe(
          "Whether sent messages from this subdomain can be previewed in the activity log.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body: Record<string, unknown> = {};
        const pathKeys = new Set(["subdomain_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!pathKeys.has(k)) body[k] = v;
        }

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "PATCH",
          `/zones/${zoneId}/email/sending/subdomains/${args.subdomain_id}`,
          body,
        );

        const handle = await context.writeResource(
          "sending_subdomain",
          String(args.subdomain_id),
          result,
        );
        context.logger.info("Updated sending_subdomain", {});
        return { dataHandles: [handle] };
      },
    },
    delete_sending_subdomain: {
      description: "Delete a sending subdomain",
      arguments: z.object({
        subdomain_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        await cfApi(
          apiToken,
          "DELETE",
          `/zones/${zoneId}/email/sending/subdomains/${args.subdomain_id}`,
        );

        context.logger.info("Deleted resource {id}", { id: args.subdomain_id });
        return { dataHandles: [] };
      },
    },
    get_sending_subdomain_dns: {
      description: "Get sending subdomain DNS records",
      arguments: z.object({
        subdomain_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["subdomain_id", "page", "per_page"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await cfApiPaginated<
          Record<string, unknown>
        >(
          apiToken,
          `/zones/${zoneId}/email/sending/subdomains/${args.subdomain_id}/dns`,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "get_sending_subdomain_dns",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} get_sending_subdomain_dns", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    email_sending_subdomains_fix_sending_subdomain_dns: {
      description: "Fix sending subdomain DNS records",
      arguments: z.object({
        subdomain_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/sending/subdomains/${args.subdomain_id}/dns`,
        );

        const handle = await context.writeResource(
          "email_sending_subdomains_fix_sending_subdomain_dns",
          "latest",
          result,
        );
        context.logger.info(
          "Executed email_sending_subdomains_fix_sending_subdomain_dns",
          {},
        );
        return { dataHandles: [handle] };
      },
    },
    get_sending_subdomain_dns_status: {
      description: "Get sending subdomain DNS status",
      arguments: z.object({
        subdomain_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/sending/subdomains/${args.subdomain_id}/dns/status`,
        );

        const handle = await context.writeResource(
          "sending_subdomain_dns_status",
          String(args.subdomain_id),
          result,
        );
        context.logger.info("Fetched sending_subdomain_dns_status", {});
        return { dataHandles: [handle] };
      },
    },
    get_publiclistsuppressionzonesending: {
      description: "List zone email suppressions",
      arguments: z.object({
        page: z.number().optional(),
        per_page: z.number().optional(),
        order: z.enum(["email", "expires_at", "created_at"]).optional(),
        direction: z.enum(["asc", "desc"]).optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set(["page", "per_page"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
        }

        const { results, truncated } = await cfApiPaginated<
          Record<string, unknown>
        >(
          apiToken,
          `/zones/${zoneId}/email/sending/suppression`,
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "get_publiclistsuppressionzonesending",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info(
          "Found {count} get_publiclistsuppressionzonesending",
          { count: results.length },
        );
        return { dataHandles: [handle] };
      },
    },
    create_post_publicnewsuppressionzonesending: {
      description: "Create zone email suppression",
      arguments: z.object({
        email: z.string(),
        expires_at: z.string().nullable().optional(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;

        const body = args;

        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "POST",
          `/zones/${zoneId}/email/sending/suppression`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "post_publicnewsuppressionzonesending",
          id,
          result,
        );
        context.logger.info(
          "Created post_publicnewsuppressionzonesending {id}",
          { id },
        );
        return { dataHandles: [handle] };
      },
    },
    get_publicgetsuppressionzonesending: {
      description: "Get zone email suppression",
      arguments: z.object({
        suppression_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        const result = await cfApi<Record<string, unknown>>(
          apiToken,
          "GET",
          `/zones/${zoneId}/email/sending/suppression/${args.suppression_id}`,
        );

        const handle = await context.writeResource(
          "publicgetsuppressionzonesending",
          String(args.suppression_id),
          result,
        );
        context.logger.info("Fetched publicgetsuppressionzonesending", {});
        return { dataHandles: [handle] };
      },
    },
    delete_publicdeletesuppressionzonesending: {
      description: "Delete zone email suppression",
      arguments: z.object({
        suppression_id: z.string(),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiToken, zoneId } = context.globalArgs;
        await cfApi(
          apiToken,
          "DELETE",
          `/zones/${zoneId}/email/sending/suppression/${args.suppression_id}`,
        );

        context.logger.info("Deleted resource {id}", {
          id: args.suppression_id,
        });
        return { dataHandles: [] };
      },
    },
  },
};
