/**
 * Datadog On-Call — on-call schedules, escalation policies, and routing
 *
 * Auto-generated by scripts/datadog-codegen — do not edit manually.
 *
 * @module
 */
// SPDX-License-Identifier: AGPL-3.0-or-later WITH Swamp-Extension-Exception

import { z } from "npm:zod@4.4.3";
import { ddApi, ddApiPaginated } from "./_lib/api.ts";

// =============================================================================
// Schemas
// =============================================================================

const GlobalArgsSchema = z.object({
  apiKey: z.string().meta({ sensitive: true }).describe(
    "Datadog API key (DD-API-KEY)",
  ),
  appKey: z.string().meta({ sensitive: true }).describe(
    "Datadog application key (DD-APPLICATION-KEY)",
  ),
  site: z.enum(["us1", "us3", "us5", "eu1", "ap1", "us1-fed"]).default("us1")
    .describe("Datadog site"),
});

const CreateOnCallEscalationPolicySchema = z.object({
  id: z.string().describe(
    "Specifies the unique identifier of the escalation policy.",
  ),
  type: z.enum(["policies"]).optional().describe(
    "Indicates that the resource is of type `policies`.",
  ),
  name: z.string().min(1).describe(
    "Specifies the name of the escalation policy.",
  ),
  resolve_page_on_policy_end: z.boolean().optional().describe(
    "Indicates whether the page is automatically resolved when the policy ends.",
  ),
  retries: z.number().int().min(0).max(10).optional().describe(
    "Specifies how many times the escalation sequence is retried if there is no response.",
  ),
  steps_id: z.string().optional().describe("Related steps ID"),
  teams_id: z.string().optional().describe("Related teams ID"),
});

const CreateOnCallScheduleSchema = z.object({
  id: z.string().describe("The schedule's unique identifier."),
  type: z.enum(["schedules"]).optional().describe("Schedules resource type."),
  name: z.string().optional().describe("A short name for the schedule."),
  tags: z.array(z.string()).optional().describe(
    "A list of tags associated with the schedule.",
  ),
  time_zone: z.string().optional().describe(
    "The time zone in which this schedule operates.",
  ),
  layers_id: z.string().optional().describe("Related layers ID"),
  teams_id: z.string().optional().describe("Related teams ID"),
});

const GetScheduleOnCallRespondersSchema = z.object({
  id: z.string().describe(
    "Unique identifier of this on-call responders lookup.",
  ),
  type: z.enum(["schedule_oncall_responders"]).optional().describe(
    "Represents the resource type for a schedule's grouped on-call responders across the previous, cur...",
  ),
  scheduled_at: z.string().optional().describe(
    "The timestamp the responders were resolved at.",
  ),
  responders_id: z.string().optional().describe("Related responders ID"),
  schedule_id: z.string().optional().describe("Related schedule ID"),
});

const GetTeamOnCallUsersSchema = z.object({
  id: z.string().optional().describe(
    "Unique identifier of the on-call responder configuration.",
  ),
  relationships: z.unknown().optional(),
  type: z.unknown(),
});

const GetOnCallTeamRoutingRulesSchema = z.object({
  id: z.string().optional().describe(
    "Specifies the unique identifier of this team routing rules record.",
  ),
  relationships: z.unknown().optional(),
  type: z.unknown(),
});

const SetOnCallTeamRoutingRulesSchema = z.object({
  id: z.string().optional().describe(
    "Specifies the unique identifier of this team routing rules record.",
  ),
  relationships: z.unknown().optional(),
  type: z.unknown(),
});

const UserNotificationChannelsItemSchema = z.object({
  id: z.string().describe("Unique identifier for the channel"),
  type: z.enum(["notification_channels"]).optional().describe(
    "Indicates that the resource is of type 'notification_channels'.",
  ),
  active: z.boolean().optional().describe(
    "Whether the notification channel is currently active.",
  ),
  config: z.union([z.unknown(), z.unknown(), z.unknown()]).optional().describe(
    "Defines the configuration for an On-Call notification channel",
  ),
});

const ListUserNotificationChannelsSchema = z.object({
  items: z.array(UserNotificationChannelsItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateUserNotificationChannelSchema = z.object({
  id: z.string().describe("Unique identifier for the channel"),
  type: z.enum(["notification_channels"]).optional().describe(
    "Indicates that the resource is of type 'notification_channels'.",
  ),
  active: z.boolean().optional().describe(
    "Whether the notification channel is currently active.",
  ),
  config: z.union([z.unknown(), z.unknown(), z.unknown()]).optional().describe(
    "Defines the configuration for an On-Call notification channel",
  ),
});

const UserNotificationRulesItemSchema = z.object({
  id: z.string().describe("Unique identifier for the rule"),
  type: z.enum(["notification_rules"]).optional().describe(
    "Indicates that the resource is of type 'notification_rules'.",
  ),
  category: z.enum(["high_urgency", "low_urgency"]).optional().describe(
    "Specifies the category a notification rule will apply to",
  ),
  channel_settings: z.unknown().optional().describe(
    "Defines the configuration for a channel associated with a notification rule",
  ),
  delay_minutes: z.number().int().optional().describe(
    "The number of minutes that will elapse before this rule is evaluated. 0 indicates immediate evalu...",
  ),
  channel_id: z.string().optional().describe("Related channel ID"),
});

const ListUserNotificationRulesSchema = z.object({
  items: z.array(UserNotificationRulesItemSchema),
  truncated: z.boolean(),
  fetchedAt: z.string(),
});

const CreateUserNotificationRuleSchema = z.object({
  id: z.string().describe("Unique identifier for the rule"),
  type: z.enum(["notification_rules"]).optional().describe(
    "Indicates that the resource is of type 'notification_rules'.",
  ),
  category: z.enum(["high_urgency", "low_urgency"]).optional().describe(
    "Specifies the category a notification rule will apply to",
  ),
  channel_settings: z.unknown().optional().describe(
    "Defines the configuration for a channel associated with a notification rule",
  ),
  delay_minutes: z.number().int().optional().describe(
    "The number of minutes that will elapse before this rule is evaluated. 0 indicates immediate evalu...",
  ),
  channel_id: z.string().optional().describe("Related channel ID"),
});

// =============================================================================
// Model Definition
// =============================================================================

/** Datadog On-Call — on-call schedules, escalation policies, and routing */
export const model = {
  type: "@webframp/datadog/on-call",
  version: "2026.07.20.10",
  globalArguments: GlobalArgsSchema,

  upgrades: [],

  resources: {
    "on_call_escalation_policy": {
      description: "Create On-Call escalation policy",
      schema: CreateOnCallEscalationPolicySchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "on_call_schedule": {
      description: "Create On-Call schedule",
      schema: CreateOnCallScheduleSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "schedule_on_call_responders": {
      description: "Get on-call responders for a schedule",
      schema: GetScheduleOnCallRespondersSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "team_on_call_users": {
      description: "Get team on-call users",
      schema: GetTeamOnCallUsersSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "on_call_team_routing_rules": {
      description: "Get On-Call team routing rules",
      schema: GetOnCallTeamRoutingRulesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "set_on_call_team_routing_rules": {
      description: "Set On-Call team routing rules",
      schema: SetOnCallTeamRoutingRulesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "user_notification_channels": {
      description: "List On-Call notification channels for a user",
      schema: ListUserNotificationChannelsSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "user_notification_channel": {
      description: "Create an On-Call notification channel for a user",
      schema: CreateUserNotificationChannelSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
    "user_notification_rules": {
      description: "List On-Call notification rules for a user",
      schema: ListUserNotificationRulesSchema,
      lifetime: "infinite" as const,
      garbageCollection: 10,
    },
    "user_notification_rule": {
      description: "Create an On-Call notification rule for a user",
      schema: CreateUserNotificationRuleSchema,
      lifetime: "infinite" as const,
      garbageCollection: 20,
    },
  },

  methods: {
    create_on_call_escalation_policy: {
      description: "Create On-Call escalation policy",
      arguments: z.object({
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        name: z.string().min(1).describe(
          "Specifies the name for the new escalation policy.",
        ),
        resolve_page_on_policy_end: z.boolean().optional().describe(
          "Indicates whether the page is automatically resolved when the policy ends.",
        ),
        retries: z.number().int().min(0).max(10).optional().describe(
          "Specifies how many times the escalation sequence is retried if there is no re...",
        ),
        steps: z.array(z.unknown()).describe(
          "A list of escalation steps, each defining assignment, escalation timeout, and...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && ["include"].includes(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["include"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "policies", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/on-call/escalation-policies${qs}`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "on_call_escalation_policy",
          id,
          result,
        );
        context.logger.info("Created on_call_escalation_policy {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_on_call_escalation_policy: {
      description: "Get On-Call escalation policy",
      arguments: z.object({
        policy_id: z.string().describe("The ID of the escalation policy"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>(["policy_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/escalation-policies/${
            encodeURIComponent(String(args.policy_id))
          }${qs}`,
        );

        const handle = await context.writeResource(
          "on_call_escalation_policy",
          String(args.policy_id),
          result,
        );
        context.logger.info("Fetched on_call_escalation_policy", {});
        return { dataHandles: [handle] };
      },
    },
    update_on_call_escalation_policy: {
      description: "Update On-Call escalation policy",
      arguments: z.object({
        policy_id: z.string().describe("The ID of the escalation policy"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        name: z.string().min(1).describe(
          "Specifies the name of the escalation policy.",
        ),
        resolve_page_on_policy_end: z.boolean().optional().describe(
          "Indicates whether the page is automatically resolved when the policy ends.",
        ),
        retries: z.number().int().min(0).max(10).optional().describe(
          "Specifies how many times the escalation sequence is retried if there is no re...",
        ),
        steps: z.array(z.unknown()).describe(
          "A list of escalation steps, each defining assignment, escalation timeout, and...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["policy_id", "include"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "policies", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PUT",
          `/api/v2/on-call/escalation-policies/${
            encodeURIComponent(String(args.policy_id))
          }`,
          body,
        );

        const handle = await context.writeResource(
          "on_call_escalation_policy",
          String(args.policy_id),
          result,
        );
        context.logger.info("Updated on_call_escalation_policy", {});
        return { dataHandles: [handle] };
      },
    },
    delete_on_call_escalation_policy: {
      description: "Delete On-Call escalation policy",
      arguments: z.object({
        policy_id: z.string().describe("The ID of the escalation policy"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/on-call/escalation-policies/${
            encodeURIComponent(String(args.policy_id))
          }`,
        );

        context.logger.info("Deleted resource {id}", { id: args.policy_id });
        return { dataHandles: [] };
      },
    },
    create_on_call_schedule: {
      description: "Create On-Call schedule",
      arguments: z.object({
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        layers: z.array(z.unknown()).describe(
          "The layers of On-Call coverage that define rotation intervals and restrictions.",
        ),
        name: z.string().describe(
          "A human-readable name for the new schedule.",
        ),
        time_zone: z.string().describe(
          "The time zone in which the schedule is defined.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && ["include"].includes(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["include"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "schedules", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/on-call/schedules${qs}`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "on_call_schedule",
          id,
          result,
        );
        context.logger.info("Created on_call_schedule {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_on_call_schedule: {
      description: "Get On-Call schedule",
      arguments: z.object({
        schedule_id: z.string().describe("The ID of the schedule"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>(["schedule_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/schedules/${
            encodeURIComponent(String(args.schedule_id))
          }${qs}`,
        );

        const handle = await context.writeResource(
          "on_call_schedule",
          String(args.schedule_id),
          result,
        );
        context.logger.info("Fetched on_call_schedule", {});
        return { dataHandles: [handle] };
      },
    },
    update_on_call_schedule: {
      description: "Update On-Call schedule",
      arguments: z.object({
        schedule_id: z.string().describe("The ID of the schedule"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        layers: z.array(z.unknown()).describe(
          "The updated list of layers (rotations) for this schedule.",
        ),
        name: z.string().describe("A short name for the schedule."),
        time_zone: z.string().describe(
          "The time zone used when interpreting rotation times.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["schedule_id", "include"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = { data: { type: "schedules", attributes: attrs } };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PUT",
          `/api/v2/on-call/schedules/${
            encodeURIComponent(String(args.schedule_id))
          }`,
          body,
        );

        const handle = await context.writeResource(
          "on_call_schedule",
          String(args.schedule_id),
          result,
        );
        context.logger.info("Updated on_call_schedule", {});
        return { dataHandles: [handle] };
      },
    },
    delete_on_call_schedule: {
      description: "Delete On-Call schedule",
      arguments: z.object({
        schedule_id: z.string().describe("The ID of the schedule"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/on-call/schedules/${
            encodeURIComponent(String(args.schedule_id))
          }`,
        );

        context.logger.info("Deleted resource {id}", { id: args.schedule_id });
        return { dataHandles: [] };
      },
    },
    get_schedule_on_call_responders: {
      description: "Get on-call responders for a schedule",
      arguments: z.object({
        schedule_id: z.string().describe("The ID of the schedule."),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        filter_position: z.string().optional().describe(
          "Comma-separated list of positions to retrieve. Allowed values: `previous`, `c...",
        ),
        filter_at_ts: z.string().optional().describe(
          "Retrieves the on-call responders at the given timestamp in RFC3339 format (fo...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>(["schedule_id"]);
        const paramNameMap: Record<string, string> = {
          "filter_position": "filter[position]",
          "filter_at_ts": "filter[at_ts]",
        };
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiName = paramNameMap[k] ?? k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/schedules/${
            encodeURIComponent(String(args.schedule_id))
          }/responders${qs}`,
        );

        const handle = await context.writeResource(
          "schedule_on_call_responders",
          String(args.schedule_id),
          result,
        );
        context.logger.info("Fetched schedule_on_call_responders", {});
        return { dataHandles: [handle] };
      },
    },
    get_team_on_call_users: {
      description: "Get team on-call users",
      arguments: z.object({
        team_id: z.string().describe("The team ID"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/teams/${
            encodeURIComponent(String(args.team_id))
          }/on-call${qs}`,
        );

        const handle = await context.writeResource(
          "team_on_call_users",
          String(args.team_id),
          result,
        );
        context.logger.info("Fetched team_on_call_users", {});
        return { dataHandles: [handle] };
      },
    },
    get_on_call_team_routing_rules: {
      description: "Get On-Call team routing rules",
      arguments: z.object({
        team_id: z.string().describe("The team ID"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>(["team_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/teams/${
            encodeURIComponent(String(args.team_id))
          }/routing-rules${qs}`,
        );

        const handle = await context.writeResource(
          "on_call_team_routing_rules",
          String(args.team_id),
          result,
        );
        context.logger.info("Fetched on_call_team_routing_rules", {});
        return { dataHandles: [handle] };
      },
    },
    set_on_call_team_routing_rules: {
      description: "Set On-Call team routing rules",
      arguments: z.object({
        team_id: z.string().describe("The team ID"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        rules: z.array(z.unknown()).optional().describe(
          "A list of routing rule items that define how incoming pages should be handled.",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["team_id", "include"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "team_routing_rules", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PUT",
          `/api/v2/on-call/teams/${
            encodeURIComponent(String(args.team_id))
          }/routing-rules`,
          body,
        );

        const handle = await context.writeResource(
          "set_on_call_team_routing_rules",
          String(args.team_id),
          result,
        );
        context.logger.info("Updated set_on_call_team_routing_rules", {});
        return { dataHandles: [handle] };
      },
    },
    list_user_notification_channels: {
      description: "List On-Call notification channels for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["user_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiKey = k;
            params[apiKey] = String(v);
          }
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-channels`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "user_notification_channels",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} user_notification_channels", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_user_notification_channel: {
      description: "Create an On-Call notification channel for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        config: z.unknown().optional().describe(
          "Notification channel configuration",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["user_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "notification_channels", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-channels`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "user_notification_channel",
          id,
          result,
        );
        context.logger.info("Created user_notification_channel {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_user_notification_channel: {
      description: "Get an On-Call notification channel for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        channel_id: z.string().describe("The channel ID"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-channels/${
            encodeURIComponent(String(args.channel_id))
          }`,
        );

        const handle = await context.writeResource(
          "user_notification_channel",
          String(args.channel_id),
          result,
        );
        context.logger.info("Fetched user_notification_channel", {});
        return { dataHandles: [handle] };
      },
    },
    delete_user_notification_channel: {
      description: "Delete an On-Call notification channel for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        channel_id: z.string().describe("The channel ID"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-channels/${
            encodeURIComponent(String(args.channel_id))
          }`,
        );

        context.logger.info("Deleted resource {id}", { id: args.channel_id });
        return { dataHandles: [] };
      },
    },
    list_user_notification_rules: {
      description: "List On-Call notification rules for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const params: Record<string, string> = {};
        const excludeKeys = new Set<string>(["user_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiKey = k;
            params[apiKey] = String(v);
          }
        }

        const { results, truncated } = await ddApiPaginated(
          apiKey,
          appKey,
          site,
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-rules`,
          { "style": "none", "limitParam": "", "limitDefault": 0 },
          params,
        );

        if (truncated) {
          context.logger.info(
            "WARNING: results truncated at {count} (pagination cap)",
            { count: results.length },
          );
        }

        const handle = await context.writeResource(
          "user_notification_rules",
          "main",
          {
            items: results,
            truncated,
            fetchedAt: new Date().toISOString(),
          },
        );

        context.logger.info("Found {count} user_notification_rules", {
          count: results.length,
        });
        return { dataHandles: [handle] };
      },
    },
    create_user_notification_rule: {
      description: "Create an On-Call notification rule for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        category: z.unknown().optional(),
        channel_settings: z.unknown().nullable().optional().describe(
          "Configuration for the associated channel, if necessary",
        ),
        delay_minutes: z.number().int().optional().describe(
          "The number of minutes that will elapse before this rule is evaluated. 0 indic...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["user_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "notification_rules", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "POST",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-rules`,
          body,
        );

        const id = (result as { id?: string }).id ?? "created";
        const handle = await context.writeResource(
          "user_notification_rule",
          id,
          result,
        );
        context.logger.info("Created user_notification_rule {id}", { id });
        return { dataHandles: [handle] };
      },
    },
    get_user_notification_rule: {
      description: "Get an On-Call notification rule for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        rule_id: z.string().describe("The rule ID"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const queryParts: string[] = [];
        const excludeKeys = new Set<string>(["user_id", "rule_id"]);
        for (const [k, v] of Object.entries(args)) {
          if (v !== undefined && !excludeKeys.has(k)) {
            const apiName = k;
            queryParts.push(
              `${encodeURIComponent(apiName)}=${encodeURIComponent(String(v))}`,
            );
          }
        }
        const qs = queryParts.length > 0 ? `?${queryParts.join("&")}` : "";

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "GET",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-rules/${
            encodeURIComponent(String(args.rule_id))
          }${qs}`,
        );

        const handle = await context.writeResource(
          "user_notification_rule",
          String(args.rule_id),
          result,
        );
        context.logger.info("Fetched user_notification_rule", {});
        return { dataHandles: [handle] };
      },
    },
    update_user_notification_rule: {
      description: "Update an On-Call notification rule for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        rule_id: z.string().describe("The rule ID"),
        include: z.string().optional().describe(
          "Comma-separated list of included relationships to be returned. Allowed values...",
        ),
        category: z.unknown().optional(),
        channel_settings: z.unknown().nullable().optional().describe(
          "Configuration for the associated channel, if necessary",
        ),
        delay_minutes: z.number().int().optional().describe(
          "The number of minutes that will elapse before this rule is evaluated. 0 indic...",
        ),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        const attrs: Record<string, unknown> = {};
        const excludeKeys = new Set<string>(["user_id", "rule_id", "include"]);
        for (const [k, v] of Object.entries(args)) {
          if (!excludeKeys.has(k)) attrs[k] = v;
        }
        const body = {
          data: { type: "notification_rules", attributes: attrs },
        };

        const result = await ddApi(
          apiKey,
          appKey,
          site,
          "PUT",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-rules/${encodeURIComponent(String(args.rule_id))}`,
          body,
        );

        const handle = await context.writeResource(
          "user_notification_rule",
          String(args.rule_id),
          result,
        );
        context.logger.info("Updated user_notification_rule", {});
        return { dataHandles: [handle] };
      },
    },
    delete_user_notification_rule: {
      description: "Delete an On-Call notification rule for a user",
      arguments: z.object({
        user_id: z.string().describe("The user ID"),
        rule_id: z.string().describe("The rule ID"),
      }),
      execute: async (
        args: Record<string, unknown>,
        context: {
          globalArgs: Record<string, string>;
          writeResource: (
            spec: string,
            instance: string,
            data: unknown,
          ) => Promise<{ name: string }>;
          logger: {
            info: (msg: string, props: Record<string, unknown>) => void;
          };
        },
      ) => {
        const { apiKey, appKey, site } = context.globalArgs;
        await ddApi(
          apiKey,
          appKey,
          site,
          "DELETE",
          `/api/v2/on-call/users/${
            encodeURIComponent(String(args.user_id))
          }/notification-rules/${encodeURIComponent(String(args.rule_id))}`,
        );

        context.logger.info("Deleted resource {id}", { id: args.rule_id });
        return { dataHandles: [] };
      },
    },
  },
};
