// Cloudflare Rulesets — WAF custom rules, transform rules, managed rulesets — Tests
// Auto-generated by scripts/cloudflare-codegen — do not edit manually.
// SPDX-License-Identifier: Apache-2.0

import { assertEquals, assertExists } from "jsr:@std/assert@1.0.19";
import { createModelTestContext } from "@systeminit/swamp-testing";
import { model } from "./rulesets.ts";

// ---------------------------------------------------------------------------
// Model Export Structure Tests
// ---------------------------------------------------------------------------

Deno.test("rulesets model: has correct type", () => {
  assertEquals(model.type, "@webframp/cloudflare/rulesets");
});

Deno.test("rulesets model: has valid version format", () => {
  const versionPattern = /^\d{4}\.\d{2}\.\d{2}\.\d+$/;
  assertEquals(versionPattern.test(model.version), true);
});

Deno.test("rulesets model: has globalArguments with apiToken", () => {
  assertExists(model.globalArguments);
  const shape = model.globalArguments.shape;
  assertExists(shape.apiToken);
  assertExists(shape.accountId);
});

Deno.test("rulesets model: has expected methods", () => {
  assertExists(model.methods);
  assertExists(model.methods.listaccountrulesets);
  assertExists(model.methods.createaccountruleset);
  assertExists(model.methods.getaccountentrypointruleset);
  assertExists(model.methods.updateaccountentrypointruleset);
  assertExists(model.methods.listaccountentrypointrulesetversions);
  assertExists(model.methods.getaccountentrypointrulesetversion);
  assertExists(model.methods.getaccountruleset);
  assertExists(model.methods.updateaccountruleset);
  assertExists(model.methods.deleteaccountruleset);
  assertExists(model.methods.createaccountrulesetrule);
  assertExists(model.methods.updateaccountrulesetrule);
  assertExists(model.methods.deleteaccountrulesetrule);
  assertExists(model.methods.listaccountrulesetversions);
  assertExists(model.methods.getaccountrulesetversion);
  assertExists(model.methods.deleteaccountrulesetversion);
  assertExists(model.methods.listaccountrulesetversionrulesbytag);
  assertExists(model.methods.listzonerulesets);
  assertExists(model.methods.createzoneruleset);
  assertExists(model.methods.getzoneentrypointruleset);
  assertExists(model.methods.updatezoneentrypointruleset);
  assertExists(model.methods.listzoneentrypointrulesetversions);
  assertExists(model.methods.getzoneentrypointrulesetversion);
  assertExists(model.methods.getzoneruleset);
  assertExists(model.methods.updatezoneruleset);
  assertExists(model.methods.deletezoneruleset);
  assertExists(model.methods.createzonerulesetrule);
  assertExists(model.methods.updatezonerulesetrule);
  assertExists(model.methods.deletezonerulesetrule);
  assertExists(model.methods.listzonerulesetversions);
  assertExists(model.methods.getzonerulesetversion);
  assertExists(model.methods.deletezonerulesetversion);
  assertExists(model.methods.listzonerulesetversionrulesbytag);
});

Deno.test("rulesets model: has expected resources", () => {
  assertExists(model.resources);
  assertExists(model.resources["listaccountrulesets"]);
  assertExists(model.resources["createaccountruleset"]);
  assertExists(model.resources["getaccountentrypointruleset"]);
  assertExists(model.resources["updateaccountentrypointruleset"]);
  assertExists(model.resources["listaccountentrypointrulesetversions"]);
  assertExists(model.resources["getaccountentrypointrulesetversion"]);
  assertExists(model.resources["getaccountruleset"]);
  assertExists(model.resources["updateaccountruleset"]);
  assertExists(model.resources["createaccountrulesetrule"]);
  assertExists(model.resources["updateaccountrulesetrule"]);
  assertExists(model.resources["listaccountrulesetversions"]);
  assertExists(model.resources["getaccountrulesetversion"]);
  assertExists(model.resources["listaccountrulesetversionrulesbytag"]);
  assertExists(model.resources["listzonerulesets"]);
  assertExists(model.resources["createzoneruleset"]);
  assertExists(model.resources["getzoneentrypointruleset"]);
  assertExists(model.resources["updatezoneentrypointruleset"]);
  assertExists(model.resources["listzoneentrypointrulesetversions"]);
  assertExists(model.resources["getzoneentrypointrulesetversion"]);
  assertExists(model.resources["getzoneruleset"]);
  assertExists(model.resources["updatezoneruleset"]);
  assertExists(model.resources["createzonerulesetrule"]);
  assertExists(model.resources["updatezonerulesetrule"]);
  assertExists(model.resources["listzonerulesetversions"]);
  assertExists(model.resources["getzonerulesetversion"]);
  assertExists(model.resources["listzonerulesetversionrulesbytag"]);
});

// ---------------------------------------------------------------------------
// Mock Cloudflare API Server
// ---------------------------------------------------------------------------

function startMockCfServer(
  responses: Record<string, { result: unknown; isCollection?: boolean }>,
): { url: string; server: Deno.HttpServer } {
  const server = Deno.serve({ port: 0, onListen() {} }, (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    for (
      const [pattern, { result, isCollection }] of Object.entries(responses)
    ) {
      if (path.includes(pattern)) {
        return Response.json({
          success: true,
          errors: [],
          messages: [],
          result,
          result_info: isCollection
            ? {
              page: 1,
              per_page: 50,
              total_count: Array.isArray(result) ? result.length : 1,
              total_pages: 1,
            }
            : undefined,
        });
      }
    }

    return Response.json({
      success: false,
      errors: [{ code: 404, message: "Not found" }],
      messages: [],
      result: null,
    });
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: `http://localhost:${addr.port}`, server };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    const newUrl = reqUrl.replace(
      "https://api.cloudflare.com/client/v4",
      mockUrl,
    );
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}

Deno.test({
  name: "rulesets model: listaccountrulesets fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = { "id": "fixture-123" };
    const { url, server } = startMockCfServer({
      "/rulesets": { result: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-rulesets",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).listaccountrulesets.execute({}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "rulesets model: createaccountruleset executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = { "id": "fixture-123" };
    const { url, server } = startMockCfServer({
      "/rulesets": { result: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-rulesets",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).createaccountruleset.execute({ "id": "fixture-123" }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "rulesets model: updateaccountentrypointruleset executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = { "id": "fixture-123" };
    const { url, server } = startMockCfServer({
      "/rulesets/phases/test-id-123/entrypoint": { result: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-rulesets",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).updateaccountentrypointruleset.execute({
        "ruleset_phase": "test-id-123",
        "id": "fixture-123",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "rulesets model: deleteaccountruleset executes successfully",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockCfServer({
      "/rulesets/test-id-123": { result: { id: "test-id-123" } },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-rulesets",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).deleteaccountruleset.execute(
        { "ruleset_id": "test-id-123" },
        context,
      );
      assertEquals(result.dataHandles.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});
