/**
 * Method classifier — determines the swamp method type for each operation
 * and generates the model source code.
 *
 * Classifies operations as:
 * - list: GET returning a collection
 * - get: GET returning a single item (path ends with {id})
 * - create: POST that creates a resource
 * - update: PUT/PATCH that modifies a resource
 * - delete: DELETE
 * - action: POST that performs an action (not a standard CRUD create)
 */

import type { GroupedOperation, ServiceGroup } from "./service_grouper.ts";
import { schemaToZod } from "./type_mapper.ts";
import { ZOD_VERSION } from "../config.ts";
import type { ServiceConfig } from "../config.ts";

export type MethodType =
  | "list"
  | "get"
  | "create"
  | "update"
  | "delete"
  | "action";

export interface ClassifiedMethod {
  /** swamp method name (e.g., list_buckets, get_bucket, create_bucket) */
  name: string;
  /** The classification */
  type: MethodType;
  /** Description for the method */
  description: string;
  /** The original operation */
  operation: GroupedOperation;
}

/**
 * Classify an operation into a swamp method type.
 */
export function classifyOperation(op: GroupedOperation): MethodType {
  const { httpMethod, path, isCollection } = op;

  switch (httpMethod) {
    case "get":
      if (isCollection) return "list";
      return "get";
    case "post": {
      // Heuristic: if path ends without {id} param and has a request body
      // with properties matching a resource shape, it's a create.
      // Otherwise it's an action.
      const lastSegment = path.split("/").pop() ?? "";
      if (lastSegment.startsWith("{")) return "action";
      if (op.requestBody?.properties) return "create";
      return "action";
    }
    case "put":
    case "patch":
      return "update";
    case "delete":
      return "delete";
    default:
      return "action";
  }
}

/**
 * Generate a method name from the operation.
 * Uses the operationId if available, otherwise constructs from path + method.
 */
export function generateMethodName(
  op: GroupedOperation,
  type: MethodType,
): string {
  // Try to extract a clean name from operationId
  if (op.operationId) {
    // CF operationIds are like "r2-list-buckets" or "workers-kv-list-namespaces"
    // Remove the service prefix: everything up to and including the first verb
    let name = op.operationId.replace(/-/g, "_");

    // Strip known service prefixes (e.g., "r2_", "workers_kv_", "d1_")
    // Strategy: remove everything before the first recognized verb
    const verbPrefixes = [
      "list",
      "get",
      "create",
      "update",
      "delete",
      "put",
      "patch",
    ];
    for (const verb of verbPrefixes) {
      const idx = name.indexOf(`${verb}_`);
      if (idx > 0) {
        name = name.slice(idx);
        break;
      }
      // Also check if name ends with or equals the verb (no trailing resource)
      if (name.endsWith(`_${verb}`) || name === verb) {
        name = name.slice(name.lastIndexOf(`_${verb}`) + 1);
        break;
      }
    }

    // If no verb was found in the name, prefix with the type
    const hasVerb = verbPrefixes.some((v) => name.startsWith(v));
    if (!hasVerb && type !== "action") {
      name = `${type}_${name}`;
    }

    return sanitizeMethodName(name);
  }

  // Fallback: construct from path
  const segments = op.path.split("/").filter((s) => s && !s.startsWith("{"));
  const lastSegments = segments.slice(-2);
  const resource = lastSegments.join("_");
  return sanitizeMethodName(`${type}_${resource}`);
}

/** Sanitize a method name to valid TypeScript identifier */
function sanitizeMethodName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}

/**
 * Classify all operations in a service group into methods.
 * De-duplicates by method name (first wins).
 */
export function classifyServiceMethods(
  group: ServiceGroup,
): ClassifiedMethod[] {
  const methods: ClassifiedMethod[] = [];
  const seen = new Set<string>();

  for (const op of group.operations) {
    const type = classifyOperation(op);
    const name = generateMethodName(op, type);

    if (seen.has(name)) continue;
    seen.add(name);

    methods.push({
      name,
      type,
      description: op.summary || op.description || `${type} operation`,
      operation: op,
    });
  }

  return methods;
}

/**
 * Generate the complete model TypeScript source file for a service.
 */
export function generateModelSource(
  group: ServiceGroup,
  methods: ClassifiedMethod[],
  version: string,
  upgradesBlock = "  upgrades: [],",
): string {
  const { config } = group;
  const modelType = `@webframp/cloudflare/${config.name}`;

  const lines: string[] = [];

  // Header
  lines.push(`/**`);
  lines.push(` * ${config.description}`);
  lines.push(` *`);
  lines.push(
    ` * Auto-generated by scripts/cloudflare-codegen — do not edit manually.`,
  );
  lines.push(` *`);
  lines.push(` * @module`);
  lines.push(` */`);
  lines.push(
    `// SPDX-License-Identifier: Apache-2.0`,
  );
  lines.push(``);
  lines.push(`import { z } from "npm:zod@${ZOD_VERSION}";`);

  // Only import the API helpers that are actually used
  const usesCfApi = methods.some((m) =>
    m.type !== "list" || m.operation.usesCursorPagination
  );
  const usesCfApiPaginated = methods.some((m) =>
    m.type === "list" && !m.operation.usesCursorPagination
  );
  const apiImports: string[] = [];
  if (usesCfApi) apiImports.push("cfApi");
  if (usesCfApiPaginated) apiImports.push("cfApiPaginated");
  // sanitizeInstanceName is emitted only by bodies that build an instance name
  // from an API-influenced value: every `create`, and any `get`/`update`
  // targeting a resource by a path id. `list` ("main") and `action` ("latest")
  // use constant instance names and never call it. Import it only when a body
  // actually references it, or deno lint fails with no-unused-vars.
  const usesSanitize = methods.some(methodEmitsSanitize);
  if (usesSanitize) apiImports.push("sanitizeInstanceName");
  if (apiImports.length > 0) {
    lines.push(
      `import { ${apiImports.join(", ")} } from "./_lib/api.ts";`,
    );
  }
  lines.push(``);
  // EXTENSION_NAME is referenced by list method bodies (collectedBy metadata).
  // Only emit it when a list method exists, or it would be an unused const.
  const hasListMethod = methods.some((m) => m.type === "list");
  if (hasListMethod) {
    lines.push(`const EXTENSION_NAME = "${modelType}";`);
    lines.push(``);
  }

  // Schemas section
  lines.push(
    `// =============================================================================`,
  );
  lines.push(`// Schemas`);
  lines.push(
    `// =============================================================================`,
  );
  lines.push(``);

  // GlobalArgs
  lines.push(generateGlobalArgsSchema(config));
  lines.push(``);

  // Generate response schemas for each unique response shape
  const schemaNames = generateResponseSchemas(methods, lines);

  // Model definition
  lines.push(
    `// =============================================================================`,
  );
  lines.push(`// Model Definition`);
  lines.push(
    `// =============================================================================`,
  );
  lines.push(``);
  lines.push(`/** ${config.description} */`);
  lines.push(`export const model = {`);
  lines.push(`  type: "${modelType}",`);
  lines.push(`  version: "${version}",`);
  lines.push(`  globalArguments: GlobalArgsSchema,`);
  lines.push(``);
  lines.push(upgradesBlock);
  lines.push(``);

  // Resources
  lines.push(`  resources: {`);
  const seenResources = new Set<string>();
  for (const method of methods) {
    if (method.type === "delete") continue;
    const resourceName = method.type === "list"
      ? method.name.replace(/^list_/, "")
      : method.name.replace(/^(get|create|update|action)_/, "");
    if (seenResources.has(resourceName)) continue;
    seenResources.add(resourceName);
    lines.push(
      `    "${resourceName}": {`,
    );
    lines.push(`      description: "${escapeStr(method.description)}",`);
    lines.push(
      `      schema: ${schemaNames.get(method.name) ?? "z.object({})"},`,
    );
    lines.push(`      lifetime: "infinite" as const,`);
    lines.push(
      `      garbageCollection: ${method.type === "list" ? 10 : 20},`,
    );
    lines.push(`    },`);
  }
  lines.push(`  },`);
  lines.push(``);

  // Methods
  lines.push(`  methods: {`);
  for (const method of methods) {
    lines.push(generateMethod(method, config, schemaNames));
  }
  lines.push(`  },`);
  lines.push(`};`);
  lines.push(``);

  return lines.join("\n");
}

/** Generate GlobalArgsSchema based on service scope */
function generateGlobalArgsSchema(config: ServiceConfig): string {
  const lines = [`const GlobalArgsSchema = z.object({`];
  lines.push(
    `  apiToken: z.string().meta({ sensitive: true }).describe("Cloudflare API token; overrides the CLOUDFLARE_API_TOKEN environment variable. Wire with a vault.get(...) expression to source it from a vault.").optional(),`,
  );

  if (config.scope === "account") {
    lines.push(
      `  accountId: z.string().describe("Cloudflare account ID"),`,
    );
  } else if (config.scope === "zone") {
    lines.push(
      `  zoneId: z.string().describe("Cloudflare zone ID"),`,
    );
  }

  lines.push(`});`);
  return lines.join("\n");
}

/** Generate Zod schemas for all unique response shapes */
function generateResponseSchemas(
  methods: ClassifiedMethod[],
  lines: string[],
): Map<string, string> {
  const schemaNames = new Map<string, string>();

  // First pass: determine which methods will actually produce resources
  // (dedup by resource name, matching the resources section logic)
  const seenResources = new Set<string>();
  const methodsWithResources: ClassifiedMethod[] = [];

  for (const method of methods) {
    if (method.type === "delete") continue;
    const resourceName = method.type === "list"
      ? method.name.replace(/^list_/, "")
      : method.name.replace(/^(get|create|update|action)_/, "");
    if (!seenResources.has(resourceName)) {
      seenResources.add(resourceName);
      methodsWithResources.push(method);
    }
  }

  for (const method of methodsWithResources) {
    const schema = method.operation.responseSchema;
    if (!schema) {
      schemaNames.set(method.name, "z.object({})");
      continue;
    }

    const varName = toPascalCase(method.name) + "Schema";
    schemaNames.set(method.name, varName);

    if (method.type === "list") {
      // For list methods, generate both item schema and list wrapper
      const itemVarName = toPascalCase(method.name.replace(/^list_/, "")) +
        "ItemSchema";
      const itemZod = withPassthrough(schemaToZod(schema, { indent: 2 }, 1));
      lines.push(`const ${itemVarName} = ${itemZod};`);
      lines.push(``);
      lines.push(`const ${varName} = z.object({`);
      lines.push(`  items: z.array(${itemVarName}),`);
      lines.push(`  truncated: z.boolean(),`);
      lines.push(`  fetchedAt: z.string(),`);
      lines.push(
        `  durationMs: z.number().optional().describe(`,
      );
      lines.push(`    "Method execution duration in milliseconds",`);
      lines.push(`  ),`);
      lines.push(
        `  collectedBy: z.string().optional().describe(`,
      );
      lines.push(`    "Extension that collected this data",`);
      lines.push(`  ),`);
      lines.push(`});`);
    } else {
      const zodStr = withPassthrough(schemaToZod(schema, { indent: 2 }, 1));
      lines.push(`const ${varName} = ${zodStr};`);
    }
    lines.push(``);
  }

  // For methods that share a resource name but aren't the "primary" one,
  // map them to the same schema variable
  for (const method of methods) {
    if (method.type === "delete") continue;
    if (schemaNames.has(method.name)) continue;
    const resourceName = method.type === "list"
      ? method.name.replace(/^list_/, "")
      : method.name.replace(/^(get|create|update|action)_/, "");
    // Find the primary method for this resource
    const primary = methodsWithResources.find((m) => {
      const primaryResource = m.type === "list"
        ? m.name.replace(/^list_/, "")
        : m.name.replace(/^(get|create|update|action)_/, "");
      return primaryResource === resourceName;
    });
    if (primary) {
      schemaNames.set(
        method.name,
        schemaNames.get(primary.name) ?? "z.object({})",
      );
    } else {
      schemaNames.set(method.name, "z.object({})");
    }
  }

  return schemaNames;
}

/** Generate a single method definition */
function generateMethod(
  method: ClassifiedMethod,
  config: ServiceConfig,
  _schemaNames: Map<string, string>,
): string {
  const { operation } = method;
  const lines: string[] = [];
  const indent = "    ";

  lines.push(`${indent}${method.name}: {`);
  lines.push(
    `${indent}  description: "${escapeStr(method.description)}",`,
  );

  // Arguments schema
  lines.push(`${indent}  arguments: ${generateArgsSchema(operation)},`);

  // Execute function. The body is generated first so the parameter name can be
  // derived from whether the body actually references `args`, rather than
  // predicted ahead of time by methodUsesArgs(). Prediction and reality can
  // disagree — a path template placeholder the spec never declares still
  // produces an `args.<name>` reference — and when they do, the generated method
  // does not compile. Deriving it removes the whole class of mismatch.
  const bodyLines = generateExecuteBody(method, config, indent);
  const argsParam = bodyReferencesArgs(bodyLines) ? "args" : "_args";
  lines.push(
    `${indent}  execute: async (${argsParam}: Record<string, unknown>, context: { globalArgs: Record<string, string>; writeResource: (spec: string, instance: string, data: unknown) => Promise<{ name: string }>; logger: { info: (msg: string, props: Record<string, unknown>) => void } }) => {`,
  );
  lines.push(...bodyLines);

  lines.push(`${indent}  },`);
  lines.push(`${indent}},`);

  return lines.join("\n");
}

/**
 * True when generated body text references the `args` parameter.
 *
 * Comments are stripped first: a comment mentioning `args` says nothing about
 * whether the code uses it, and naming the parameter `args` on that basis would
 * produce a misleading signature.
 *
 * Word-boundary matched so `_args`, `argsSchema`, `context.globalArgs`, or a
 * field literally named `myargs` do not count as uses.
 *
 * Exported for direct unit testing.
 */
export function bodyReferencesArgs(bodyLines: string[]): boolean {
  const code = bodyLines
    .join("\n")
    // Line comments only. Block comments are not emitted into method bodies by
    // any generator path, and stripping them naively would corrupt string
    // literals containing "/*".
    .replace(/\/\/[^\n]*/g, "");
  return /(^|[^.\w])args\b/.test(code);
}

/** Generate the statements inside a method's execute function */
function generateExecuteBody(
  method: ClassifiedMethod,
  config: ServiceConfig,
  indent: string,
): string[] {
  const { operation, type } = method;
  const lines: string[] = [];

  const scopeId = config.scope === "account" ? "accountId" : "zoneId";

  // Build the API path with parameter substitution
  const apiPath = buildApiPath(operation.path, config.scope);

  // Only destructure the scope var if the path actually uses it
  const scopeParam = config.scope === "account" ? "account_id" : "zone_id";
  const pathUsesScopeVar = operation.path.includes(`{${scopeParam}}`);
  if (pathUsesScopeVar) {
    lines.push(
      `${indent}    const { apiToken, ${scopeId} } = context.globalArgs;`,
    );
  } else {
    lines.push(
      `${indent}    const { apiToken } = context.globalArgs;`,
    );
  }

  if (type === "list") {
    lines.push(generateListBody(method, apiPath, indent));
  } else if (type === "get") {
    lines.push(generateGetBody(method, apiPath, indent));
  } else if (type === "create") {
    lines.push(generateCreateBody(method, apiPath, indent));
  } else if (type === "update") {
    lines.push(generateUpdateBody(method, apiPath, indent));
  } else if (type === "delete") {
    lines.push(generateDeleteBody(method, apiPath, indent));
  } else {
    lines.push(generateActionBody(method, apiPath, indent));
  }

  return lines;
}

/** Generate the arguments schema for a method */
function generateArgsSchema(op: GroupedOperation): string {
  const fields: string[] = [];
  const seenFields = new Set<string>();

  // Path params (minus scope)
  for (const p of op.pathParams) {
    const fieldName = sanitizeFieldName(p.name);
    if (seenFields.has(fieldName)) continue;
    seenFields.add(fieldName);
    const desc = p.description
      ? `.describe("${escapeStr(p.description)}")`
      : "";
    fields.push(`  ${fieldName}: z.string()${desc},`);
  }

  // Query params (for list/get methods)
  for (const p of op.queryParams) {
    const fieldName = sanitizeFieldName(p.name);
    if (seenFields.has(fieldName)) continue;
    seenFields.add(fieldName);
    const desc = p.description
      ? `.describe("${escapeStr(p.description)}")`
      : "";
    let zodType = "z.string()";
    if (p.schema?.type === "integer" || p.schema?.type === "number") {
      zodType = "z.number()";
    } else if (p.schema?.type === "boolean") {
      zodType = "z.boolean()";
    } else if (p.schema?.enum) {
      const vals = (p.schema.enum as string[]).map((v) =>
        `"${escapeStr(String(v))}"`
      );
      zodType = `z.enum([${vals.join(", ")}])`;
    }
    fields.push(
      `  ${fieldName}: ${zodType}.optional()${desc},`,
    );
  }

  // Request body fields (for create/update).
  //
  // Order matters: a discriminated-union body (oneOf) sometimes carries a
  // sibling top-level `properties` entry that is just the discriminator field
  // (e.g. `kind`), already duplicated inside every oneOf variant. Checking
  // `properties` first would surface only that discriminator and silently
  // drop the variant-specific fields the body generators (which check oneOf
  // before properties) actually need — the args schema and the body builder
  // must agree on which shape they're using. So array and oneOf are checked
  // ahead of a bare `properties` object here, matching generateCreateBody /
  // generateUpdateBody / generateActionBody.
  if (op.requestBody?.type === "array" && op.requestBody.items) {
    // Bare-array request body (e.g., PUT /schedules expects an array of cron
    // objects). Expose as a required `items` argument containing the array.
    const itemZod = schemaToZod(op.requestBody.items, { indent: 2 }, 2);
    const desc = op.requestBody.description
      ? `.describe("${escapeStr(truncateStr(op.requestBody.description))}")`
      : "";
    if (!seenFields.has("items")) {
      seenFields.add("items");
      fields.push(`  items: z.array(${itemZod})${desc},`);
    }
  } else if (op.requestBody?.oneOf) {
    // Discriminated union request body (e.g., workers_secret with oneOf variants).
    // Expose the union as a required `body` argument using z.union.
    const variantZods = op.requestBody.oneOf.map((variant) =>
      schemaToZod(variant, { indent: 2 }, 2)
    );
    const desc = op.requestBody.description
      ? `.describe("${escapeStr(truncateStr(op.requestBody.description))}")`
      : "";
    if (!seenFields.has("body")) {
      seenFields.add("body");
      if (variantZods.length === 1) {
        fields.push(`  body: ${variantZods[0]}${desc},`);
      } else {
        fields.push(
          `  body: z.union([${variantZods.join(", ")}])${desc},`,
        );
      }
    }
  } else if (op.requestBody?.properties) {
    const required = new Set(op.requestBody.required ?? []);
    for (const [name, prop] of Object.entries(op.requestBody.properties)) {
      // Skip id fields in request bodies
      if (name === "id") continue;
      const fieldName = sanitizeFieldName(name);
      if (seenFields.has(fieldName)) continue;
      seenFields.add(fieldName);
      const fieldZod = schemaToZod(prop, { indent: 2 }, 2);
      const optSuffix = required.has(name) ? "" : ".optional()";
      const desc = prop.description
        ? `.describe("${escapeStr(truncateStr(prop.description))}")`
        : "";
      fields.push(
        `  ${fieldName}: ${fieldZod}${optSuffix}${desc},`,
      );
    }
  }

  if (fields.length === 0) {
    return "z.object({})";
  }

  return `z.object({\n${fields.join("\n")}\n    })`;
}

/** Generate list method body */
function generateListBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = method.name.replace(/^list_/, "");
  const pathParamNames = method.operation.pathParams
    .map((p) => sanitizeFieldName(p.name));

  // Cursor-based endpoints: single fetch, pass all query params directly
  if (method.operation.usesCursorPagination) {
    const excludeNames = [...pathParamNames];
    return `${indent}    const startMs = Date.now();
${indent}    const params: Record<string, string> = {};
${indent}    const excludeKeys = new Set(${JSON.stringify(excludeNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
${indent}    }
${indent}    const qs = new URLSearchParams(params).toString();
${indent}    const url = qs ? \`${apiPath}?\${qs}\` : \`${apiPath}\`;
${indent}
${indent}    const result = await cfApi<Record<string, unknown>>(apiToken, "GET", url);
${indent}    const items = (result as { result?: unknown[] })?.result ?? (Array.isArray(result) ? result : [result]);
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", "main", {
${indent}      items,
${indent}      truncated: false,
${indent}      fetchedAt: new Date().toISOString(),
${indent}      durationMs: Date.now() - startMs,
${indent}      collectedBy: EXTENSION_NAME,
${indent}    });
${indent}
${indent}    context.logger.info("Found {count} ${resourceName}", { count: (items as unknown[]).length });
${indent}    return { dataHandles: [handle] };`;
  }

  // Page-based: use cfApiPaginated, exclude path params and pagination params
  const excludeNames = [...pathParamNames, "page", "per_page"];

  return `${indent}    const startMs = Date.now();
${indent}    const params: Record<string, string> = {};
${indent}    const excludeKeys = new Set(${JSON.stringify(excludeNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (v !== undefined && !excludeKeys.has(k)) params[k] = String(v);
${indent}    }
${indent}
${indent}    const { results, truncated } = await cfApiPaginated<Record<string, unknown>>(
${indent}      apiToken,
${indent}      \`${apiPath}\`,
${indent}      params,
${indent}    );
${indent}
${indent}    if (truncated) {
${indent}      context.logger.info("WARNING: results truncated at {count} (pagination cap)", { count: results.length });
${indent}    }
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", "main", {
${indent}      items: results,
${indent}      truncated,
${indent}      fetchedAt: new Date().toISOString(),
${indent}      durationMs: Date.now() - startMs,
${indent}      collectedBy: EXTENSION_NAME,
${indent}    });
${indent}
${indent}    context.logger.info("Found {count} ${resourceName}", { count: results.length });
${indent}    return { dataHandles: [handle] };`;
}

/** Generate get method body */
function generateGetBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = method.name.replace(/^get_/, "");
  const idParam = method.operation.pathParams[
    method.operation.pathParams.length - 1
  ];
  const instanceExpr = idParam
    ? `sanitizeInstanceName(String(args.${sanitizeFieldName(idParam.name)}))`
    : '"latest"';

  return `${indent}    const result = await cfApi<Record<string, unknown>>(
${indent}      apiToken,
${indent}      "GET",
${indent}      \`${apiPath}\`,
${indent}    );
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", ${instanceExpr}, result);
${indent}    context.logger.info("Fetched ${resourceName}", {});
${indent}    return { dataHandles: [handle] };`;
}

/** Generate create method body */
function generateCreateBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = method.name.replace(/^create_/, "");
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];

  // Build query string from query params if any exist
  const hasQueryParams = queryParamNames.length > 0;
  const queryBuild = hasQueryParams
    ? `\n${indent}    const queryParts: string[] = [];
${indent}    const queryKeys = new Set(${JSON.stringify(queryParamNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (v !== undefined && queryKeys.has(k)) queryParts.push(\`\${k}=\${encodeURIComponent(String(v))}\`);
${indent}    }
${indent}    const qs = queryParts.length > 0 ? \`?\${queryParts.join("&")}\` : "";`
    : "";
  const pathSuffix = hasQueryParams ? "${qs}" : "";

  // Determine how to build the request body based on schema shape.
  const reqBody = method.operation.requestBody;
  let bodyFilter: string;
  if (reqBody?.type === "array") {
    bodyFilter = `\n${indent}    const body = args.items;`;
  } else if (reqBody?.oneOf) {
    bodyFilter = `\n${indent}    const body = args.body;`;
  } else if (excludeNames.length > 0) {
    bodyFilter = `\n${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set(${JSON.stringify(excludeNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }`;
  } else {
    bodyFilter = `\n${indent}    const body = args;`;
  }

  return `${bodyFilter}${queryBuild}
${indent}
${indent}    const result = await cfApi<Record<string, unknown>>(
${indent}      apiToken,
${indent}      "POST",
${indent}      \`${apiPath}${pathSuffix}\`,
${indent}      body,
${indent}    );
${indent}
${indent}    const id = sanitizeInstanceName((result as { id?: string }).id ?? "created");
${indent}    const handle = await context.writeResource("${resourceName}", id, result);
${indent}    context.logger.info("Created ${resourceName} {id}", { id });
${indent}    return { dataHandles: [handle] };`;
}

/** Generate update method body */
function generateUpdateBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = method.name.replace(/^update_/, "");
  const httpMethod = method.operation.httpMethod.toUpperCase();
  const idParam = method.operation.pathParams[
    method.operation.pathParams.length - 1
  ];
  const instanceExpr = idParam
    ? `sanitizeInstanceName(String(args.${sanitizeFieldName(idParam.name)}))`
    : '"updated"';
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];

  const hasQueryParams = queryParamNames.length > 0;
  const queryBuild = hasQueryParams
    ? `\n${indent}    const queryParts: string[] = [];
${indent}    const queryKeys = new Set(${JSON.stringify(queryParamNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (v !== undefined && queryKeys.has(k)) queryParts.push(\`\${k}=\${encodeURIComponent(String(v))}\`);
${indent}    }
${indent}    const qs = queryParts.length > 0 ? \`?\${queryParts.join("&")}\` : "";`
    : "";
  const pathSuffix = hasQueryParams ? "${qs}" : "";

  // Determine how to build the request body based on schema shape.
  // Bare-array bodies (exposed as `items` arg) must be sent as the raw array.
  // oneOf union bodies (exposed as `body` arg) must be sent as the raw value.
  // Standard object bodies are built by filtering path/query params from args.
  let bodyFilter: string;
  const reqBody = method.operation.requestBody;
  if (reqBody?.type === "array") {
    bodyFilter = `\n${indent}    const body = args.items;`;
  } else if (reqBody?.oneOf) {
    bodyFilter = `\n${indent}    const body = args.body;`;
  } else if (excludeNames.length > 0) {
    bodyFilter = `\n${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set(${JSON.stringify(excludeNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }`;
  } else {
    bodyFilter = `\n${indent}    const body = args;`;
  }

  return `${bodyFilter}${queryBuild}
${indent}
${indent}    const result = await cfApi<Record<string, unknown>>(
${indent}      apiToken,
${indent}      "${httpMethod}",
${indent}      \`${apiPath}${pathSuffix}\`,
${indent}      body,
${indent}    );
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", ${instanceExpr}, result);
${indent}    context.logger.info("Updated ${resourceName}", {});
${indent}    return { dataHandles: [handle] };`;
}

/** Generate delete method body */
function generateDeleteBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const idParam = method.operation.pathParams[
    method.operation.pathParams.length - 1
  ];
  const idRef = idParam
    ? `args.${sanitizeFieldName(idParam.name)}`
    : '"unknown"';

  const hasBody = method.operation.requestBody !== undefined;
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];

  const hasQueryParams = queryParamNames.length > 0;
  const queryBuild = hasQueryParams
    ? `\n${indent}    const queryParts: string[] = [];
${indent}    const queryKeys = new Set(${JSON.stringify(queryParamNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (v !== undefined && queryKeys.has(k)) queryParts.push(\`\${k}=\${encodeURIComponent(String(v))}\`);
${indent}    }
${indent}    const qs = queryParts.length > 0 ? \`?\${queryParts.join("&")}\` : "";`
    : "";
  const pathSuffix = hasQueryParams ? "${qs}" : "";

  // Determine how to build the request body, matching the same array/oneOf/
  // properties priority as generateArgsSchema so the declared arguments and
  // the value actually sent agree.
  let bodySetup = "";
  let bodyArg = "";
  const reqBody = method.operation.requestBody;
  if (hasBody && reqBody?.type === "array") {
    bodySetup = `\n${indent}    const body = args.items;\n`;
    bodyArg = `\n${indent}      body,`;
  } else if (hasBody && reqBody?.oneOf) {
    bodySetup = `\n${indent}    const body = args.body;\n`;
    bodyArg = `\n${indent}      body,`;
  } else if (hasBody && excludeNames.length > 0) {
    bodySetup = `\n${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set(${JSON.stringify(excludeNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }\n`;
    bodyArg = `\n${indent}      body,`;
  } else if (hasBody) {
    bodyArg = `\n${indent}      args,`;
  }

  return `${bodySetup}${queryBuild}
${indent}    await cfApi(
${indent}      apiToken,
${indent}      "DELETE",
${indent}      \`${apiPath}${pathSuffix}\`,${bodyArg}
${indent}    );
${indent}
${indent}    context.logger.info("Deleted resource {id}", { id: ${idRef} });
${indent}    return { dataHandles: [] };`;
}

/** Generate action method body */
function generateActionBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = method.name.replace(/^action_/, "");
  const httpMethod = method.operation.httpMethod.toUpperCase();
  const hasBody = method.operation.requestBody !== undefined;
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];

  const hasQueryParams = queryParamNames.length > 0;
  const queryBuild = hasQueryParams
    ? `\n${indent}    const queryParts: string[] = [];
${indent}    const queryKeys = new Set(${JSON.stringify(queryParamNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (v !== undefined && queryKeys.has(k)) queryParts.push(\`\${k}=\${encodeURIComponent(String(v))}\`);
${indent}    }
${indent}    const qs = queryParts.length > 0 ? \`?\${queryParts.join("&")}\` : "";`
    : "";
  const pathSuffix = hasQueryParams ? "${qs}" : "";

  let bodySetup = "";
  let bodyArg = "";
  const reqBody = method.operation.requestBody;
  if (hasBody && reqBody?.type === "array") {
    bodySetup = `\n${indent}    const body = args.items;\n`;
    bodyArg = `\n${indent}      body,`;
  } else if (hasBody && reqBody?.oneOf) {
    bodySetup = `\n${indent}    const body = args.body;\n`;
    bodyArg = `\n${indent}      body,`;
  } else if (hasBody && excludeNames.length > 0) {
    bodySetup = `\n${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set(${JSON.stringify(excludeNames)});
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }\n`;
    bodyArg = `\n${indent}      body,`;
  } else if (hasBody) {
    bodyArg = `\n${indent}      args,`;
  }

  return `${bodySetup}${queryBuild}
${indent}    const result = await cfApi<Record<string, unknown>>(
${indent}      apiToken,
${indent}      "${httpMethod}",
${indent}      \`${apiPath}${pathSuffix}\`,${bodyArg}
${indent}    );
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", "latest", result ?? {});
${indent}    context.logger.info("Executed ${method.name}", {});
${indent}    return { dataHandles: [handle] };`;
}

/** Build the API path with template literal substitution */
function buildApiPath(path: string, scope: string): string {
  // Single-pass replacement: scope params → globalArgs vars, others → args refs.
  // Handle BOTH account_id and zone_id in case a service spans both scopes —
  // the primary scope determines which is in globalArgs, the other becomes a
  // method arg if present.
  const primaryParam = scope === "account" ? "account_id" : "zone_id";
  const primaryVar = scope === "account" ? "accountId" : "zoneId";

  return path.replace(/\{([^}]+)\}/g, (_, name) => {
    if (name === primaryParam) {
      return `\${${primaryVar}}`;
    }
    // Secondary scope param (e.g., zone_id in an account-scoped service)
    // becomes an args reference — the method's globalArgs won't have it
    if (name === "account_id") {
      return `\${args.account_id}`;
    }
    if (name === "zone_id") {
      return `\${args.zone_id}`;
    }
    return `\${args.${sanitizeFieldName(name)}}`;
  });
}

function sanitizeFieldName(name: string): string {
  // Replace special characters with underscores, collapse multiples
  return name
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .replace(/^\d/, "_$&"); // prefix leading digit with underscore
}

/**
 * True when a method's generated body references sanitizeInstanceName. This
 * MUST stay in lockstep with the body generators:
 *   - create: always (wraps the API-returned id, falling back to "created")
 *   - get / update: only when a trailing path param supplies the instance id
 *     (otherwise the body uses the constant "latest"/"updated")
 *   - list ("main"), action ("latest"), delete (no resource): never
 */
function methodEmitsSanitize(method: ClassifiedMethod): boolean {
  if (method.type === "create") return true;
  if (method.type === "get" || method.type === "update") {
    return method.operation.pathParams.length > 0;
  }
  return false;
}

function toPascalCase(name: string): string {
  return name
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

/**
 * Append `.passthrough()` to a generated object schema so unknown API-returned
 * fields survive validation instead of being stripped. Output/resource schemas
 * describe observed reality, which the spec never fully captures, so unknown
 * fields must pass through. Only applies to a top-level `z.object({...})`; other
 * shapes (records, unions, unknown) are returned unchanged.
 */
function withPassthrough(zodExpr: string): string {
  if (!zodExpr.startsWith("z.object({")) return zodExpr;
  // `.passthrough()` must attach to the ZodObject, not a wrapper: a nullable
  // object is `z.object({...}).nullable()` and ZodNullable has no
  // `.passthrough()`. Insert before the trailing `.nullable()` in that case.
  if (zodExpr.endsWith(".nullable()")) {
    return `${
      zodExpr.slice(0, -".nullable()".length)
    }.passthrough().nullable()`;
  }
  return `${zodExpr}.passthrough()`;
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ");
}

function truncateStr(s: string): string {
  const oneLine = s.replace(/\s+/g, " ").trim();
  return oneLine.length <= 80 ? oneLine : oneLine.slice(0, 77) + "...";
}
