// fal.ai API Keys — key management — Tests
// Auto-generated by scripts/falai-codegen — do not edit manually.
// SPDX-License-Identifier: Apache-2.0

import { assertEquals, assertExists } from "jsr:@std/assert@1.0.19";
import { createModelTestContext } from "@systeminit/swamp-testing";
import { model } from "./keys.ts";

// ---------------------------------------------------------------------------
// Model Export Structure Tests
// ---------------------------------------------------------------------------

Deno.test("keys model: has correct type", () => {
  assertEquals(model.type, "@webframp/falai/keys");
});

Deno.test("keys model: has valid version format", () => {
  const versionPattern = /^\d{4}\.\d{2}\.\d{2}\.\d+$/;
  assertEquals(versionPattern.test(model.version), true);
});

Deno.test("keys model: has globalArguments with apiToken", () => {
  assertExists(model.globalArguments);
  const shape = model.globalArguments.shape;
  assertExists(shape.apiToken);
});

Deno.test("keys model: has expected methods", () => {
  assertExists(model.methods);
  assertExists(model.methods.list_api_keys);
  assertExists(model.methods.create_api_key);
  assertExists(model.methods.delete_api_key);
});

Deno.test("keys model: has expected resources", () => {
  assertExists(model.resources);
  assertExists(model.resources["api_keys"]);
  assertExists(model.resources["api_key"]);
});

// ---------------------------------------------------------------------------
// Mock fal.ai API Server
// ---------------------------------------------------------------------------

function startMockFalServer(
  responses: Record<string, { body: unknown }>,
): { url: string; server: Deno.HttpServer } {
  const server = Deno.serve({ port: 0, onListen() {} }, (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    for (const [pattern, { body }] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        return Response.json(body);
      }
    }

    return Response.json(
      { error: { type: "not_found", message: "Not found" } },
      { status: 404 },
    );
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: `http://localhost:${addr.port}`, server };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    const newUrl = reqUrl.replace("https://api.fal.ai/v1", mockUrl);
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}

Deno.test({
  name: "keys model: list_api_keys fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockBody = {
      "keys": [{
        "key_id": "abc123def456",
        "alias": "Production Key",
        "scope": "API",
        "created_at": "2025-01-15T12:00:00Z",
        "creator_nickname": "developer",
        "creator_email": "developer@example.com",
      }],
    };
    const { url, server } = startMockFalServer({
      "/keys": { body: mockBody },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token" },
        definition: { id: "test-id", name: "test-keys", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).list_api_keys.execute({}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "keys model: create_api_key creates and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockBody = {
      "id": "new-123",
      "key_id": "abc123def456",
      "key_secret": "sk_live_abc123...",
      "key": "abc123def456:sk_live_abc123...",
    };
    const { url, server } = startMockFalServer({
      "/keys": { body: mockBody },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token" },
        definition: { id: "test-id", name: "test-keys", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).create_api_key.execute({
        "key_id": "abc123def456",
        "key_secret": "sk_live_abc123...",
        "key": "abc123def456:sk_live_abc123...",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "keys model: delete_api_key executes successfully",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockFalServer({
      "/keys/test-id-123": { body: { id: "test-id-123" } },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: { "apiToken": "test-token" },
        definition: { id: "test-id", name: "test-keys", version: 1, tags: {} },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).delete_api_key.execute({ "key_id": "test-id-123" }, context);
      assertEquals(result.dataHandles.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});
