// Snyk Projects — project listing, attributes, relationships, and target management — Tests
// Auto-generated by scripts/snyk-codegen — do not edit manually.
// SPDX-License-Identifier: Apache-2.0

import { assertEquals, assertExists } from "jsr:@std/assert@1";
import { createModelTestContext } from "@systeminit/swamp-testing";
import { model } from "./projects.ts";

// ---------------------------------------------------------------------------
// Model Export Structure Tests
// ---------------------------------------------------------------------------

Deno.test("projects model: has correct type", () => {
  assertEquals(model.type, "@webframp/snyk/projects");
});

Deno.test("projects model: has valid version format", () => {
  const versionPattern = /^\d{4}\.\d{2}\.\d{2}\.\d+$/;
  assertEquals(versionPattern.test(model.version), true);
});

Deno.test("projects model: has globalArguments with apiToken", () => {
  assertExists(model.globalArguments);
  const shape = model.globalArguments.shape;
  assertExists(shape.apiToken);
  assertExists(shape.orgId);
  assertExists(shape.version);
});

Deno.test("projects model: has expected methods", () => {
  assertExists(model.methods);
  assertExists(model.methods.list_org_projects);
  assertExists(model.methods.get_org_project);
  assertExists(model.methods.update_org_project);
  assertExists(model.methods.delete_org_project);
  assertExists(model.methods.get_sbom);
});

Deno.test("projects model: has expected resources", () => {
  assertExists(model.resources);
  assertExists(model.resources["org_projects"]);
  assertExists(model.resources["org_project"]);
  assertExists(model.resources["sbom"]);
});

// ---------------------------------------------------------------------------
// Mock Snyk API Server
// ---------------------------------------------------------------------------

function startMockSnykServer(
  responses: Record<string, { data: unknown; isCollection?: boolean }>,
): { url: string; server: Deno.HttpServer } {
  const server = Deno.serve({ port: 0, onListen() {} }, (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    for (const [pattern, { data, isCollection }] of Object.entries(responses)) {
      if (path.includes(pattern)) {
        const body = isCollection
          ? {
            data: Array.isArray(data) ? data : [data],
            jsonapi: { version: "1.0" },
            links: { self: path, next: null },
          }
          : {
            data,
            jsonapi: { version: "1.0" },
            links: { self: path },
          };
        return Response.json(body, {
          headers: { "content-type": "application/vnd.api+json" },
        });
      }
    }

    return new Response(
      JSON.stringify({
        jsonapi: { version: "1.0" },
        errors: [{ status: "404", detail: "Not found" }],
      }),
      { status: 404, headers: { "content-type": "application/vnd.api+json" } },
    );
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: `http://localhost:${addr.port}`, server };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    const newUrl = reqUrl.replace("https://api.snyk.io/rest", mockUrl);
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}

Deno.test({
  name: "projects model: list_org_projects fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockItem = {
      "id": "fixture-123",
      "type": "resource",
      "attributes": {
        "build_args": null,
        "business_criticality": ["medium"],
        "created": "2021-05-29T09:50:54.014Z",
        "environment": ["external", "hosted"],
        "lifecycle": ["production"],
        "name": "snyk/goof",
        "origin": "github",
        "read_only": true,
        "settings": {
          "auto_dependency_upgrade": null,
          "auto_remediation_prs": null,
          "manual_remediation_prs": null,
          "pull_request_assignment": null,
          "pull_requests": null,
          "recurring_tests": null,
        },
        "status": "active",
        "tags": [{ "key": "tag-key", "value": "tag-value" }],
        "target_file": "package.json",
        "target_reference": "main",
        "target_runtime": "test-value",
        "importer_id": "test-value",
        "organization_id": "test-value",
        "owner_id": "test-value",
        "target_id": "test-value",
      },
    };
    const { url, server } = startMockSnykServer({
      "/projects": { data: [mockItem], isCollection: true },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "orgId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-projects",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).list_org_projects.execute({}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "projects model: get_org_project fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "id": "fixture-123",
      "type": "resource",
      "attributes": {
        "build_args": null,
        "business_criticality": ["medium"],
        "created": "2021-05-29T09:50:54.014Z",
        "environment": ["external", "hosted"],
        "lifecycle": ["production"],
        "name": "snyk/goof",
        "origin": "github",
        "read_only": true,
        "settings": {
          "auto_dependency_upgrade": null,
          "auto_remediation_prs": null,
          "manual_remediation_prs": null,
          "pull_request_assignment": null,
          "pull_requests": null,
          "recurring_tests": null,
        },
        "status": "active",
        "tags": [{ "key": "tag-key", "value": "tag-value" }],
        "target_file": "package.json",
        "target_reference": "main",
        "target_runtime": "test-value",
        "importer_id": "test-value",
        "organization_id": "test-value",
        "owner_id": "test-value",
        "target_id": "test-value",
      },
    };
    const { url, server } = startMockSnykServer({
      "/projects/test-id-123": { data: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "orgId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-projects",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).get_org_project.execute({ "project_id": "test-id-123" }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "projects model: update_org_project executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "id": "fixture-123",
      "type": "resource",
      "attributes": {
        "build_args": null,
        "business_criticality": ["medium"],
        "created": "2021-05-29T09:50:54.014Z",
        "environment": ["external", "hosted"],
        "lifecycle": ["production"],
        "name": "snyk/goof",
        "origin": "github",
        "read_only": true,
        "settings": {
          "auto_dependency_upgrade": null,
          "auto_remediation_prs": null,
          "manual_remediation_prs": null,
          "pull_request_assignment": null,
          "pull_requests": null,
          "recurring_tests": null,
        },
        "status": "active",
        "tags": [{ "key": "tag-key", "value": "tag-value" }],
        "target_file": "package.json",
        "target_reference": "main",
        "target_runtime": "test-value",
        "importer_id": "test-value",
        "organization_id": "test-value",
        "owner_id": "test-value",
        "target_id": "test-value",
      },
    };
    const { url, server } = startMockSnykServer({
      "/projects/test-id-123": { data: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "orgId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-projects",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).update_org_project.execute({
        "project_id": "test-id-123",
        "name": "test-resource",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "projects model: delete_org_project executes successfully",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockSnykServer({
      "/projects/test-id-123": {
        data: { id: "test-id-123", type: "resource" },
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: {
          "apiToken": "test-token",
          "version": "2024-10-15",
          "orgId": "test-org-123",
        },
        definition: {
          id: "test-id",
          name: "test-projects",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).delete_org_project.execute({ "project_id": "test-id-123" }, context);
      assertEquals(result.dataHandles.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});
