// Cloudflare Workers Scripts — upload, deploy, bindings, routes, cron triggers — Tests
// Auto-generated by scripts/cloudflare-codegen — do not edit manually.
// SPDX-License-Identifier: Apache-2.0

import { assertEquals, assertExists } from "jsr:@std/assert@1.0.19";
import { createModelTestContext } from "@systeminit/swamp-testing";
import { model } from "./workers_scripts.ts";

// ---------------------------------------------------------------------------
// Model Export Structure Tests
// ---------------------------------------------------------------------------

Deno.test("workers-scripts model: has correct type", () => {
  assertEquals(model.type, "@webframp/cloudflare/workers-scripts");
});

Deno.test("workers-scripts model: has valid version format", () => {
  const versionPattern = /^\d{4}\.\d{2}\.\d{2}\.\d+$/;
  assertEquals(versionPattern.test(model.version), true);
});

Deno.test("workers-scripts model: has globalArguments with apiToken", () => {
  assertExists(model.globalArguments);
  const shape = model.globalArguments.shape;
  assertExists(shape.apiToken);
  assertExists(shape.accountId);
});

Deno.test("workers-scripts model: has expected methods", () => {
  assertExists(model.methods);
  assertExists(model.methods.list_workers);
  assertExists(model.methods.list_worker_script_search_workers);
  assertExists(model.methods.update_worker_script_upload_worker_module);
  assertExists(model.methods.delete_worker);
  assertExists(model.methods.create_assets_upload_session);
  assertExists(model.methods.put_content);
  assertExists(model.methods.list_deployments);
  assertExists(model.methods.create_deployment);
  assertExists(model.methods.get_deployment);
  assertExists(model.methods.delete_deployment);
  assertExists(model.methods.get_cron_triggers);
  assertExists(model.methods.update_cron_triggers);
  assertExists(model.methods.get_settings);
  assertExists(model.methods.patch_settings);
  assertExists(model.methods.list_script_secrets);
  assertExists(model.methods.put_script_secret);
  assertExists(model.methods.patch_script_secrets_bulk);
  assertExists(model.methods.get_script_secret);
  assertExists(model.methods.delete_script_secret);
  assertExists(model.methods.get_subdomain);
  assertExists(model.methods.create_worker_script_post_subdomain);
  assertExists(model.methods.delete_subdomain);
  assertExists(model.methods.list_tails);
  assertExists(model.methods.worker_tail_logs_start_tail);
  assertExists(model.methods.delete_tail);
  assertExists(model.methods.get_worker_script_fetch_usage_model);
  assertExists(model.methods.update_usage_model);
  assertExists(model.methods.list_versions);
  assertExists(model.methods.worker_versions_upload_version);
  assertExists(model.methods.get_version_detail);
  assertExists(model.methods.put_script_content);
});

Deno.test("workers-scripts model: has expected resources", () => {
  assertExists(model.resources);
  assertExists(model.resources["workers"]);
  assertExists(model.resources["worker_script_search_workers"]);
  assertExists(model.resources["worker_script_upload_worker_module"]);
  assertExists(model.resources["assets_upload_session"]);
  assertExists(model.resources["put_content"]);
  assertExists(model.resources["list_deployments"]);
  assertExists(model.resources["deployment"]);
  assertExists(model.resources["cron_triggers"]);
  assertExists(model.resources["settings"]);
  assertExists(model.resources["patch_settings"]);
  assertExists(model.resources["script_secrets"]);
  assertExists(model.resources["put_script_secret"]);
  assertExists(model.resources["patch_script_secrets_bulk"]);
  assertExists(model.resources["script_secret"]);
  assertExists(model.resources["subdomain"]);
  assertExists(model.resources["worker_script_post_subdomain"]);
  assertExists(model.resources["list_tails"]);
  assertExists(model.resources["worker_tail_logs_start_tail"]);
  assertExists(model.resources["worker_script_fetch_usage_model"]);
  assertExists(model.resources["usage_model"]);
  assertExists(model.resources["list_versions"]);
  assertExists(model.resources["worker_versions_upload_version"]);
  assertExists(model.resources["version_detail"]);
  assertExists(model.resources["put_script_content"]);
});

// ---------------------------------------------------------------------------
// Mock Cloudflare API Server
// ---------------------------------------------------------------------------

function startMockCfServer(
  responses: Record<string, { result: unknown; isCollection?: boolean }>,
): { url: string; server: Deno.HttpServer } {
  const server = Deno.serve({ port: 0, onListen() {} }, (req) => {
    const url = new URL(req.url);
    const path = url.pathname;

    for (
      const [pattern, { result, isCollection }] of Object.entries(responses)
    ) {
      if (path.includes(pattern)) {
        return Response.json({
          success: true,
          errors: [],
          messages: [],
          result,
          result_info: isCollection
            ? {
              page: 1,
              per_page: 50,
              total_count: Array.isArray(result) ? result.length : 1,
              total_pages: 1,
            }
            : undefined,
        });
      }
    }

    return Response.json({
      success: false,
      errors: [{ code: 404, message: "Not found" }],
      messages: [],
      result: null,
    });
  });

  const addr = server.addr as Deno.NetAddr;
  return { url: `http://localhost:${addr.port}`, server };
}

function installFetchMock(mockUrl: string): () => void {
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (input, init) => {
    const reqUrl = typeof input === "string" ? input : input.toString();
    const newUrl = reqUrl.replace(
      "https://api.cloudflare.com/client/v4",
      mockUrl,
    );
    return originalFetch(newUrl, init);
  };
  return () => {
    globalThis.fetch = originalFetch;
  };
}

Deno.test({
  name: "workers-scripts model: list_workers fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = [{
      "cache_options": null,
      "compatibility_date": null,
      "compatibility_flags": null,
      "created_on": null,
      "etag": null,
      "exports": null,
      "handlers": ["fetch", "scheduled"],
      "has_assets": null,
      "has_modules": null,
      "id": "my-workers-script",
      "last_deployed_from": "wrangler",
      "logpush": null,
      "migration_tag": "v1",
      "modified_on": null,
      "named_handlers": [{ "handlers": ["class"], "name": "MyDurableObject" }],
      "observability": null,
      "placement": null,
      "placement_mode": null,
      "placement_status": null,
      "tag": "e8f70fdbc8b1fb0b8ddb1af166186758",
      "tags": null,
      "tail_consumers": null,
      "usage_model": null,
      "routes": [null],
    }];
    const { url, server } = startMockCfServer({
      "/workers/scripts": { result: mockData, isCollection: true },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-workers-scripts",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).list_workers.execute({}, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "workers-scripts model: update_worker_script_upload_worker_module executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "cache_options": null,
      "compatibility_date": null,
      "compatibility_flags": null,
      "created_on": null,
      "etag": null,
      "exports": null,
      "handlers": ["fetch", "scheduled"],
      "has_assets": null,
      "has_modules": null,
      "id": "my-workers-script",
      "last_deployed_from": "wrangler",
      "logpush": null,
      "migration_tag": "v1",
      "modified_on": null,
      "named_handlers": [{ "handlers": ["class"], "name": "MyDurableObject" }],
      "observability": null,
      "placement": null,
      "placement_mode": null,
      "placement_status": null,
      "tag": "e8f70fdbc8b1fb0b8ddb1af166186758",
      "tags": null,
      "tail_consumers": null,
      "usage_model": null,
      "entry_point": "index.js",
      "startup_time_ms": 10,
    };
    const { url, server } = startMockCfServer({
      "/workers/scripts/test-id-123": { result: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-workers-scripts",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).update_worker_script_upload_worker_module.execute({
        "script_name": "test-id-123",
        "cache_options": null,
        "compatibility_date": null,
        "compatibility_flags": null,
        "created_on": null,
        "etag": null,
        "exports": null,
        "handlers": ["fetch", "scheduled"],
        "has_assets": null,
        "has_modules": null,
        "id": "my-workers-script",
        "last_deployed_from": "wrangler",
        "logpush": null,
        "migration_tag": "v1",
        "modified_on": null,
        "named_handlers": [{
          "handlers": ["class"],
          "name": "MyDurableObject",
        }],
        "observability": null,
        "placement": null,
        "placement_mode": null,
        "placement_status": null,
        "tag": "e8f70fdbc8b1fb0b8ddb1af166186758",
        "tags": null,
        "tail_consumers": null,
        "usage_model": null,
        "entry_point": "index.js",
        "startup_time_ms": 10,
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "workers-scripts model: delete_worker executes successfully",
  sanitizeResources: false,
  fn: async () => {
    const { url, server } = startMockCfServer({
      "/workers/scripts/test-id-123": { result: { id: "test-id-123" } },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-workers-scripts",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).delete_worker.execute({ "script_name": "test-id-123" }, context);
      assertEquals(result.dataHandles.length, 0);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "workers-scripts model: create_assets_upload_session creates and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "id": "new-123",
      "buckets": [["test-value"]],
      "jwt": "test-value",
    };
    const { url, server } = startMockCfServer({
      "/workers/scripts/test-id-123/assets-upload-session": {
        result: mockData,
      },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-workers-scripts",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).create_assets_upload_session.execute({
        "script_name": "test-id-123",
        "buckets": [["test-value"]],
        "jwt": "test-value",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name: "workers-scripts model: list_deployments fetches and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = { "deployments": [null] };
    const { url, server } = startMockCfServer({
      "/workers/scripts/test-id-123/deployments": { result: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-workers-scripts",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).list_deployments.execute({ "script_name": "test-id-123" }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});

Deno.test({
  name:
    "workers-scripts model: worker_tail_logs_start_tail executes and writes resource",
  sanitizeResources: false,
  fn: async () => {
    const mockData = {
      "expires_at": "test-value",
      "id": null,
      "url": "test-value",
    };
    const { url, server } = startMockCfServer({
      "/workers/scripts/test-id-123/tails": { result: mockData },
    });
    const uninstall = installFetchMock(url);

    try {
      const { context, getWrittenResources } = createModelTestContext({
        globalArgs: { "apiToken": "test-token", "accountId": "acct-123" },
        definition: {
          id: "test-id",
          name: "test-workers-scripts",
          version: 1,
          tags: {},
        },
      });

      const result = await (model.methods as Record<
        string,
        {
          execute: (
            args: Record<string, unknown>,
            ctx: unknown,
          ) => Promise<{ dataHandles: unknown[] }>;
        }
      >).worker_tail_logs_start_tail.execute({
        "script_name": "test-id-123",
        "expires_at": "test-value",
        "id": null,
        "url": "test-value",
      }, context);
      assertEquals(result.dataHandles.length, 1);

      const resources = getWrittenResources();
      assertEquals(resources.length, 1);
    } finally {
      uninstall();
      await server.shutdown();
    }
  },
});
