/**
 * Method classifier — determines the swamp method type for each operation
 * and generates the model source code.
 *
 * Classifies operations as:
 * - list: GET returning a collection
 * - get: GET returning a single item (path ends with {id})
 * - create: POST that creates a resource
 * - update: PUT/PATCH that modifies a resource
 * - delete: DELETE
 * - action: POST that performs an action (not a standard CRUD create)
 */

import type { GroupedOperation, ServiceGroup } from "./service_grouper.ts";
import type { ParameterObject } from "./schema_fetcher.ts";
import { schemaToZod, truncateAtBoundary } from "./type_mapper.ts";
import { ZOD_VERSION } from "../config.ts";
import type { ServiceConfig } from "../config.ts";

export type MethodType =
  | "list"
  | "get"
  | "create"
  | "update"
  | "delete"
  | "action";

export interface ClassifiedMethod {
  /** swamp method name (e.g., list_projects, get_project, create_project) */
  name: string;
  /** The classification */
  type: MethodType;
  /** Description for the method */
  description: string;
  /** The original operation */
  operation: GroupedOperation;
}

/**
 * The resource spec a method reads or writes. Every site that declares,
 * writes, or tests a resource MUST derive the name here: a method's verb
 * prefix need not match its type (a POST with a body is a "create" even when
 * the operation is named `update_*`), and a body generator that strips only
 * its own type's prefix would write to a spec the model never declared.
 */
export function resourceNameOf(
  method: Pick<ClassifiedMethod, "name" | "type">,
): string {
  return method.type === "list"
    ? method.name.replace(/^list_/, "")
    : method.name.replace(/^(get|create|update|action)_/, "");
}

/**
 * Classify an operation into a swamp method type.
 */
export function classifyOperation(op: GroupedOperation): MethodType {
  const { httpMethod, isCollection } = op;

  switch (httpMethod) {
    case "get":
      if (isCollection) return "list";
      return "get";
    case "post": {
      const lastSegment = op.path.split("/").pop() ?? "";
      if (lastSegment.startsWith("{")) return "action";
      if (op.requestBody?.properties) return "create";
      return "action";
    }
    case "put":
    case "patch":
      return "update";
    case "delete":
      return "delete";
    default:
      return "action";
  }
}

/**
 * Generate a method name from the operation.
 */
export function generateMethodName(
  op: GroupedOperation,
  type: MethodType,
): string {
  if (op.operationId) {
    let name = op.operationId.replace(/-/g, "_").replace(/\./g, "_");

    // Snyk operationIds look like "getOrgProjects" or "listProjectIssues"
    // Convert camelCase to snake_case
    name = name.replace(/([a-z])([A-Z])/g, "$1_$2").toLowerCase();

    // Remove common prefixes that duplicate the verb
    const verbPrefixes = [
      "list",
      "get",
      "create",
      "update",
      "delete",
      "patch",
    ];
    const hasVerb = verbPrefixes.some((v) => name.startsWith(`${v}_`));
    if (!hasVerb && type !== "action") {
      name = `${type}_${name}`;
    }

    return sanitizeMethodName(name);
  }

  // Fallback: construct from path
  const segments = op.path.split("/").filter((s) => s && !s.startsWith("{"));
  const lastSegments = segments.slice(-2);
  const resource = lastSegments.join("_");
  return sanitizeMethodName(`${type}_${resource}`);
}

function sanitizeMethodName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .toLowerCase();
}

/**
 * Classify all operations in a service group into methods.
 * De-duplicates by method name (first wins).
 */
export function classifyServiceMethods(
  group: ServiceGroup,
): ClassifiedMethod[] {
  const methods: ClassifiedMethod[] = [];
  const seen = new Set<string>();

  for (const op of group.operations) {
    const type = classifyOperation(op);
    const name = generateMethodName(op, type);

    if (seen.has(name)) continue;
    seen.add(name);

    methods.push({
      name,
      type,
      description: op.summary || op.description || `${type} operation`,
      operation: op,
    });
  }

  return methods;
}

/**
 * Generate the complete model TypeScript source file for a service.
 */
export function generateModelSource(
  group: ServiceGroup,
  methods: ClassifiedMethod[],
  version: string,
  upgradesBlock = "  upgrades: [],",
): string {
  const { config } = group;
  const modelType = `@webframp/snyk/${config.name}`;

  const lines: string[] = [];

  // Header
  lines.push(`/**`);
  lines.push(` * ${config.description}`);
  lines.push(` *`);
  lines.push(
    ` * Auto-generated by scripts/snyk-codegen — do not edit manually.`,
  );
  lines.push(` *`);
  lines.push(` * @module`);
  lines.push(` */`);
  lines.push(
    `// SPDX-License-Identifier: Apache-2.0`,
  );
  lines.push(``);
  lines.push(`import { z } from "npm:zod@${ZOD_VERSION}";`);

  // Import API helpers based on what's used
  const usesSingle = methods.some((m) => m.type !== "list");
  const usesPaginated = methods.some(
    (m) => m.type === "list" && m.operation.usesCursorPagination,
  );
  const usesSimpleList = methods.some(
    (m) => m.type === "list" && !m.operation.usesCursorPagination,
  );
  const apiImports: string[] = [];
  if (usesSingle) apiImports.push("snykApi");
  if (usesPaginated || usesSimpleList) apiImports.push("snykApiPaginated");
  // Every list method builds its query with queryEntries; other methods use it
  // (via toQueryString) only when the operation declares query parameters.
  const usesQuery = methods.some((m) => m.operation.queryParams.length > 0);
  if (usesPaginated || usesSimpleList || usesQuery) {
    apiImports.push("queryEntries");
  }
  if (methods.some(requiresBody)) apiImports.push("requireBody");
  if (
    methods.some((m) => m.type !== "list" && m.operation.queryParams.length > 0)
  ) {
    apiImports.push("toQueryString");
  }
  // sanitizeInstanceName is emitted only by bodies that build an instance name
  // from an API-influenced value: every `create`, and any `get`/`update`
  // targeting a resource by a path id. `list` and `action` use constant
  // instance names and never call it. Import it only when a body actually
  // references it, or deno lint fails with no-unused-vars.
  const usesSanitize = methods.some(methodEmitsSanitize);
  if (usesSanitize) apiImports.push("sanitizeInstanceName");
  if (apiImports.length > 0) {
    lines.push(
      `import { ${apiImports.join(", ")} } from "./_lib/api.ts";`,
    );
  }
  lines.push(``);
  // EXTENSION_NAME is referenced by list method bodies (collectedBy metadata).
  // Only emit it when a list method exists, or it would be an unused const.
  const hasListMethod = methods.some((m) => m.type === "list");
  if (hasListMethod) {
    lines.push(`const EXTENSION_NAME = "${modelType}";`);
    lines.push(``);
  }

  // Schemas section
  lines.push(
    `// =============================================================================`,
  );
  lines.push(`// Schemas`);
  lines.push(
    `// =============================================================================`,
  );
  lines.push(``);

  // GlobalArgs
  lines.push(generateGlobalArgsSchema(config));
  lines.push(``);

  // Generate response schemas
  const schemaNames = generateResponseSchemas(methods, lines);

  // Model definition
  lines.push(
    `// =============================================================================`,
  );
  lines.push(`// Model Definition`);
  lines.push(
    `// =============================================================================`,
  );
  lines.push(``);
  lines.push(`/** ${config.description} */`);
  lines.push(`export const model = {`);
  lines.push(`  type: "${modelType}",`);
  lines.push(`  version: "${version}",`);
  lines.push(`  globalArguments: GlobalArgsSchema,`);
  lines.push(``);
  lines.push(upgradesBlock);
  lines.push(``);

  // Resources
  lines.push(`  resources: {`);
  const seenResources = new Set<string>();
  for (const method of methods) {
    if (method.type === "delete") continue;
    const resourceName = resourceNameOf(method);
    if (seenResources.has(resourceName)) continue;
    seenResources.add(resourceName);
    lines.push(`    "${resourceName}": {`);
    lines.push(
      `      description: "${escapeStr(method.description)}",`,
    );
    lines.push(
      `      schema: ${schemaNames.get(method.name) ?? "z.object({})"},`,
    );
    lines.push(`      lifetime: "infinite" as const,`);
    lines.push(
      `      garbageCollection: ${method.type === "list" ? 10 : 20},`,
    );
    lines.push(`    },`);
  }
  lines.push(`  },`);
  lines.push(``);

  // Methods
  lines.push(`  methods: {`);
  for (const method of methods) {
    lines.push(generateMethod(method, config, schemaNames));
  }
  lines.push(`  },`);
  lines.push(`};`);
  lines.push(``);

  return lines.join("\n");
}

/** Generate GlobalArgsSchema based on service scope */
function generateGlobalArgsSchema(config: ServiceConfig): string {
  const lines = [`const GlobalArgsSchema = z.object({`];
  lines.push(
    `  apiToken: z.string().meta({ sensitive: true }).describe("Snyk API token"),`,
  );

  if (config.scope === "org") {
    lines.push(
      `  orgId: z.string().describe("Snyk organization ID"),`,
    );
  } else if (config.scope === "group") {
    lines.push(
      `  groupId: z.string().describe("Snyk group ID"),`,
    );
  }

  lines.push(
    `  version: z.string().default("2024-10-15").describe("Snyk API version date"),`,
  );
  lines.push(`});`);
  return lines.join("\n");
}

/** Schema for a resource nothing declares a response shape for. */
const OPEN_OBJECT = "z.object({}).passthrough()";

/**
 * Generate Zod schemas for every resource, keyed back to each method.
 *
 * Several methods can write one resource (list_x, get_x, create_x). A list
 * writes the {items, truncated, ...} wrapper and the others write a flat
 * object, so a single shared schema built from whichever method comes first
 * rejects the other writers' data. A resource with both kinds therefore gets a
 * union of the wrapper and the flat shape, and the flat shape comes from the
 * first writer that actually declares a response schema.
 */
function generateResponseSchemas(
  methods: ClassifiedMethod[],
  lines: string[],
): Map<string, string> {
  const schemaNames = new Map<string, string>();

  const writersByResource = new Map<string, ClassifiedMethod[]>();
  for (const method of methods) {
    if (method.type === "delete") continue;
    const resourceName = resourceNameOf(method);
    const writers = writersByResource.get(resourceName) ?? [];
    writers.push(method);
    writersByResource.set(resourceName, writers);
  }

  for (const [, writers] of writersByResource) {
    const listWriter = writers.find((m) => m.type === "list");
    const flatWriter = writers.find((m) =>
      m.type !== "list" && m.operation.responseSchema
    );

    let listExpr: string | undefined;
    if (listWriter) {
      const varName = toPascalCase(listWriter.name) + "Schema";
      const itemVarName = toPascalCase(listWriter.name.replace(/^list_/, "")) +
        "ItemSchema";
      const schema = listWriter.operation.responseSchema;
      const itemZod = schema
        ? withPassthrough(schemaToZod(schema, { indent: 2, lenient: true }, 1))
        : OPEN_OBJECT;
      lines.push(`const ${itemVarName} = ${itemZod};`);
      lines.push(``);
      lines.push(`const ${varName} = z.object({`);
      lines.push(`  items: z.array(${itemVarName}),`);
      lines.push(`  truncated: z.boolean(),`);
      lines.push(`  fetchedAt: z.string(),`);
      lines.push(
        `  durationMs: z.number().optional().describe(`,
      );
      lines.push(`    "Method execution duration in milliseconds",`);
      lines.push(`  ),`);
      lines.push(
        `  collectedBy: z.string().optional().describe(`,
      );
      lines.push(`    "Extension that collected this data",`);
      lines.push(`  ),`);
      lines.push(`});`);
      lines.push(``);
      listExpr = varName;
    }

    let flatExpr: string | undefined;
    if (flatWriter) {
      const varName = toPascalCase(flatWriter.name) + "Schema";
      const zodStr = withPassthrough(
        schemaToZod(flatWriter.operation.responseSchema!, {
          indent: 2,
          lenient: true,
        }, 1),
      );
      lines.push(`const ${varName} = ${zodStr};`);
      lines.push(``);
      flatExpr = varName;
    }

    // Wrapper first: list data matches it; flat data falls through to the
    // second member. The flat shape is all-optional, so it also tolerates the
    // empty object a 204 writes.
    // A non-list writer without a declared response (a 204 create) still
    // writes an object, so it counts as a flat writer with an open shape.
    const hasFlatWriter = writers.some((m) => m.type !== "list");
    if (!flatExpr && hasFlatWriter) flatExpr = OPEN_OBJECT;
    const expr = listExpr && flatExpr
      ? `z.union([${listExpr}, ${flatExpr}])`
      : (listExpr ?? flatExpr ?? OPEN_OBJECT);
    for (const m of writers) schemaNames.set(m.name, expr);
  }

  return schemaNames;
}

/** Determine if a method's execute body references `args` */
function methodUsesArgs(
  method: ClassifiedMethod,
  config: ServiceConfig,
): boolean {
  const { type, operation } = method;
  if (type === "list") return true;
  if (operation.pathParams.length > 0) return true;
  if (type === "create" || type === "update") return true;
  if (type === "action" && operation.requestBody) return true;
  if (operation.queryParams.length > 0) return true;
  // Check if path has secondary scope params that become args references
  const primaryParam = config.scope === "org"
    ? "org_id"
    : config.scope === "group"
    ? "group_id"
    : null;
  const path = operation.path;
  if (primaryParam === "org_id" && path.includes("{group_id}")) return true;
  if (primaryParam === "group_id" && path.includes("{org_id}")) return true;
  return false;
}

/** Generate a single method definition */
function generateMethod(
  method: ClassifiedMethod,
  config: ServiceConfig,
  _schemaNames: Map<string, string>,
): string {
  const { operation, type } = method;
  const lines: string[] = [];
  const indent = "    ";

  lines.push(`${indent}${method.name}: {`);
  lines.push(
    `${indent}  description: "${escapeStr(method.description)}",`,
  );

  // Arguments schema
  lines.push(`${indent}  arguments: ${generateArgsSchema(operation)},`);

  // Execute function
  const argsUsed = methodUsesArgs(method, config);
  const argsParam = argsUsed ? "args" : "_args";
  lines.push(
    `${indent}  execute: async (${argsParam}: Record<string, unknown>, context: { globalArgs: Record<string, string>; writeResource: (spec: string, instance: string, data: unknown) => Promise<{ name: string }>; logger: { info: (msg: string, props: Record<string, unknown>) => void } }) => {`,
  );

  // Destructure globalArgs
  const scopeId = config.scope === "org"
    ? "orgId"
    : config.scope === "group"
    ? "groupId"
    : null;
  const primaryParam = config.scope === "org"
    ? "org_id"
    : config.scope === "group"
    ? "group_id"
    : null;
  const pathUsesScopeVar = primaryParam
    ? operation.path.includes(`{${primaryParam}}`)
    : false;
  if (scopeId && pathUsesScopeVar) {
    lines.push(
      `${indent}    const { apiToken, ${scopeId}, version } = context.globalArgs;`,
    );
  } else {
    lines.push(
      `${indent}    const { apiToken, version } = context.globalArgs;`,
    );
  }

  // Build the API path
  const apiPath = buildApiPath(operation.path, config.scope);

  if (type === "list") {
    lines.push(generateListBody(method, apiPath, indent));
  } else if (type === "get") {
    lines.push(generateGetBody(method, apiPath, indent));
  } else if (type === "create") {
    lines.push(generateCreateBody(method, apiPath, indent));
  } else if (type === "update") {
    lines.push(generateUpdateBody(method, apiPath, indent));
  } else if (type === "delete") {
    lines.push(generateDeleteBody(method, apiPath, indent));
  } else {
    lines.push(generateActionBody(method, apiPath, indent));
  }

  lines.push(`${indent}  },`);
  lines.push(`${indent}},`);

  return lines.join("\n");
}

/** Generate the arguments schema for a method */
function generateArgsSchema(op: GroupedOperation): string {
  const fields: string[] = [];
  const seenFields = new Set<string>();

  // Path params (minus scope)
  for (const p of op.pathParams) {
    const fieldName = sanitizeFieldName(p.name);
    if (seenFields.has(fieldName)) continue;
    seenFields.add(fieldName);
    const desc = p.description
      ? `.describe("${escapeStr(truncateStr(p.description))}")`
      : "";
    fields.push(`  ${fieldName}: z.string()${desc},`);
  }

  // Query params
  for (const p of op.queryParams) {
    const fieldName = sanitizeFieldName(p.name);
    if (seenFields.has(fieldName)) continue;
    seenFields.add(fieldName);
    const desc = p.description
      ? `.describe("${escapeStr(truncateStr(p.description))}")`
      : "";
    let zodType = "z.string()";
    if (isArrayParam(p)) {
      zodType = "z.union([z.string(), z.array(z.string())])";
    } else if (p.schema?.type === "integer" || p.schema?.type === "number") {
      zodType = "z.number()";
    } else if (p.schema?.type === "boolean") {
      zodType = "z.boolean()";
    } else if (p.schema?.enum) {
      const vals = (p.schema.enum as string[]).map((v) =>
        `"${escapeStr(String(v))}"`
      );
      zodType = `z.enum([${vals.join(", ")}])`;
    }
    fields.push(`  ${fieldName}: ${zodType}.optional()${desc},`);
  }

  // Request body fields (for create/update)
  if (op.requestBody?.properties) {
    const required = new Set(op.requestBody.required ?? []);
    for (const [name, prop] of Object.entries(op.requestBody.properties)) {
      if (name === "id") continue;
      const fieldName = sanitizeFieldName(name);
      if (seenFields.has(fieldName)) continue;
      seenFields.add(fieldName);
      const fieldZod = schemaToZod(prop, { indent: 2 }, 2);
      const optSuffix = required.has(name) ? "" : ".optional()";
      const desc = prop.description
        ? `.describe("${escapeStr(truncateStr(prop.description))}")`
        : "";
      fields.push(`  ${fieldName}: ${fieldZod}${optSuffix}${desc},`);
    }
  }

  if (fields.length === 0) {
    return "z.object({})";
  }

  return `z.object({\n${fields.join("\n")}\n    })`;
}

/** Generate list method body */
function generateListBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = resourceNameOf(method);

  return `${indent}    const startMs = Date.now();
${indent}    const query = queryEntries(args, ${
    queryFieldsLiteral(method.operation)
  });
${indent}
${indent}    const { results, truncated } = await snykApiPaginated(
${indent}      apiToken,
${indent}      \`${apiPath}\`,
${indent}      version,
${indent}      query,
${indent}    );
${indent}
${indent}    if (truncated) {
${indent}      context.logger.info("WARNING: results truncated at {count} (pagination cap)", { count: results.length });
${indent}    }
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", "main", {
${indent}      items: results,
${indent}      truncated,
${indent}      fetchedAt: new Date().toISOString(),
${indent}      durationMs: Date.now() - startMs,
${indent}      collectedBy: EXTENSION_NAME,
${indent}    });
${indent}
${indent}    context.logger.info("Found {count} ${resourceName}", { count: results.length });
${indent}    return { dataHandles: [handle] };`;
}

/** Generate get method body */
function generateGetBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = resourceNameOf(method);
  const idParam = method.operation.pathParams[
    method.operation.pathParams.length - 1
  ];
  const instanceExpr = idParam
    ? `sanitizeInstanceName(String(args.${sanitizeFieldName(idParam.name)}))`
    : '"latest"';

  const qsSetup = querySetup(method.operation, indent);
  const qsSuffix = qsSetup ? "${qs}" : "";

  return `${qsSetup}${indent}    const result = await snykApi(
${indent}      apiToken,
${indent}      "GET",
${indent}      \`${apiPath}${qsSuffix}\`,
${indent}      version,
${indent}    );
${requireLine(method, indent)}${indent}
${indent}    const handle = await context.writeResource("${resourceName}", ${instanceExpr}, result);
${indent}    context.logger.info("Fetched ${resourceName}", {});
${indent}    return { dataHandles: [handle] };`;
}

/** Generate create method body */
function generateCreateBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = resourceNameOf(method);
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];
  const qsSetup = querySetup(method.operation, indent);
  const qsSuffix = qsSetup ? "${qs}" : "";

  return `${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set<string>(${
    JSON.stringify(excludeNames)
  });
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }
${qsSetup}${indent}
${indent}    const result = await snykApi(
${indent}      apiToken,
${indent}      "POST",
${indent}      \`${apiPath}${qsSuffix}\`,
${indent}      version,
${indent}      body,
${indent}    );
${requireLine(method, indent)}${indent}
${indent}    const id = sanitizeInstanceName(String((result as { id?: unknown }).id ?? "created"));
${indent}    const handle = await context.writeResource("${resourceName}", id, result);
${indent}    context.logger.info("Created ${resourceName} {id}", { id });
${indent}    return { dataHandles: [handle] };`;
}

/** Generate update method body */
function generateUpdateBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const resourceName = resourceNameOf(method);
  const httpMethod = method.operation.httpMethod.toUpperCase();
  const idParam = method.operation.pathParams[
    method.operation.pathParams.length - 1
  ];
  const instanceExpr = idParam
    ? `sanitizeInstanceName(String(args.${sanitizeFieldName(idParam.name)}))`
    : '"updated"';
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];
  const qsSetup = querySetup(method.operation, indent);
  const qsSuffix = qsSetup ? "${qs}" : "";

  return `${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set<string>(${
    JSON.stringify(excludeNames)
  });
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }
${qsSetup}${indent}
${indent}    const result = await snykApi(
${indent}      apiToken,
${indent}      "${httpMethod}",
${indent}      \`${apiPath}${qsSuffix}\`,
${indent}      version,
${indent}      body,
${indent}    );
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", ${instanceExpr}, result);
${indent}    context.logger.info("Updated ${resourceName}", {});
${indent}    return { dataHandles: [handle] };`;
}

/** Generate delete method body */
function generateDeleteBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  const idParam = method.operation.pathParams[
    method.operation.pathParams.length - 1
  ];
  const idRef = idParam
    ? `args.${sanitizeFieldName(idParam.name)}`
    : '"unknown"';

  const qsSetup = querySetup(method.operation, indent);
  const qsSuffix = qsSetup ? "${qs}" : "";

  return `${qsSetup}${indent}    await snykApi(
${indent}      apiToken,
${indent}      "DELETE",
${indent}      \`${apiPath}${qsSuffix}\`,
${indent}      version,
${indent}    );
${indent}
${indent}    context.logger.info("Deleted resource {id}", { id: ${idRef} });
${indent}    return { dataHandles: [] };`;
}

/** Generate action method body */
function generateActionBody(
  method: ClassifiedMethod,
  apiPath: string,
  indent: string,
): string {
  // Strip whatever verb prefix the action's name carries (an action-classified
  // POST may be named create_/update_/get_*). This must match the resource-key
  // derivation in generateModelSource, or the method writes to an undeclared
  // resource spec.
  const resourceName = resourceNameOf(method);
  const httpMethod = method.operation.httpMethod.toUpperCase();
  const hasBody = method.operation.requestBody !== undefined;
  const pathParamNames = method.operation.pathParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const queryParamNames = method.operation.queryParams.map((p) =>
    sanitizeFieldName(p.name)
  );
  const excludeNames = [...pathParamNames, ...queryParamNames];

  const qsSetup = querySetup(method.operation, indent);
  const urlSuffix = qsSetup ? "${qs}" : "";
  let bodySetup = "";
  let bodyArg = "";
  if (hasBody) {
    bodySetup = `${indent}    const body: Record<string, unknown> = {};
${indent}    const excludeKeys = new Set<string>(${
      JSON.stringify(excludeNames)
    });
${indent}    for (const [k, v] of Object.entries(args)) {
${indent}      if (!excludeKeys.has(k)) body[k] = v;
${indent}    }
`;
    bodyArg = `\n${indent}      body,`;
  }
  bodySetup += qsSetup;

  return `${bodySetup}
${indent}    const result = await snykApi(
${indent}      apiToken,
${indent}      "${httpMethod}",
${indent}      \`${apiPath}${urlSuffix}\`,
${indent}      version,${bodyArg}
${indent}    );
${indent}
${indent}    const handle = await context.writeResource("${resourceName}", "latest", result ?? {});
${indent}    context.logger.info("Executed ${method.name}", {});
${indent}    return { dataHandles: [handle] };`;
}

/**
 * True when a get/create body must reject an empty reply. Only operations the
 * spec says return content qualify: a create that answers 204 (for example a
 * relationship update) succeeds with no body, and failing it would report an
 * error after the server already applied the change.
 */
function requiresBody(method: ClassifiedMethod): boolean {
  return (method.type === "get" || method.type === "create") &&
    method.operation.hasResponseBody;
}

/** The requireBody statement for a method, or "" when an empty reply is fine. */
function requireLine(method: ClassifiedMethod, indent: string): string {
  return requiresBody(method)
    ? `${indent}    requireBody(result, "${method.name}");\n`
    : "";
}

/** True for a query parameter whose schema is an array. */
function isArrayParam(p: ParameterObject): boolean {
  return p.schema?.type === "array";
}

/**
 * Emit the object literal mapping each query argument to its API parameter.
 * Argument names are sanitized identifiers; API names can contain dots (for
 * example `meta.count`), so the original name travels with the field. Arrays
 * join with commas only when the spec says `explode: false`; otherwise each
 * value repeats the key (the OpenAPI default for query parameters).
 */
function queryFieldsLiteral(op: GroupedOperation): string {
  const entries: string[] = [];
  // A query parameter whose argument name matches a path parameter shares one
  // argument with it; the path value wins, as in the args schema.
  const seen = new Set<string>(
    op.pathParams.map((p) => sanitizeFieldName(p.name)),
  );
  for (const p of op.queryParams) {
    const field = sanitizeFieldName(p.name);
    if (seen.has(field)) continue;
    seen.add(field);
    const comma = isArrayParam(p) && p.explode === false;
    entries.push(
      `${field}: { name: ${JSON.stringify(p.name)}${
        comma ? ", comma: true" : ""
      } }`,
    );
  }
  return entries.length === 0 ? "{}" : `{ ${entries.join(", ")} }`;
}

/**
 * Emit the `const qs = ...` statement for a non-list method, or "" when the
 * operation has no query parameters. Ends with a newline when non-empty.
 */
function querySetup(op: GroupedOperation, indent: string): string {
  if (op.queryParams.length === 0) return "";
  return `${indent}    const qs = toQueryString(queryEntries(args, ${
    queryFieldsLiteral(op)
  }));\n`;
}

/** Build the API path with template literal substitution */
function buildApiPath(path: string, scope: string): string {
  const primaryParam = scope === "org"
    ? "org_id"
    : scope === "group"
    ? "group_id"
    : null;
  const primaryVar = scope === "org"
    ? "orgId"
    : scope === "group"
    ? "groupId"
    : null;

  return path.replace(/\{([^}]+)\}/g, (_, name) => {
    if (primaryParam && name === primaryParam) {
      return `\${encodeURIComponent(${primaryVar})}`;
    }
    // Secondary scope params become args references
    if (name === "org_id") {
      return `\${encodeURIComponent(String(args.org_id))}`;
    }
    if (name === "group_id") {
      return `\${encodeURIComponent(String(args.group_id))}`;
    }
    return `\${encodeURIComponent(String(args.${sanitizeFieldName(name)}))}`;
  });
}

function sanitizeFieldName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_|_$/g, "")
    .replace(/^\d/, "_$&");
}

/**
 * True when a method's generated body references sanitizeInstanceName. This
 * MUST stay in lockstep with the body generators:
 *   - create: always (wraps the API-returned id, falling back to "created")
 *   - get / update: only when a trailing path param supplies the instance id
 *     (otherwise the body uses the constant "latest"/"updated")
 *   - list, action, delete: never
 */
function methodEmitsSanitize(method: ClassifiedMethod): boolean {
  if (method.type === "create") return true;
  if (method.type === "get" || method.type === "update") {
    return method.operation.pathParams.length > 0;
  }
  return false;
}

function toPascalCase(name: string): string {
  return name
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}

/**
 * Append `.passthrough()` to a generated object schema so unknown API-returned
 * fields survive validation instead of being stripped. Output/resource schemas
 * describe observed reality, which the spec never fully captures, so unknown
 * fields must pass through. Only applies to a top-level `z.object({...})`; other
 * shapes (records, unions, unknown) are returned unchanged.
 */
function withPassthrough(zodExpr: string): string {
  if (!zodExpr.startsWith("z.object({")) return zodExpr;
  // Lenient mapping already attaches it (at every depth); never double up.
  if (/\.passthrough\(\)(\.nullable\(\))?$/.test(zodExpr)) return zodExpr;
  // `.passthrough()` must attach to the ZodObject, not a wrapper: a nullable
  // object is `z.object({...}).nullable()` and ZodNullable has no
  // `.passthrough()`. Insert before the trailing `.nullable()` in that case.
  if (zodExpr.endsWith(".nullable()")) {
    return `${
      zodExpr.slice(0, -".nullable()".length)
    }.passthrough().nullable()`;
  }
  return `${zodExpr}.passthrough()`;
}

function escapeStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ");
}

function truncateStr(s: string): string {
  return truncateAtBoundary(s, 80);
}
